Add Russian translation (ru)
mastodon/mastodon pull request #1023
Opened 2017-04-06 02:48 UTC by rkarabut

Hello! Translated everything. For now, 'federated timeline' got worded as 'глобальная лента' ('global timeline') for lack of a better term, 'fediverse' is just 'общая сеть' ('common network'). 'Toot!' is 'Протрубить!' which is a bit long but will have to do. Had to look up some OAuth terms to translate Doorkeeper decently, everything appears to be in order as well. There also are some unavoidable (because of the current format) problems with numerals, though nothing too jarring I believe.  Cheers!

2017-04-08 02:30 UTC, yiskah approved these changes
This one looks good and comprehensive

2017-04-08 02:31 UTC, yiskah commented
@Gargron if u have the chance since this is your mother tongue I figure you may have opinions on this translation

2017-04-09 12:48 UTC, Gargron approved these changes

2017-04-09 12:59 UTC, Gargron requested changes

2017-04-09 12:59 UTC, Gargron commented on app/assets/javascripts/components/containers/mastodon.jsx
> +addLocaleData([...en, ...de, ...es, ...fr, ...pt, ...hu, ...uk, ...fi, ...eo ...ru]);
Missing comma after `...eo`

2017-04-10 10:51 UTC, Gargron approved these changes

2017-04-10 10:52 UTC, merged