Add invite comments
mastodon/mastodon pull request #10465
Opened 2019-04-03 14:35 UTC by ThibG

2019-04-03 16:17 UTC, Gargron commented
Was someone asking for this?

2019-04-03 16:59 UTC, ThibG commented
Yeah

2019-06-13 15:10 UTC, Gargron requested changes

2019-06-13 15:10 UTC, Gargron commented on app/models/invite.rb
> +#  note       :text
So is it a `comment` or a `note`?

2019-07-23 15:43 UTC, ThibG commented
I think the reason why this hadn't been merged was to not add a new translatable string just before an upcoming release? If so, this could be merged now

2019-08-19 07:00 UTC, ThibG commented
@Gargron can we get that in before the 3.0 call for translations?

2019-08-19 09:40 UTC, Gargron approved these changes

2019-08-19 09:40 UTC, merged