Explicitly disable storage of REST API results
mastodon/mastodon pull request #10655
Opened 2019-04-30 09:44 UTC by ThibG

Fixes #10652

2019-05-03 05:59 UTC, ykzts approved these changes

2019-05-03 14:22 UTC, Gargron requested changes
Is the idea that you skip the headers on all API responses that use `render_cached_json`? Because in that case you've missed `/api/v1/instance` as well as `/api/v1/instance/activity`

2019-05-03 16:35 UTC, ThibG commented
Oh, yeah, indeed. Fixed that.

2019-05-03 18:39 UTC, Gargron approved these changes

2019-05-03 18:39 UTC, merged

2019-05-22 21:20 UTC, ariasuni commented
Thanks a lot, this is so much better now!