Record account suspend/silence time and keep track of domain blocks
mastodon/mastodon pull request #10660
Opened 2019-05-01 09:41 UTC by ThibG

Currently, undoing an instance block will either unblock *every* blocked person on that instance or none (depending on the moderator's choice), because an instance block translates to an individual block for every user of that instance.

This change records the time an user was blocked, and ties the unblock part to blocks performed *exactly* at the same time as the instance block.

This is a work in progress because we have to figure out what to do with instances that were blocked before that PR. The code in the PR will *not* unblock them, which is probably not what we want to do.

Also need to add tests and make sure the interface is clear.

2019-05-01 11:50 UTC, ThibG commented
Updated. The unblock screen won't ask whether you want to unblock *all* existing accounts of that instance anymore, and will instead give the count of accounts that would actually be unblocked.

The accounts affected are those whose block date matches that of the domain block or are `nil`. That is, those who were definitely blocked through the domain block as well as those who were blocked before the feature was merged. There's a few things we could do slightly differently in that regard, but not much.

2019-05-01 15:54 UTC, Gargron reviewed
We could remove the booleans

2019-05-01 16:21 UTC, ThibG commented
We definitely could, I just wanted to avoid a costly and error-prone migration script.



Le 1 mai 2019 17:55:22 GMT+02:00, Eugen Rochko <notifications@github.com> a écrit :
>Gargron commented on this pull request.
>
>We could remove the booleans
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tootsuite/mastodon/pull/10660#pullrequestreview-232629983

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

2019-05-09 23:26 UTC, nightpool commented
I think the idea here is good but removing the boolean columns now is going to save us a ton of headaches down the road wrt our data model.

If you really really don't want to remove the booleans, then we should encapsulate any logic that refers to the booleans or the dates into the account model so that we only have to care about the legacy data model in one place.

2019-05-11 13:38 UTC, ThibG commented
I have changed the migration script to set the `silenced_at` and `suspended_at` fields of existing accounts to the date of the corresponding domain block if there is one, and to the current time otherwise.
I have changed the code to not use the `suspended` and `silenced` fields anymore and updated the tests accordingly.
Finally, I have added a post-deployment migration script to remove those columns from the database.

I have **not** tried the migration yet.

2019-05-11 17:00 UTC, nightpool requested changes
First pass. I think we can narrow down the amount of files touched by this change, especially spec files as noted below. We should make sure we're using the `suspend!` and `silence!` methods in specs going forward.

2019-05-11 17:47 UTC, ThibG commented on spec/controllers/application_controller_spec.rb
> +      sign_in(Fabricate(:user, account: Fabricate(:account, suspended_at: nil)))
I've tried to do that but I'm not quite sure how to do that, or if it is even possible

2019-05-11 19:55 UTC, nightpool requested changes
now that we can undo domain blocks precisely, is there any argument for leaving in the ability to undo them and NOT unsilence/unsuspend affected users? it seems like an extra level of complexity that doesn't help anyone

2019-05-11 19:55 UTC, nightpool commented on app/models/account.rb
> +    !silenced_at.nil?
prefer `.present?` to `!thing.nil?`

2019-05-11 19:55 UTC, nightpool commented on app/models/account.rb
> +    date = Time.now.utc if date.nil?
`date ||= Time.now`

2019-05-11 19:55 UTC, nightpool commented on app/models/account.rb
> +    !suspended_at.nil?
.present per above

2019-05-11 19:55 UTC, nightpool commented on app/models/account.rb
> +    date = Time.now.utc if date.nil?
||= per above

2019-05-11 19:55 UTC, nightpool commented on app/services/resolve_account_service.rb
> +    @account              = Account.new(username: @username, domain: @domain)
I don't agree with this whitespace change but it's also not a huge deal. this line is semantically different from the lines that follow, so they shouldn't be grouped together

2019-05-12 11:08 UTC, ThibG commented
Removed the `retroactive` option as suggested, making *all* unblocks/unsilences retroactive.

This removes the checkbox but not the text:

![image](https://user-images.githubusercontent.com/384364/57581382-fe402f80-74b6-11e9-83f9-384814349156.png)

2019-05-13 02:25 UTC, nightpool commented on spec/services/block_domain_service_spec.rb
> +  let!(:already_banned_account) { Fabricate(:account, username: 'badguy', domain: 'evil.org', suspended: true, silenced_at: 1.day.ago) }
both `suspended` and `silenced_at`?

2019-05-13 02:26 UTC, nightpool approved these changes
LGTM % a minor question about the tests

2019-05-14 17:05 UTC, merged

2019-05-29 09:03 UTC, JamesABDL commented
I think this has broken the explore page:

```
method=GET path=/explore format=html controller=DirectoriesController action=index status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column accounts.suspended does not exist
```

2019-05-29 09:05 UTC, Gargron commented
Need to tootctl cache clear