Update CONTRIBUTING.md
mastodon/mastodon pull request #11017
Opened 2019-06-09 20:18 UTC by mighty-joey

Made some changes to make contributing to this project a bit more approachable for the newbie open source developer.

2019-06-09 20:34 UTC, marek-lach commented
Such a guide should probably also include steps on how to create a fork in the first place, and also how to create a branch in your own repository to contribute to?

2019-06-09 23:06 UTC, mighty-joey reviewed
Updated to add additional info

2019-06-09 23:39 UTC, nightpool requested changes
Hey! Thanks for the contribution. I agree that we need more detailed and approachable instructions on how to contribute changes!

Left a couple of comments about specifics but overall i'm kind of confused about who the target audience is for this step-by-step guide. Someone who's familiar with a feature-branch-based git workflow but has never used github before? Someone who can install, make changes to, and test the rails app but hasn't used git? It assumes that the reader will already be familiar with extremely crucial steps like "how to run the app" and "how to push changes to a branch"—or even "what a branch is". I'm not sure there's an audience that understands all of these concepts but needs a step-by-step guide on how to make a pull request. 

Also, it looks like these instructions were just taken wholesale from https://help.github.com/en/articles/creating-a-pull-request-from-a-fork? That's a little bit sketchy.

I would suggest re-writing this section to cover proposing changes using the Github web editor, which is much easier for new users, or maybe just linking to https://help.github.com/en/articles/editing-files-in-another-users-repository

Thank you for taking the time and initiative to start this conversation! I would love to see an improvement in mastodon's getting started documentation for contributing

2019-06-09 23:39 UTC, nightpool commented on CONTRIBUTING.md
> +8. If you do not want to allow anyone with push access to the upstream repository to make changes to your PR, unselect Allow edits from maintainers.
the distinction here is confusing and probably not particularly useful in a entry-level tutorial like this one

2019-06-09 23:39 UTC, nightpool commented on CONTRIBUTING.md
> +1. Fork a repository from Mastodon and create a branch to build new features or test out ideas - instructions available here: https://help.github.com/en/articles/fork-a-repo
These instructions are really long and there's a much easier way to make pull requests by using the Github web editor for small changes.

2019-06-09 23:39 UTC, nightpool commented on CONTRIBUTING.md
> +6. Use the head fork drop-down menu to select your fork, then use the compare branch drop-down menu to select the branch you made your changes in.
assuming someone knows what a branch is or how to make changes on it doesn't seem to make sense for this level of introductory guide?

2019-06-09 23:43 UTC, mighty-joey commented
Thanks for considering. I proposed these changes for a newcomer like myself. I am new to GitHub, and a CS student. This was a requirement for a course I am taking.

2019-07-03 03:44 UTC, Gargron requested changes

2019-07-03 03:44 UTC, Gargron commented on CONTRIBUTING.md
> +1. Fork a repository from Mastodon and create a branch to build new features or test out ideas - instructions available here: https://help.github.com/en/articles/fork-a-repo
Maybe this link could be like `([See instructions](https://help.github.com/en/articles/fork-a-repo))` for brevity?

2019-07-03 03:44 UTC, Gargron commented on CONTRIBUTING.md
> +8. If you do not want to allow anyone with push access to the upstream repository to make changes to your PR, unselect Allow edits from maintainers.
I feel like this line is not necessary.

2019-07-03 20:13 UTC, closed without merging

2019-07-03 20:13 UTC, nightpool commented
closed due to inactivity