Add audio uploads
mastodon/mastodon pull request #11123
Opened 2019-06-19 15:27 UTC by Gargron

Fix #4827

Accept uploads of OGG, WAV, FLAC, OPUS and MP3 files, and converts them to OGG. Media attachments get a new `audio` type. In the UI, audio uploads are displayed identically to video uploads.

2019-06-19 21:17 UTC, nightpool requested changes

2019-06-19 21:17 UTC, nightpool commented on app/javascript/mastodon/components/status.js
>          const video = status.getIn(['media_attachments', 0]);
mb rename video to something more generic?

2019-06-19 21:17 UTC, nightpool commented on app/javascript/mastodon/components/status.js
>          const video = status.getIn(['media_attachments', 0]);
attachment?

2019-06-19 21:17 UTC, nightpool commented on app/views/stream_entries/_detailed_status.html.haml
> +    - if status.media_attachments.first.video? || status.media_attachments.first.audio?
let's put this into a method on MediaAttachment, like `use_video_player?`

2019-06-19 21:17 UTC, nightpool commented on app/views/stream_entries/_simple_status.html.haml
> +    - if status.media_attachments.first.video? || status.media_attachments.first.audio?
as above

2019-06-19 21:17 UTC, nightpool commented on app/services/post_status_service.rb
> +    raise Mastodon::ValidationError, I18n.t('media_attachments.validations.images_and_video') if @media.size > 1 && @media.find { |x| x.video? || x.audio? }
this should be `larger_media_format?` right?

2019-06-19 21:17 UTC, nightpool commented on app/controllers/media_controller.rb
> +    raise ActiveRecord::RecordNotFound unless @media_attachment.video? || @media_attachment.gifv? || @media_attachment.audio?
can/should this also be `larger_media_format?`

2019-06-19 21:40 UTC, nightpool approved these changes
LGTM

2019-06-19 21:42 UTC, merged

2019-06-21 20:51 UTC, koyuawsmbrtn commented
Sick! :tada:

2019-06-22 10:09 UTC, tn5421 commented
Is there any way we can simply embed the file as-is, without transcoding lossy source files to another format?

2019-06-22 10:11 UTC, Gargron commented
No, it won't be playable on all platforms then

2019-06-22 10:13 UTC, tn5421 commented
Perhaps an option could be included in a users settings that allows them to override this default setting, with a warning given to the tune of your reply.

if I upload a 96kbps opus file and it gets transcoded to 192kbps mp3 it's going to sound like a 96kbps mp3 regardless of the extra file size

2019-06-22 12:21 UTC, Gargron commented
We use variable bitrate so I don't think the file will be bigger if the source isn't higher quality

2019-06-22 13:26 UTC, koyuawsmbrtn commented
Suggestion: Make the audio player smaller like in the previous PR

2019-06-22 16:43 UTC, trwnh commented
@tn5421 96kbps opus and 96kbps mp3 are not the same at all -- the 96kbps opus will sound vastly better since the opus codec is more efficient than mp3. also as stated, with variable bitrate the bitrate of a section of audio is allowed to dip down. there is still a quality loss with lossy->lossy transcode, but not so much that it makes the audio unusable.

what could be done is, if you are uploading an mp3 and it is already below a certain size or bitrate, then the transcode is skipped.

2019-06-22 20:08 UTC, Gargron commented
> what could be done is, if you are uploading an mp3 and it is already below a certain size or bitrate, then the transcode is skipped.

Nothing needs to be done. That's how it is