Add more specific class names to notification divs
mastodon/mastodon pull request #1120
Opened 2017-04-07 01:06 UTC by chris-martin

I found myself wanting to add some custom CSS to fav/boost notifications, but there weren't any CSS classes to distinguish them. This diff just adds some classes. It shouldn't directly affect how anything renders in the default style.

2017-04-08 03:00 UTC, yiskah commented
Unsure if we should merge this when the classes don't call anything in the official unmodified code. Seems messy.

2017-04-08 11:39 UTC, ineffyble commented
If the class names are similar to current ones, and don't clash, then adding them as "placeholder" classes doesn't feel inherently bad.

2017-04-08 18:58 UTC, Gargron requested changes

2017-04-08 18:58 UTC, Gargron commented on app/assets/javascripts/components/features/notifications/components/notification.jsx
> +      <div className='notification notification--follow'>
When it's a namespaced (nested) element: `parent__child`. When it's a modifier: `parent-modifier`. I see nothing wrong with this PR in general but the format of these needs to be fixed.

2017-04-08 23:30 UTC, chris-martin commented on app/assets/javascripts/components/features/notifications/components/notification.jsx
> +      <div className='notification notification--follow'>
Oh sorry, when I saw the class names with `__` I assumed you were following [BEM](http://getbem.com/introduction/). Will update.

2017-04-08 23:34 UTC, chris-martin commented
@Gargron Updated with requested changes.

2017-04-09 18:44 UTC, yiskah approved these changes
These look to be the requested changes

2017-04-10 20:41 UTC, Gargron approved these changes

2017-04-10 20:41 UTC, merged