Added logout to dropdown menu
mastodon/mastodon pull request #11353
Opened 2019-07-18 17:32 UTC by koyuawsmbrtn

First bigger pull request. Need some review on localization, haven't tested this PR yet.

2019-07-18 23:51 UTC, Gargron requested changes

2019-07-18 23:51 UTC, Gargron commented on app/javascript/mastodon/components/dropdown_menu.js
>      const { text, href = '#' } = option;
Add `method`

2019-07-18 23:51 UTC, Gargron commented on app/javascript/mastodon/components/dropdown_menu.js
> +    if (href === '/auth/sign_out') {
Remove this section and just pass `method` from outside

2019-07-18 23:51 UTC, Gargron commented on app/javascript/mastodon/features/compose/components/action_bar.js
> +    menu.push({ text: intl.formatMessage(messages.logout), href: '/auth/sign_out' });
I.e. add `method: 'delete'` here

2019-07-18 23:56 UTC, Gargron requested changes

2019-07-18 23:56 UTC, Gargron commented on app/javascript/mastodon/features/compose/components/action_bar.js
> +    menu.push({ text: intl.formatMessage(messages.logout), href: '/auth/sign_out', target: '', method: 'delete' });
If you pass `null` the `target` attribute won't be rendered.

2019-07-18 23:56 UTC, Gargron commented on app/javascript/mastodon/components/dropdown_menu.js
> +    const { text, href = '#', target = '_blank', method = '' } = option;
There is no need to set `method` to any default value. We don't want it rendered when nothing is given.

2019-07-19 00:14 UTC, koyuawsmbrtn commented
Hope this works now.

2019-07-19 01:58 UTC, Gargron approved these changes

2019-07-19 01:58 UTC, merged