Require at least 1 accepted follow from the remote domain for AUTHORIZED_FETCH mode.
mastodon/mastodon pull request #11556
Opened 2019-08-12 19:16 UTC by BenLubar

This means that remote instances will at least be *visible* to the admin.

2019-08-12 23:21 UTC, TemporaryUsername12481 commented
This effectively kills discoverability, should be an option disabled by default if implemented at all.

2019-08-13 11:05 UTC, ClearlyClaire requested changes
That would at the very least require a configuration option.

Also, as is, the change would effectively break federation, as it would reject the follow requests to begin with.

2019-08-13 11:06 UTC, ThibG commented
Oh, and remote instances *are* visible to the admin with `AUTHORIZED_FETCH`: each instance signs stuff with an actor, so that actor is visible in the list of remote actors.

2019-08-13 13:44 UTC, Gargron commented
A random follower on some local account is not anymore visibile to the admin than the existence of a remote account in the local database, as is already the case. And this would be a really breaking change. So I do not think this PR should be merged.

2019-08-17 16:08 UTC, closed without merging