Check if document.getElementById('tabs-bar__portal') is null
mastodon/mastodon pull request #11605
Opened 2019-08-19 03:36 UTC by zunda

While viewing LTL or FTL in multi-column mode, Javascript raises TypeError while narrowing the window:

![shonbori](https://user-images.githubusercontent.com/30968/63237655-5dd67580-c232-11e9-8591-134cd60bc177.gif)

While I'm not fully sure what I'm doing, this change seems to prevent the error.

2019-08-19 07:13 UTC, ThibG commented
I am afraid of two things with this change:
- That instead of crashing, it would just display the column header within the column instead of above it (which admittedly is better than crashing, but would still lead ton inconsistent experience and be hard to debug)
- That it may also happen for the `ColumnBackButton` component

2019-08-19 15:15 UTC, ThibG commented
The root issue is that the portal container and its content can be created in the same React render cycle, so whenever that happens, the target of the portal isn't in the DOM yet. This is obviously an issue, and I guess there ought to be a better way to achieve this, but I can't think of one.

Your patch does indeed prevent a crash and it does indeed make the header scroll within the column as opposed to stay on top like it should normally do.

One workaround I can think of is to add something to force the component to render again as long as the portal target doesn't exist, with something like:
```javascript
this.setState({ forceReRender: !this.state.forceReRender });
```

2019-08-19 15:16 UTC, ClearlyClaire requested changes

2019-08-19 15:16 UTC, ThibG commented on app/javascript/mastodon/components/column_header.js
> +      if (e === null) return component;
This branch should force the component to re-render, as otherwise, the column header will not scroll properly.

2019-08-19 18:33 UTC, zunda commented
@ThibG thanks so much for looking into this! It seems that the problem is far too much for my knowledge around React. May I close this PR and create an Issue so that you'd be able to take time to come up with a better solution?

2019-08-19 20:36 UTC, ThibG commented
Or I could add the workaround I suggested in this PR, if you don't mind?

2019-08-20 18:54 UTC, zunda commented
Reported as an Issue at #11630 and closing this. Cheers!

2019-08-20 18:54 UTC, closed without merging