Add timeline read markers API
mastodon/mastodon pull request #11762
Opened 2019-09-04 23:53 UTC by Gargron

Fix #4093, close #6756

2019-09-05 03:20 UTC, ykzts requested changes

2019-09-05 03:20 UTC, ykzts commented on app/javascript/mastodon/actions/markers.js
> +  console.log('Saving timeline markers...', beacon);
```suggestion
  console.log('Saving timeline markers...', beacon); // eslint-disable-line no-console
```

2019-09-05 03:20 UTC, ykzts commented on app/javascript/mastodon/actions/markers.js
> +import api from '../api';
unused?

2019-09-05 03:36 UTC, ykzts approved these changes

2019-09-06 11:55 UTC, merged

2019-09-08 16:30 UTC, nolanlawson commented
I have a few questions about this implementation:

1. It seems the Mastodon webapp will submit the markers in the unload event. So if a user keeps their tab open in their browser and never closes it, another client will never know what the last read position is? It seems like it may be better to do this lazily (e.g. every few minutes), as well as during the unload event and when a page goes into a background tab.
2. This is only for the home/notifications timelines right now, if I understand correctly?
3. Is the assumption that, on first load, a client will immediately scroll to the saved position in the timeline if a marker is found? So if a user has not checked Mastodon in several days and there are 100s of statuses, should the app load all 100+ of them and then scroll to the position? Or give up and reset the position? Or lazily show the new content?

/cc @charlag

2019-09-08 17:34 UTC, charlag commented
I agree with @nolanlawson on the first one.
I think when you open it on another client you just load:
 1. The latest ones
 2. Statuses with max_id = marker and 
and put a loadable gap between them (I think we do something like that already).
cc @connyduck

2019-09-08 19:01 UTC, Gargron commented
> It seems like it may be better to do this lazily (e.g. every few minutes), as well as during the unload event and when a page goes into a background tab.

Well, what if you have multiple clients open? And they all try to update the position at the same time? If they all use the streaming API I suppose they would arrive at similar or identical results but it seems wasteful to just keep updating it back and forth between them all. I'm not sure what the point would be of saving and loading a marker while a client is already actively open, the other app would then load the top of the timeline anyway..?

2019-09-08 20:32 UTC, charlag commented
It could be done in the way that we send it to the server and server writes it only when thr client stops communicating but that's complicated I guess.
I dot think anyone will load marker when the app is already open, only on startup. If two clients open, the last used one is likely to win (which makes sense to me).