Fix already-known remote private toots not being searchable by URL
mastodon/mastodon pull request #12336
Opened 2019-11-09 16:22 UTC by ThibG

Whenever an URL search fails, and an account is provided, try getting a
private status matching that URL from database.

Drawbacks of this approach:
- Only works for toots that are already known (but this should be fine in most cases, as in most cases, people who would have access to the toot would have followed the person and received already—this wouldn't be the case for significantly old toots, though), does not fetch them
- While it shouldn't be the case in practice, the `url` attribute may not be unique, as that cannot be enforced without fetching it. Thus, a misbehaving server may cause an URL to resolve in non-deterministic ways. I can't see any reason for someone to do that, though.
- The search may be slow, as there is no index on `url`.

2019-11-09 23:55 UTC, ykzts approved these changes

2019-11-10 11:03 UTC, Gargron requested changes

2019-11-10 11:03 UTC, Gargron commented on app/services/resolve_url_service.rb
> +      status = Status.find_by(id: @url) || Status.find_by(url: @url)
Did you mean `uri` instead of `id`?

2019-11-10 13:13 UTC, ThibG commented on app/services/resolve_url_service.rb
> +      status = Status.find_by(id: @url) || Status.find_by(url: @url)
… yes

2019-11-10 22:04 UTC, Gargron approved these changes

2019-11-10 22:04 UTC, merged