Add relationship-based options to status dropdowns
mastodon/mastodon pull request #12377
Opened 2019-11-13 21:51 UTC by Gargron

Instead of always showing mute/block, fetch up-to-date relationship when the status dropdown is opened, to be able to also show unmute/unblock as well as block/unblock the domain.

2019-11-14 04:32 UTC, trwnh commented
fixes #10514 i think?

2019-11-14 05:02 UTC, ykzts requested changes

2019-11-14 05:02 UTC, ykzts commented on app/javascript/mastodon/features/status/components/action_bar.js
> +    const { status, relationship, onBlockDomain } = this.props;
```suggestion
    const { status, onBlockDomain } = this.props;
```

> 'relationship' is assigned a value but never used.

2019-11-14 05:02 UTC, ykzts commented on app/javascript/mastodon/features/status/components/action_bar.js
> +    const { status, relationship, onUnblockDomain } = this.props;
```suggestion
    const { status, onUnblockDomain } = this.props;
```

> 'relationship' is assigned a value but never used.

2019-11-14 05:02 UTC, ykzts commented on app/javascript/mastodon/components/status_action_bar.js
> +    const { status, relationship, onBlockDomain } = this.props;
```suggestion
    const { status, onBlockDomain } = this.props;
```

> 'relationship' is assigned a value but never used.

2019-11-14 05:02 UTC, ykzts commented on app/javascript/mastodon/components/status_action_bar.js
> +    const { status, relationship, onUnblockDomain } = this.props;
```suggestion
    const { status, onUnblockDomain } = this.props;
```

> 'relationship' is assigned a value but never used.

2019-11-19 20:23 UTC, ykzts approved these changes

2019-11-19 20:24 UTC, merged

2019-11-21 09:25 UTC, umonaca commented
Well, not everyone wants the lovely bookmark icon to be removed...

2019-11-24 12:56 UTC, ThibG commented
Note that on non-mobile, this may cause the menu to change while displayed, because of the relationship info being updated after the menu gets shown.

On mobile, the behavior is different, with the updated relationship not updating the menu.