Drop support for Ruby 2.4
mastodon/mastodon pull request #12834
Opened 2020-01-12 16:08 UTC by Shleeble

2020-01-13 11:18 UTC, Gargron requested changes

2020-01-13 11:18 UTC, Gargron commented on Gemfile
> +ruby '>= 2.5.0', '< 3.0.0'
Not necessary

2020-01-13 11:18 UTC, Gargron commented on README.md
> +- **Redis** 4+
This is probably part of another PR? Until Sidekiq 6.0 is merged I believe we are still compatible with Redis 3, for example.

2020-01-14 02:24 UTC, Shleeble commented
@Gargron the scope of this PR has been pulled back to just removing the CircleCI -- and NOT a release focused drop of support as I originally intended.

2020-01-14 07:52 UTC, Gargron approved these changes

2020-01-15 01:30 UTC, ykzts approved these changes

2020-01-15 06:45 UTC, merged