Add touch icons for Chrome, iOS and Windows 10
mastodon/mastodon pull request #130
Opened 2016-11-02 14:19 UTC by fhemberger

2016-11-02 14:25 UTC, fhemberger commented
Fixes #112.

2016-11-02 14:41 UTC, rowan-m requested changes

2016-11-02 14:41 UTC, rowan-m commented on public/manifest.json
> +	"name": "Mastodon",
I would add `short_name` and `description`.

2016-11-02 14:41 UTC, rowan-m commented on public/manifest.json
> +	"display": "standalone"
I would add `"start_url": "/#/statuses/home"`

2016-11-02 15:03 UTC, fhemberger commented on public/manifest.json
> +	"name": "Mastodon",
If no `short_name` is given, `name` will be used instead.

2016-11-02 15:05 UTC, fhemberger commented on public/manifest.json
> +	"name": "Mastodon",
Added `description` and `start_url`.

2016-11-02 15:14 UTC, rowan-m approved these changes

2016-11-02 16:41 UTC, merged

2016-11-03 15:58 UTC, rowan-m commented on app/views/layouts/application.html.haml
> +    %link{:rel => "manifest", :href => "/assets/manifest.json"}/
This is currently deployed to `/manifest.json`. Either should point to the correct location or the file should be moved. Not sure what's more correct for the architecture.

2016-11-03 16:18 UTC, fhemberger commented on app/views/layouts/application.html.haml
> +    %link{:rel => "manifest", :href => "/assets/manifest.json"}/
Oh, yes. You're right. @Gargron any preferences on where to put those two files?

2016-11-03 16:27 UTC, Gargron commented on app/views/layouts/application.html.haml
> +    %link{:rel => "manifest", :href => "/assets/manifest.json"}/
Right... Actually, manifest.json links to some assets, but you have to be aware that they're compiled in the asset pipeline and the end result will have slightly different file names (with digests) which you can't know in advance. So manifest.json should probably be in the assets folder and be something like `manifest.json.erb` and link to the graphics using the `asset_path` helper.