Make the getting started ui more intuitive
mastodon/mastodon pull request #1309
Opened 2017-04-09 02:14 UTC by ameliavoncat

**Context**
* Some of the links in the `Getting started` tab change the context of the third column, while others leave the page entirely. 
* The ordering of the links makes the tab even less intuitive for a new user - the `Preferences` link navigates away from the page, while several of the links below it navigate within the column.

**Changes**
* Re-orders the links in the `Getting started` tab, grouping links which only change the context of the column together, and separating them from links which leave the page.
* Adds subheadings to clarify the distinction between the two groups of links.

2017-04-24 01:25 UTC, mjankowski requested changes
Can you rebase this, and add a screenshot of the chagnes?

2017-04-24 05:55 UTC, ameliavoncat commented
Done. 👍 

<img src="https://cloud.githubusercontent.com/assets/19511039/25323831/f6b7aa1a-2876-11e7-9ad2-b40f560b93d5.png" width=300px></img>

2017-04-25 09:22 UTC, mjankowski approved these changes

2017-04-25 12:22 UTC, ykzts commented on app/assets/javascripts/components/features/ui/components/column_subheading.jsx
> +  text: React.PropTypes.string.isRequired,
`React.PropTypes` is deprecated. Using `PropTypes` (and `import PropTypes from 'prop-types';)`.

2017-04-25 19:13 UTC, ameliavoncat commented on app/assets/javascripts/components/features/ui/components/column_subheading.jsx
> +  text: React.PropTypes.string.isRequired,
Updated. 😄

2017-04-25 23:21 UTC, merged