Feature/doorkeeper locale
mastodon/mastodon pull request #13132
Opened 2020-02-23 12:13 UTC by berkes

Doorkeeper locale was outdated. 

This caused "missing translation messges" in doorkeeper errors:

![afbeelding](https://user-images.githubusercontent.com/77059/75111818-3e376400-563e-11ea-8f5e-b10bf0d7d16b.png)

This PR attempts to sync with upstream en.yml, without loosing our customisations.

2020-02-24 21:20 UTC, Gargron requested changes

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> -    scopes:
Removing necessary strings

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        created_at: Created At
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        title: Authorization code
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        able_to: This application will be able to
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        prompt: Authorize %{client_name} to use your account?
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        secret: Secret
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        application_id: Application UID
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        callback_urls: Callback urls
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        title: New Application
Keep old

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> -        website: Application website
Removing necessary strings

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> -        scopes: Scopes
Removing necessary strings

2020-02-24 21:20 UTC, Gargron commented on config/locales/doorkeeper.en.yml
> +        name: Name
Keep old

2020-02-25 11:15 UTC, berkes commented
Please let me know if you'd rather have this PR rebased & force pushed. Or if you are OK with separate commits for the requested fixes.

2020-06-24 18:37 UTC, SuperSandro2000 commented
/unstale

2020-10-24 14:39 UTC, SuperSandro2000 commented
Bump

2020-10-24 16:52 UTC, berkes commented
@SuperSandro2000 anything else I can or should do, other than occasionally rebasing on master?

2020-10-24 20:22 UTC, SuperSandro2000 commented
IDK. I just keep spam bot away from things that are not spam.

2021-06-09 21:38 UTC, closed without merging