Polls improvements
mastodon/mastodon pull request #13257
Opened 2020-03-13 12:31 UTC by Sasha-Sorokin

This PR is dedicated to slightly improve polls by raising options limit and doing a redesign to avoid issues with that increase.

### Current changes

*(click each for description!)*

* <details>
  <summary><b>Redesign the polls</b> (<a href="https://github.com/tootsuite/mastodon/commit/753982638aae4bf5ea66f1840d2974629b697b52"><code>7539826</code></a>)</summary>
  This commit redesigns the polls to be more adaptive for upcoming changes to the options characters limit. The bar, or a "chart" is now displayed separately from the text. Vote check is now going afterwards the label and the percentages are taking less space.
  </details>
* <details>
  <summary><b>Raise poll option limit to 50 characters</b> (<a href="https://github.com/tootsuite/mastodon/commit/12ded91a8f9ce37c2575ddd9957726a239cae7ef"><code>12ded91</code></a>)</summary>
  This commit raises poll options character limit to 50 characters. It's a hard task to sometimes fit in 25 characters limit, especially in "lenghty" languages. To give posters more space for creativity, as with 500 characters limit, let's raise the limit for options too.
  </details>

---

### Screenshots (as of 7539826):

| Light theme | Dark theme |
|:----------------:|:---------------:|
| ![Screenshot of a poll in light theme](https://user-images.githubusercontent.com/10401817/76620775-87eddd00-6560-11ea-85cd-33bbdf8e8e4b.png) | ![Screenshot of a poll in dark hteme](https://user-images.githubusercontent.com/10401817/76620765-845a5600-6560-11ea-8b98-3c9af49b558c.png) |

---

### Feedback and review are appreciated!

After review these commits will be squashed with better description and PR marked as ready for merging.

2020-03-14 22:36 UTC, ThibG commented
I like that design (haven't actually reviewed the PR yet), this solves the “thicker bars” issue and is quite readable.

Also, no need to squash the commits, that's what Gargron does when merging PRs.

2020-03-17 12:28 UTC, ClearlyClaire requested changes
The CSS changes break the poll form
![image](https://user-images.githubusercontent.com/384364/76855888-5e7bcc80-6852-11ea-83e0-e7ae96e843d0.png)

Otherwise, it looks fine to me.

2020-03-17 13:18 UTC, Sasha-Sorokin commented
@ThibG r-right, that's because of bad refactoring with `poll__text` class. Should be fixed now.

2020-03-18 10:28 UTC, ClearlyClaire approved these changes
Looks fine to me.

(Also, attaching a screenshot of what it looks like with a multi-line poll option for other people to easily see/review)
![image](https://user-images.githubusercontent.com/384364/76951202-91ce6200-690b-11ea-85d2-9fe36f51f941.png)

2020-03-18 10:50 UTC, Sasha-Sorokin commented
You've just given me idea that it's probably still subtracts width that checkmark should use even if no checkmark is shown…

<p align=right><img src="https://user-images.githubusercontent.com/10401817/76953035-9c571e80-6940-11ea-9bd2-ccea83bc0c97.png" alt="Clippy saying “That's probably etter be fixed?”"></p>

2020-03-18 11:04 UTC, Sasha-Sorokin commented
Nah, I don't see easy ways to check if this poll was created by the user itself so I can mitigate that useless subtract (as no checkmark will be shown). Other ways lead to inconsistency in width, so I guess that's fine…

2020-04-02 07:56 UTC, Sasha-Sorokin commented
Is there something blocking this PR?

2020-04-02 15:10 UTC, merged