Add new vagrant log files to .gitignore
mastodon/mastodon pull request #13442
Opened 2020-04-09 08:54 UTC by mfmfuyu

Reference PR is #13384 

I'm verry sorry, I forgot to add new vagrant box log file to .gitignore
This PR is add new vagrant box log file to .gitignore

2020-04-09 15:07 UTC, ykzts approved these changes

2020-04-11 07:00 UTC, SuperSandro2000 requested changes

2020-04-11 07:00 UTC, SuperSandro2000 commented on .gitignore
> +ubuntu-bionic-18.04-cloudimg-console.log
I would just ignore all vagrant log files.

2020-04-11 07:14 UTC, mfmfuyu commented on .gitignore
> +ubuntu-bionic-18.04-cloudimg-console.log
Awesome! I forgot it...
Thank you very much for your suggestion!

2020-04-12 11:37 UTC, Gargron approved these changes

2020-04-12 11:37 UTC, merged