Check for a custom css file to help customization of instances
mastodon/mastodon pull request #1368
Opened 2017-04-09 20:13 UTC by Naouak

People are customizing their instance by modifying directly files from the git.

This pull request permit them to create a `custom.scss` file that will be loaded automatically instead of `application.scss`.

People will be able to rewrite completely the default css or modify variables easily with this system.

Can someone check my work? I'm not a rails dev and I did this with a lot of trials and errors, I'm not sure it's the best way to do it.

2017-04-12 11:27 UTC, expenses commented on app/helpers/style_helper.rb
> +    end
`asset_exist? 'custom.css' ? 'custom' : 'application'` might be simpler here. Otherwise, looking good.

2017-04-12 11:28 UTC, expenses commented on app/helpers/style_helper.rb
> +    end
Didn't mean to review >_<

2017-04-13 20:12 UTC, Mandragora2 commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( custom.css )
what happend if file does not exist ?

2017-04-13 20:12 UTC, Naouak commented on app/helpers/style_helper.rb
> +    end
I'm hoping that this helper will get more complicated in later versions (theme-list support? user setting?... etc.) so I think ternary operator may be a bit too much.

2017-04-13 20:13 UTC, Mandragora2 approved these changes

2017-04-13 20:13 UTC, Mandragora2 commented on docs/Running-Mastodon/Customizing.md
> +to see the changes.
👍 for the doc

2017-04-13 20:15 UTC, Naouak commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( custom.css )
It doesn't do anything. No error reported when custom.scss/custom.css is not there.

2017-04-15 00:26 UTC, Gargron requested changes
Great idea, just a few minor nitpicks!

2017-04-15 00:26 UTC, Gargron commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( custom.css )
I think you should move custom.css to the line above (`%w(a b)` creates an array `[a, b]`, it's exactly what this is for)

2017-04-15 00:26 UTC, Gargron commented on app/helpers/style_helper.rb
> +    if asset_exist?'custom.css'
Space after ? please!

2017-04-15 00:26 UTC, Gargron commented on docs/Running-Mastodon/Customizing.md
> +to see the changes.
This doc should move to tootsuite/documentation please!

2017-04-15 02:47 UTC, Naouak commented
I did all the requested changes. I will do a pull request for the removed documentation file when this pull request is accepted,

2017-04-15 20:47 UTC, Gargron approved these changes

2017-04-15 20:47 UTC, merged