Added support for configurable reserved usernames
mastodon/mastodon pull request #1382
Opened 2017-04-09 22:35 UTC by ngerakines

This PR includes changes to the account model to support the `reserved_usernames` validation check for local accounts. With it, a list of usernames can be added to settings.yml as "reserved" for the purpose of preventing people from registering accounts with those usernames.

2017-04-09 22:38 UTC, ngerakines commented on config/settings.yml
> +    - 'support'
I added "admin" and "support" as default entries because those are two account names that I wouldn't want people to steal.

2017-04-09 22:43 UTC, wxcafe commented on config/settings.yml
> +    - 'support'
Please add the other ones that were discussed on #1355

2017-04-09 22:46 UTC, ngerakines commented on config/settings.yml
> +    - 'support'
Done.

2017-04-09 22:54 UTC, Fastidious reviewed
How those get unreserved?

2017-04-09 22:57 UTC, ngerakines commented
Removing the configuration entry will allow the account to be created.

2017-04-09 23:01 UTC, wxcafe commented
It would be nice to be able to alias these accounts to another one, but this is a much bigger feature. I'll merge this when we know why the CI doesn't want to build (it's apparently not related to this tho) and I'll change the issue to reflect the change in scope

2017-04-09 23:04 UTC, ngerakines commented
Yeah, I saw the comment about aliasing, but decided to hold off on that one. A temporary solution for web visitors could be to have nginx/httpd rewrite rule samples.

Locally `rake` and spec file execution all looks good. I'm not sure what is going on with travis.

Thanks for taking a look and I'm glad it is useful.

2017-04-11 19:35 UTC, ngerakines commented
If there is anything that I can do to help this move along, please let me know. Looks like there is quite the backlog right now.

2017-04-19 09:46 UTC, bradurani requested changes

2017-04-19 09:46 UTC, bradurani commented on app/models/account.rb
> +  validates :username, presence: true, format: { with: /\A[a-z0-9_]+\z/i, message: 'only letters, numbers and underscores' }, uniqueness: { scope: :domain, case_sensitive: false }, length: { maximum:
`Setting.reserved_usernames ||= []`
should be
`Setting.revserved_username || []`

2017-04-29 09:43 UTC, ashfurrow commented
Thanks for the PR @ngerakines – looks good! Could you pull latest from master, review the changes, and address @bradurani 's comment above? Thanks again for your contribution!

2017-04-29 18:28 UTC, ngerakines commented on app/models/account.rb
> +  validates :username, presence: true, format: { with: /\A[a-z0-9_]+\z/i, message: 'only letters, numbers and underscores' }, uniqueness: { scope: :domain, case_sensitive: false }, length: { maximum:
Done!

2017-04-29 18:29 UTC, ngerakines commented
The branch has been updated from current master and the change request applied.

2017-04-29 21:26 UTC, ashfurrow commented
The code looks good, but there's a CI error. I've not seen it before, anyone have any ideas?

2017-05-13 13:52 UTC, hikaru-light commented on config/settings.yml
> +    - 'support'
LGTM:cake:

2017-05-13 16:39 UTC, hikaru-light commented
I have another way because I have implemented reserving usernames in another service.
May I push my branch?

2017-06-01 23:45 UTC, Gargron commented
The failure is because Setting.reserved_usernames is evaluated at class load time, which is before anything else, and in this case before the migrations finish running, so it runs a SELECT against an incomplete database.

2017-06-04 23:03 UTC, closed without merging