Add e-mail-based sign in challenge for users with disabled 2FA
mastodon/mastodon pull request #14013
Opened 2020-06-08 13:25 UTC by Gargron

2020-06-08 13:27 UTC, shleeable commented
Cool

2020-06-08 14:44 UTC, ClearlyClaire requested changes
This PR changes the login process so that users who do not have 2FA enabled have to—after successfully entering their password—enter a code sent to their e-mail address if they are logging from a new IP address **and** have not logged in in the past 2 weeks.

Those conditions seem reasonable. We may want to require that challenge on new IP addresses without the second condition, but I'm afraid this could be too annoying, especially with mobile users or people using the Tor Browser. Then again, they could be using 2FA to avoid the mail confirmation.

In addition to the rather minor comment I made inline, tests are failing because they pass session data with `otp_user_id` that you renamed to `attempt_user_id`.

2020-06-08 14:44 UTC, ThibG commented on app/controllers/concerns/two_factor_authentication_concern.rb
> +    elsif user.present? && (user.encrypted_password.blank? || user.valid_password?(user_params[:password]))
I feel like keeping the comments about getting the account from LDAP or PAM would make sense.

2020-06-09 07:51 UTC, ClearlyClaire approved these changes

2020-06-09 08:23 UTC, merged

2020-08-03 17:08 UTC, ThreeFx commented
Is there a way to disable this option? Every Mastodon instance without sending E-Mail support runs into issues here.

2020-08-03 17:33 UTC, Gargron commented
> Every Mastodon instance without sending E-Mail support

Running Mastodon without being able to send e-mails is impractical, so I would hope those are rare. If your users use 2FA to protect their accounts you won't run into the issue though.

2020-08-03 18:12 UTC, ThreeFx commented
Alright I kind of expected this. Thanks for the quick answer!