Refactor how public and tag timelines are queried
mastodon/mastodon pull request #14728
Opened 2020-09-04 13:52 UTC by Gargron

Contains *some* minor behaviour changes:

- Excluded suspended accounts from public timelines (was not enforced previously)
- No longer show silenced user own posts in public timelines (silenced users can no longer make public posts anyway)
- Don't allow any/all/none filters in RSS and JSON-LD versions of the public hashtag resource
- Make JSON-LD version of public hashtag resource support min_id/since_id (consistently with outbox)

2020-09-06 11:59 UTC, ThibG requested changes
I'm not sure I agree with the “Don't allow any/all/none filters in RSS and JSON-LD versions of the public hashtag resource” part, but otherwise it seems fine to me.

Minor remarks in inline comments.

Also, `HashtagQueryService` doesn't seem to be used anymore, but the PR doesn't remove its definition.

2020-09-06 11:59 UTC, ThibG commented on spec/models/public_feed_spec.rb
> +        Fabricate(:block, account: @account, target_account: blocked)
`@account.block!(blocked)` would be easier to read

2020-09-06 11:59 UTC, ThibG commented on spec/models/public_feed_spec.rb
> +        Fabricate(:block, account: blocked, target_account: @account)
`blocked.block!(@account)`… which makes me think the naming is a bit confusing

2020-09-06 11:59 UTC, ThibG commented on spec/models/public_feed_spec.rb
> +        Fabricate(:mute, account: @account, target_account: muted)
`@account.mute!(muted)`

2020-09-06 11:59 UTC, ThibG commented on app/models/public_feed.rb
> +  def initialize(account, options = {})
Documenting the `options` would be nice.

2020-09-06 11:59 UTC, ThibG commented on app/models/tag_feed.rb
> +  def initialize(tag, account, options = {})
Documenting the `options` would be nice.

2020-09-06 23:14 UTC, Gargron commented
> I'm not sure I agree with the “Don't allow any/all/none filters in RSS and JSON-LD versions of the public hashtag resource” part

Even if you discard that joining multiple tags is a more expensive operation, I don't think it's right for a JSON-LD resource to represent a complex union of different collections... It should be 1:1, in my opinion. Also nobody knows this feature even exists.

2020-09-07 07:20 UTC, ThibG approved these changes

2020-09-07 09:02 UTC, merged