Add IP-based rules
mastodon/mastodon pull request #14963
Opened 2020-10-10 17:00 UTC by Gargron

2020-10-11 13:43 UTC, ThibG requested changes
Requesting a few changes through inline comments.

Besides that, I'm a bit worried about how much this would scale: I have to admit I have no idea how many IP/subnets an instance would typically block, but I'm a bit concerned with the code loading the full list into RAM at once, as well as enumerating all subnet blocks to find a matching one. But maybe that's fine.

2020-10-11 13:43 UTC, ThibG commented on lib/mastodon/ip_blocks_cli.rb
> +        end
This doesn't cover the case where there are multiple IP blocks covering the same address (either net blocks with some wider than others, or multiple `IpBlock` records with the exact same target, as those aren't required to be unique).

2020-10-11 13:43 UTC, ThibG commented on app/models/user.rb
> +    !sign_up_ip.nil? && IpBlock.where(severity: :sign_up_requires_approval).where('ip >>= ?', sign_up_ip.to_s).exists?
That check is possibly quite slow.

2020-10-11 22:38 UTC, Gargron commented
> Besides that, I'm a bit worried about how much this would scale: I have to admit I have no idea how many IP/subnets an instance would typically block, but I'm a bit concerned with the code loading the full list into RAM at once, as well as enumerating all subnet blocks to find a matching one. But maybe that's fine.

I have two pieces of data to offer. One, by comparing to e-mail domain blocks I've accumulated over 4 years: 64, and a list of IPs I've blocked on iptables level: 291. So the assumption I am working with is that we're dealing with three digit numbers here, which is also why I'm not quick to add indices to this table.

2020-10-12 11:25 UTC, ThibG approved these changes
alright, looks good to me

still a bit worried about scaling, but based on your earlier comment, it should be fine

2020-10-12 14:33 UTC, merged

2020-10-13 01:58 UTC, Kjwon15 commented
How about allowlist for ip rules? it could be useful for school

2020-11-04 18:07 UTC, rodti commented
This is a great feature. A couple of nice-to-haves are to have the list sorted numerically, and to be able to edit existing IP rules (like the federation edit screen).