[css] reduce spacing between text elements on about pages
mastodon/mastodon pull request #1510
Opened 2017-04-11 03:12 UTC by dunn

The current margin is rather too large IMO.  Using awoo.space Guidelines as an example, this is what it's like currently:

<img width="539" alt="screen shot 2017-04-10 at 8 07 53 pm" src="https://cloud.githubusercontent.com/assets/985416/24891321/eb9ff670-1e29-11e7-9080-c404dd281051.png">

With the change, the spacing is more natural but not too tight:

<img width="529" alt="screen shot 2017-04-10 at 8 08 27 pm" src="https://cloud.githubusercontent.com/assets/985416/24891328/fe63c75a-1e29-11e7-922e-e375da477d43.png">

2017-04-12 00:07 UTC, thoragio requested changes
@dunn Given that `em` units are not being used in the stylesheet, I suggest sticking with pixels and using a value like `14px` or `16px`.

2017-04-12 00:38 UTC, dunn commented
@thoragio is there a reason for avoiding ems?  I thought generally they were preferred over pixels as a unit.

2017-04-12 08:38 UTC, thoragio commented
@dunn It's not about avoiding them; it's about being consistent with the codebase and following the established convention. That being said, rems and ems don't really make much difference in many contexts.  See this article for details if you're interested: https://hackernoon.com/rems-and-ems-and-why-you-probably-dont-need-them-664b9ce1e09f

2017-04-12 15:59 UTC, dunn commented
Fair enough.  Switched from `.5em` to `12px`.

2017-04-15 00:29 UTC, Gargron approved these changes

2017-04-15 00:29 UTC, merged