Fix compose form behavior in mobile view
mastodon/mastodon pull request #15555
Opened 2021-01-13 10:44 UTC by ThibG

Fixes #13094

Until this PR, when writing toots in mobile view, two `ComposeForm` components were rendered:
- one in the compose pane hidden by CSS
- one corresponding to the `/web/statuses/new` path

The auto-focus and auto-selection code was executed on the hidden `ComposeForm` (causing a crash in PaleMoon, see #13094) and wasn't executed on the displayed `ComposeForm` component.

This PR uses media queries to decide whether to render the compose pane's `ComposeForm`, avoiding unnecessary rendering the hidden component and avoiding the PaleMoon crash, and makes it so the auto-selection and auto-focus code gets executed when replying to toots in mobile view.

2021-02-11 00:09 UTC, Gargron requested changes

2021-02-11 00:09 UTC, Gargron commented on app/javascript/mastodon/features/compose/components/compose_form.js
> +    this.componentDidUpdate({ });
Can you please extract `componentDidUpdate` into another method instead and then call it from both?

2021-02-23 22:14 UTC, ClearlyClaire commented
ping @Gargron

2021-03-24 09:19 UTC, Gargron approved these changes

2021-03-24 09:19 UTC, merged