Add staff badges to web ui
mastodon/mastodon pull request #16167
Opened 2021-05-06 20:55 UTC by chandrn7

Addresses https://github.com/tootsuite/mastodon/issues/6702. Displays appropriate staff badge on web UI profiles. Exposes staff, mod, admin status via the API.

![Screen Shot 2021-05-06 at 4 41 54 PM](https://user-images.githubusercontent.com/25374112/117363539-b5939500-ae8a-11eb-9c18-1aef85666c49.png)
![Screen Shot 2021-05-06 at 4 42 15   ##PM](https://user-images.githubusercontent.com/25374112/117363546-b7f5ef00-ae8a-11eb-88c6-99ace4e91a95.png)
<img width="231" alt="Screen Shot 2021-05-06 at 4 53 05 PM" src="https://user-images.githubusercontent.com/25374112/117364152-8cbfcf80-ae8b-11eb-988f-7c2579889915.png">

2021-05-07 11:19 UTC, ClearlyClaire requested changes

2021-05-07 11:19 UTC, ClearlyClaire commented on app/serializers/initial_state_serializer.rb
> +      show_staff_badge: Setting.show_staff_badge,
This shouldn't be passed down to the UI but used to decide whether or not to include the badges in the REST API response.

2021-05-07 11:19 UTC, ClearlyClaire commented on app/serializers/rest/account_serializer.rb
> +  end
Those should only be returned if `Setting.show_staff_badge` is set.

2021-05-07 15:51 UTC, ClearlyClaire requested changes
Overall I'm in favor of this change, although I'm not too sure which shape the API should take, using three separate fields feels a bit much, maybe a `role` field with either role as a string would make better sense, I don't know.

In any case, the badge strings have to be translatable.

2021-05-07 16:16 UTC, ClearlyClaire approved these changes
Looks fine by me, @Gargron may want to comment on the API design, idk.

2021-05-25 23:17 UTC, chandrn7 commented
Any updates on this?

2021-10-11 05:55 UTC, closed without merging