Remove set-cookie header on custom.css
mastodon/mastodon pull request #16314
Opened 2021-05-26 02:19 UTC by tribela

`/custom.css` intended to be cached, But was not cached by nginx, cdn because it has `Set-Cookie` header.
This commit will fix that problem.

2021-05-26 02:21 UTC, ykzts approved these changes

2021-05-26 10:56 UTC, ClearlyClaire requested changes
This does not seem to actually work. I think I already had investigated `session_options[:skip]` in the past and it only worked with Rails 4?
In any case, I'm currently investigating why a session is accessed at all in the first place in this controller.

2021-05-26 11:12 UTC, ClearlyClaire commented
ok so, `session_options[:skip]` does kind of work, except it does not prevent a request with the `_session_id` cookie from having that cookie echoed back for some reason.

Cookies are initially set because of the `Localized` concern, so adding `skip_around_action :set_locale` should help. I'd also add a test in the testsuite to ensure no cookies are set from an anonymous request.

Now, because of the `_session_id` stuff, most requests will probably have a cookie anyway, still looking into how to get rid of that…

2021-05-26 11:17 UTC, ClearlyClaire commented
Adding the following avoids a session cookie being sent in all cases:
```ruby
  skip_before_action :update_user_sign_in
  skip_before_action :set_session_activity
  skip_around_action :set_locale
```

At this point, we may want to have the controller use another base controller class entirely, but this should be enough for the time being. More generally, we might want to review all controllers to ensure we are not needlessly updating/re-sending the session cookie.

2021-05-30 00:21 UTC, ClearlyClaire approved these changes

2021-05-30 00:21 UTC, ClearlyClaire commented on app/controllers/custom_css_controller.rb
> +    request.session_options[:skip] = true
I don't think it's of any use, but it doesn't hurt either.

2021-05-30 15:57 UTC, merged