Update account_serializer.rb: provide user email for OAuth resource owner
mastodon/mastodon pull request #16596
Opened 2021-08-10 20:20 UTC by frie

add user email to account data, which are provided in OAuth context (when a client authenticates at Mastodon and retrieves resource owner data)

2021-08-10 20:22 UTC, frie commented
motivated by OAuth for Fllarum where email is the base for identifying the authenticated user

2021-08-10 22:37 UTC, Gargron requested changes
This leaks the e-mail publicly and to any app

2021-08-11 05:50 UTC, weex commented
No one should ever merge this.

2021-08-11 07:58 UTC, frie commented
> This leaks the e-mail publicly and to any app

That's exactly what github is doing - what is the problem about that? AFAIK any provision of user data is authorized by the user (resource owner). Maybe Google and Twitter are not the best references for Mastodon, but most OAuth server implementations I have seen provide the email address of the ressource owner.

2021-08-11 09:30 UTC, ClearlyClaire commented
> > This leaks the e-mail publicly and to any app
> 
> That's exactly what github is doing - what is the problem about that? AFAIK any provision of user data is authorized by the user (resource owner). Maybe he OAuth server implementations of Google and Twitter are not the best references for Mastodon, but most OAuth server implementations I have seen provide the email address of the resource owner.

I'm not too familiar with the OAuth flow within Mastodon, and I'm also unsure the user email should be exposed as part of it, but your change goes far beyond: it serializes the user email of any local account in response to any REST API request from anyone. I hope you understand why that is not the way to go.

2021-08-11 13:05 UTC, frie commented
sorry, I am not at all familiar with the mastodon code do dig deeper into this. would be nice to support OAuth some time with the same quality as other sites do

2021-08-11 13:05 UTC, closed without merging