Allow keeping only 1 boosts/favs on auto deleting posts
mastodon/mastodon pull request #16653
Opened 2021-08-24 02:50 UTC by tribela

Some people want to keep posts that are boosted or favourited even if there are only one person engaged.

Related: #16529

2021-08-24 02:51 UTC, tribela commented
CC @ClearlyClaire

2021-08-24 07:14 UTC, ClearlyClaire requested changes
I'm not super happy with changing the meaning of an already-existing setting and localization strings, but since it's a conservative change and the feature isn't in any release yet, it's probably fine.

The feature and change itself looks fine to me, but the tests need to be adapted to the new behavior.

2021-08-26 11:48 UTC, ClearlyClaire approved these changes

2021-10-14 19:11 UTC, Gargron approved these changes

2021-10-14 19:11 UTC, merged