Italian files are now in the right place
mastodon/mastodon pull request #1694
Opened 2017-04-13 13:48 UTC by matteoaquila

I made a mess and put the Italian localisation files in the wrong place...
I'm so sorry, please forgive me 😭
Now those files are finally il config/locales as they should...
And I've updated settings_helper.rb and application.rb as @yookoala told me (#1679). Still working on it.jsx and all the other Javascript stuff.

2017-04-13 14:00 UTC, Gargron approved these changes

2017-04-13 14:09 UTC, Gargron requested changes

2017-04-13 14:09 UTC, Gargron commented on app/helpers/settings_helper.rb
> +    it: 'Italiano'
Missing `,` at end of line, syntax error

2017-04-13 14:17 UTC, matteoaquila commented on app/helpers/settings_helper.rb
> +    it: 'Italiano'
Come on, one day I'll finally be able to submit something **totally** correct, I'm learning, never lose hope. 😂 ❤️ 
(Thank you for the correction)

2017-04-13 15:36 UTC, yookoala commented
@matteoaquila: You have syntax error in your `devise.it.yml` file.

Same issue. According to YAML specifications, all strings start with these characters must be quoted
`:`, `{`, `}`, `[`, `]`, `,`, `&`, `*`, `#`, `?`, `|`, `-`, `<`, `>`, `=`, `!`, `%`, `@`, `

Therefore,
1. [line 11](https://github.com/tootsuite/mastodon/blob/efcf9448da60574a41d79964cece87008667cb41/config/locales/devise.it.yml#L11) cannot have unquoted strings start with symbol. Need to quote this value with `"`.
1. [line 14](https://github.com/tootsuite/mastodon/blob/efcf9448da60574a41d79964cece87008667cb41/config/locales/devise.it.yml#L14) cannot have unquoted strings start with symbol. Need to quote this value with `"`.

2017-04-13 20:26 UTC, Gargron approved these changes

2017-04-13 20:27 UTC, merged

2017-04-14 05:05 UTC, yookoala reviewed
You need to quote the whole value. Not just the variable.

E.g.

    "%{authentication_keys}" o password invalida.

should be 

    "%{authentication_keys} o password invalida."