Remove Redundant HSTS Header Declarations (nginx)
mastodon/mastodon pull request #17088
Opened 2021-12-01 23:40 UTC by mishfit

fix(#17083): remove redundant header declarations

only one add_header call is required for
`Strict-Transport-Security`

2021-12-02 06:28 UTC, Gargron commented
From [documentation](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header):

> There could be several add_header directives. These directives are inherited from the previous configuration level if and only if there are no add_header directives defined on the current level. 

Since there are other `add_header` calls in these location blocks, the HSTS header from the upper level is not inherited.

This likely does not fix #17083.

2021-12-02 06:35 UTC, Gargron commented
It seems that Rails may be setting the HSTS header: https://api.rubyonrails.org/v5.2.6/classes/ActionDispatch/SSL.html

Therefore, the fix may be to remove all HSTS headers from the nginx configuration.

2021-12-02 20:38 UTC, ClearlyClaire commented
I'm surprised it would solve the issue. To me, it seems like the proper fix would be, on the contrary, to remove the `add_header` from the `server` and `location @proxy` blocks and keep the others.

2021-12-02 21:40 UTC, mishfit commented
> I'm surprised it would solve the issue. To me, it seems like the proper fix would be, on the contrary, to remove the `add_header` from the `server` and `location @proxy` blocks and keep the others.

That's what I did...this fix is only for future installers. I still had to remove the declarations from `/etc/nginx/sites-available/<xxxx>`

2021-12-02 22:19 UTC, ClearlyClaire commented
> > I'm surprised it would solve the issue. To me, it seems like the proper fix would be, on the contrary, to remove the `add_header` from the `server` and `location @proxy` blocks and keep the others.
> 
> That's what I did...this fix is only for future installers. I still had to remove the declarations from `/etc/nginx/sites-available/<xxxx>`

I'm confused. Your PR removes the headers from the static files, while, in my understanding, it should remove the headers for the part that is proxied from Rails (`location @proxy`), since the duplication is because of both Rails and nginx setting a header. The static files need `nginx` to set the header, since it does not go through Rails.

2021-12-13 10:28 UTC, ClearlyClaire requested changes

2021-12-13 10:28 UTC, ClearlyClaire commented on dist/nginx.conf
> -    add_header Strict-Transport-Security "max-age=31536000" always;
I believe these should be kept (or rather, changed to `max-age=63072000; includeSubDomains` for consistency, along with the one on line 55), and the one that needs to be removed is the one in the `location @proxy` block (on line 93).

2022-01-12 12:20 UTC, ClearlyClaire commented
@mishfit do you agree with the proposed changes? Can you apply them? Or would you prefer if I took it from there?

2022-02-23 02:28 UTC, mishfit commented
@ClearlyClaire sorry for the delay. Things got busy over here. Is the latest closer to what you envisioned?

2022-02-23 08:40 UTC, ClearlyClaire requested changes

2022-02-23 08:40 UTC, ClearlyClaire commented on dist/nginx.conf
> +  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
I think this one needs to be removed.

2022-02-23 08:40 UTC, ClearlyClaire commented on dist/nginx.conf
> -    add_header Strict-Transport-Security "max-age=31536000" always;
And this one kept.

2022-07-31 13:50 UTC, closed without merging