Fix Redis connection error in mastodon-streaming
mastodon/mastodon pull request #17183
Opened 2021-12-23 20:16 UTC by lfuelling

This PR fixes a missing `connect()` in the `mastodon-streaming` redis client.

The error was a bit hard to figure out, because the only thing logged by `mastodon-streaming` is `Error! The client is closed!`.

2021-12-23 20:19 UTC, lfuelling commented on streaming/index.js
> +  client.on('error', (err) => console.log('Redis Client Error!', err));
You're right, it should be an error.

2021-12-24 14:30 UTC, ykzts commented on streaming/index.js
> +      user: process.env.DB_USER || pg.defaults.user,
Keep space padding.

2021-12-24 14:33 UTC, ykzts requested changes

2021-12-24 14:33 UTC, ykzts commented on streaming/index.js
> +   * @param arr {array}
```suggestion
   * @param {array} arr
```

2021-12-24 14:34 UTC, ykzts approved these changes

2021-12-25 21:55 UTC, merged