Redesign /about when already logged in
mastodon/mastodon pull request #17348
Opened 2022-01-24 17:40 UTC by ClearlyClaire

## Before

Upon visiting `/about`, one would not know they are already logged in, and will instead be presented with the registration and log-in form. If using any of them, they will just silently go to `/web`, without the registration or log-in action performed.

![Screenshot 2022-01-24 at 18-37-54 Mastodon Glitch Edition](https://user-images.githubusercontent.com/384364/150835179-1d971161-7f90-4dfe-8081-3b296afde103.png)

## After

Visiting `/about` when already logged in disables the registration form and replaces the log-in one by a button to go to the web interface.

![Screenshot 2022-01-24 at 18-33-52 Mastodon Glitch Edition](https://user-images.githubusercontent.com/384364/150835193-799c700b-7cc4-458a-b037-5c6b4f0c8d8f.png)

2022-01-24 17:42 UTC, ClearlyClaire commented
I think this partly addresses #11578

2022-03-01 08:33 UTC, ClearlyClaire commented
@Gargron ping

2022-03-02 21:00 UTC, Gargron requested changes

2022-03-02 21:00 UTC, Gargron commented on config/locales/en.yml
> +    continue_to_web: Continue to the Web interface
```suggestion
    continue_to_web: Continue to web app
```

2022-03-03 15:14 UTC, Gargron approved these changes

2022-03-03 15:14 UTC, merged