Add edit history to web UI
mastodon/mastodon pull request #17390
Opened 2022-01-29 01:19 UTC by Gargron

⚠️ **Work in progress**

___

Funded through the BMBF (BMBF Förderkennzeichen: 01IS21S29)

2022-01-30 11:00 UTC, ClearlyClaire requested changes

2022-01-31 00:33 UTC, Gargron commented on app/javascript/mastodon/components/dropdown_menu.js
> +    const items = Array.from(this.node.querySelectorAll('a, button'));
For menu items that should open in new tab, using `<a>` is a lot more natural than using `<button>`.

2022-01-31 00:33 UTC, Gargron commented on app/javascript/mastodon/components/dropdown_menu.js
> +    loading: PropTypes.bool,
Now it is.

2022-01-31 00:34 UTC, Gargron commented on app/javascript/mastodon/components/edited_timestamp/containers/dropdown_menu_container.js
> +  items: state.getIn(['history', 'items']),
When `HISTORY_FETCH_REQUEST` starts, the previous items are reset. This happens in a dispatch before the dropdown opens.

2022-01-31 00:39 UTC, Gargron commented
PR now includes a much better-looking circular loading indicator.

2022-02-06 09:59 UTC, ClearlyClaire commented on app/javascript/mastodon/components/edited_timestamp/containers/dropdown_menu_container.js
> +  items: state.getIn(['history', 'items']),
Yes, but the API reply might come after the user opened another drop-down, and there's no guarantee two API requests will return in the order they were issued.

2022-02-07 16:56 UTC, Gargron commented
History items are now stored in a map segmented by status ID to avoid dropdowns showing wrong items due to race conditions.

2022-02-08 09:13 UTC, ClearlyClaire requested changes
Apart from the missing `loading` prop, there are some issues that probably should be addressed in later PRs:
- redux history state might grow large over time, it probably needs pruning in some way
- overall, I dislike how complicated `DropdownMenu` is, but I have no concrete step to offer you to improve that
- the overall style could need some improvement, especially the position of the dropdown menu

https://user-images.githubusercontent.com/384364/152955001-41001ded-321e-49aa-a6c5-d7740d7155e5.mp4

EDITED: just noticed it also doesn't mention whether the attachments have changed

2022-02-08 09:13 UTC, ClearlyClaire commented on app/javascript/mastodon/components/edited_timestamp/containers/dropdown_menu_container.js
> +  items: state.getIn(['history', statusId, 'items']),
Missing prop: `loading: state.getIn(['history', statusId, 'loading']),`

2022-02-08 21:50 UTC, ClearlyClaire approved these changes

2022-02-09 00:17 UTC, merged