Tooltip for boosting depends on toot visibility (#1394)
mastodon/mastodon pull request #1754
Opened 2017-04-14 10:16 UTC by expenses

Fix for #1394. Looks like:
![example](https://cloud.githubusercontent.com/assets/13566135/25040827/ddfcd2c0-215f-11e7-97d1-c0271d465f64.png)
Note that this adds a new localization string.

2017-04-14 19:37 UTC, thurloat commented
There's an inconsistency between your default translation, and the English translation.

`app/assets/javascripts/components/locales/en.jsx` calls it a Toot, though there are other translations in the file that refer to toots as Posts. i.e. `"compose_form.privacy_disclaimer"`.

`app/assets/javascripts/components/components/status_action_bar.jsx` calls it a Post.

2017-04-15 03:02 UTC, expenses commented
@thurloat I think they're meant to be different.

2017-04-23 01:12 UTC, yiskah approved these changes
This looks to add a useful a11y feature

2017-04-23 03:16 UTC, Gargron commented
@expenses @thurloat For the record, the official UI does not refer to any items as "toots". They are "statuses" in most places, and "posts" in places where it needs to be shorter. Only the "publish" button is called "toot". This is deliberate, the UI can't get *too* silly.

2017-04-23 03:17 UTC, Gargron requested changes

2017-04-23 03:17 UTC, Gargron commented on app/assets/javascripts/components/locales/en.jsx
> +  "status.cannot_reblog": "This toot cannot be boosted",
Change this to status and this is good to go. Sorry it took so long

2017-04-23 03:20 UTC, expenses commented on app/assets/javascripts/components/locales/en.jsx
> +  "status.cannot_reblog": "This toot cannot be boosted",
.. And done!

2017-04-23 03:36 UTC, Gargron approved these changes

2017-04-23 03:36 UTC, merged