Change e-mail domain blocks to block IPs dynamically
mastodon/mastodon pull request #17635
Opened 2022-02-24 02:45 UTC by Gargron

When adding a new e-mail domain block, do not block any resolved DNS records silently; instead, display them as options in the form, turning the form into a two-step wizard.

2022-02-24 12:05 UTC, ykzts requested changes

2022-02-24 12:05 UTC, ykzts commented on app/workers/scheduler/email_domain_block_refresh_scheduler.rb
> +     str =~ Regexp.union([Resolv::IPv4::Regex, Resolv::IPv6::Regex])
```suggestion
    str =~ Regexp.union([Resolv::IPv4::Regex, Resolv::IPv6::Regex])
```

2022-02-24 12:05 UTC, ykzts commented on app/workers/scheduler/email_domain_block_refresh_scheduler.rb
> +  def is_ip?(str)
```suggestion
          if ip?(email_domain_block.domain)
            [email_domain_block.domain]
          else
            dns.getresources(email_domain_block.domain, Resolv::DNS::Resource::IN::A).to_a + dns.getresources(email_domain_block.domain, Resolv::DNS::Resource::IN::AAAA).to_a.map { |resource| resource.address.to_s }
          end
        end

        email_domain_block.update(ips: ips, last_refresh_at: Time.now.utc)
      end
    end
  end

  def ip?(str)
```

<img width="608" alt="image" src="https://user-images.githubusercontent.com/12539/155520627-f99113f1-7071-4e21-b9b9-3ddaf931d69d.png">

2022-02-24 15:01 UTC, ykzts approved these changes

2022-02-24 16:28 UTC, merged

2022-02-26 10:04 UTC, ClearlyClaire commented on app/models/email_domain_block.rb
> +    @history ||= Trends::History.new('email_domain_blocks', id)
Hm maybe that needs some refactoring, because email domain blocks depending on trends code feels very wrong.

2022-02-26 14:57 UTC, ClearlyClaire commented on app/models/email_domain_block.rb
> +  attr_accessor :other_domains
Feels weird to have that in the model since it's purely a form/controller thing.