Remove setting that disables account deletes
mastodon/mastodon pull request #17683
Opened 2022-03-02 05:51 UTC by Gargron

2022-03-07 15:04 UTC, ClearlyClaire approved these changes

2022-03-07 15:08 UTC, ClearlyClaire requested changes
Wait, I have reviewed this a bit fast. I believe the current code immediately deletes the account with all of its data, while we should probably keep it for a short time to let the person change their mind or let moderators some time to handle the situation.

(I believe this is why this is still marked as a Draft, but I wanted to explain my reasoning behind the “Request changes”, sorry for the noise)

2022-03-08 04:30 UTC, Gargron commented
I don't disagree that introducing a grace period would be a good change, but it is not why this is a draft. I simply forgot to toggle it. I think this should be mergeable without adding any new features.

2022-10-06 08:10 UTC, ClearlyClaire approved these changes
I still think there should be a short grace period, but this is somewhat orthogonal to this PR.

2022-10-06 08:16 UTC, merged