[WAIT-FRONT] Add "status_max_length" instance parameter
mastodon/mastodon pull request #1770
Opened 2017-04-14 13:58 UTC by pixocode

Add the ability to edit the maximum number of characters per status

2017-04-14 15:44 UTC, pixocode commented
#1781

2017-04-16 16:15 UTC, ineffyble requested changes

2017-04-16 16:15 UTC, ineffyble commented on app/views/admin/settings/index.html.haml
> +        %strong Status max length
Can you change this to be internationalised?

2017-04-18 11:02 UTC, pixocode commented on app/views/admin/settings/index.html.haml
> +        %strong Status max length
Fixed :)

2017-04-20 12:31 UTC, pixocode commented
If someone is skilled reactjs, help would be greatly appreciated ^^"

2017-04-23 16:45 UTC, ineffyble approved these changes

2017-04-23 16:52 UTC, pixocode commented
It lacks a "front" part (which I did not succeed to do) so that the parameter is repercussion on the toot form :/

2017-04-26 18:09 UTC, rixx commented
So the only part missing is to replace the `500` [here](https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/features/compose/components/compose_form.jsx#L176)?

2017-04-26 19:17 UTC, pixocode commented
@rixx yes, but I don't know how to retrieve the parameter from the back (with reactjs :/)

2017-05-17 15:58 UTC, BrunoSpy commented
you can look at 
https://gist.github.com/BrunoSpy/6581f106a15f5d830f3e2289002da2f5
We need a way to get the value of Setting.status_max_length.to_i in the two jsx files mentioned in the previous gist. But I don't know how.

2017-05-17 16:04 UTC, BrunoSpy commented
And every locale file must be changed too ("500" is hardcoded there too).

2017-08-05 16:15 UTC, nightpool requested changes
needs the above concerns addressed, at least. (front-end changes, locale changes)

but I'm also not sure this is a good feature for the project to have, from a meta perspective. it's pretty easy for admins to change this themselves, to be sure, but I don't know that making this particular setting *easier* to change is a good idea in the long run.

2017-08-05 17:04 UTC, rixx commented
Could you expand upon this, @nightpool? Particularly on the "why"?

2017-09-30 20:50 UTC, Gargron commented
Closing due to inactivity.

2017-09-30 20:50 UTC, closed without merging