Fix error resposes for `from` search prefix (addresses mastodon/mastodon#17941)
mastodon/mastodon pull request #17963
Opened 2022-04-05 03:16 UTC by single-right-quote

Using unsupported prefixes now reports a 422; searching for posts from an account the instance is not aware of reports a 404. I think the UI for this on the front end is only barely more helpful at actually communicating any problems to the user, but at least the semantics are reasonable.

In addition, this commit addresses two minor points. More importantly, `from:username@domain` succeeds when `domain` is the local domain. Less importantly, `from:@username(@domain)?` is now valid syntax.

For the record, a nealy identical version of this commit in https://github.com/kibicat/mastodon/commit/945c9b1342b7a000da05074e4572abe6ce7feb9c is running on https://glitch.cat.family, with no reported issues.

2022-04-06 19:06 UTC, ClearlyClaire requested changes
Thanks for the contribution!

The change is welcome even though I would have done without additional helpers and duplicate exceptions (`Mastodon::NotFound` could just be `ActiveRecord::RecordNotFound`).

2022-04-07 05:55 UTC, single-right-quote commented on app/lib/search_query_transformer.rb
> +        raise Mastodon::NotFound if account.nil?
I&#x2019;m not familiar with project etiquette here. I have recreated your suggestion locally (and removed code I added that it renders unused), but should I instead commit your suggestion from GitHub, then removed the needless extra code. and then squash?

2022-04-07 06:01 UTC, ClearlyClaire commented
Honestly, do as is more convenient for you (maybe avoiding force-pushes though). The PRs get squashed once they get accepted, so it is not necessary for you to do so.

2022-04-07 07:43 UTC, ClearlyClaire commented on app/lib/search_query_transformer.rb
> +        raise Mastodon::NotFound if account.nil?
Honestly, do as is more convenient for you (maybe avoiding force-pushes though). The PRs get squashed once they get accepted, so it is not necessary for you to do so.

2022-04-08 01:12 UTC, single-right-quote commented on app/lib/search_query_transformer.rb
> +        raise Mastodon::NotFound if account.nil?
Thank you; pushed.

2022-04-08 10:50 UTC, ClearlyClaire approved these changes
I'd rather have an “invalid” prefix either silently fall back to textual comparison, or have a more informative error, but it's already a noticeable improvement over the current situation.

2022-04-08 18:40 UTC, single-right-quote commented
I agree. An example where this can be a problem is searching for links, since `https://` is interpreted as a prefix, so either special casing that to fall back (ew) or just falling back in general seems very much worth exploring to me.

2022-04-08 19:21 UTC, merged