Add translatable string for #17431
mastodon/mastodon pull request #18227
Opened 2022-05-01 11:49 UTC by ykzts

2022-05-01 12:00 UTC, ClearlyClaire approved these changes

2022-05-01 23:29 UTC, Gargron requested changes

2022-05-01 23:29 UTC, Gargron commented on config/locales/en.yml
> +      only_allowed: Only Allowed
```suggestion
      only_allowed: Only allowed
```

2022-05-02 01:39 UTC, Gargron approved these changes

2022-05-02 01:39 UTC, merged