[Feature] Delete account API
mastodon/mastodon pull request #18483
Opened 2022-05-23 04:33 UTC by luiz-m-affonso

https://github.com/mastodon/mastodon/issues/18185

2022-05-23 19:15 UTC, Gargron commented
- It is not suffiicient to `@account.destroy!` to properly delete an account. You have to call `DeleteAccountService`
- This method is unsecured. Any app that has an access token for the account could delete the entire account, irreversibly

2022-05-30 14:46 UTC, ClearlyClaire requested changes

2022-05-30 14:46 UTC, ClearlyClaire commented on Gemfile.lock
> +   2.2.32
Those changes shouldn't get included!

2022-05-30 14:46 UTC, ClearlyClaire commented on app/controllers/api/v1/accounts_controller.rb
> +  end
A `doorkeeper_authorize!` `before_action` is required to prevent any app from destroying the account.

2022-06-13 06:56 UTC, ClearlyClaire approved these changes
I wonder if we should have a specific scope for this rather than `write:accounts`, but if we do chose `write:accounts`, then the PR looks good to me.

2022-12-15 15:48 UTC, Gargron commented
I think it's a really, really dangerous idea to let app developers delete users' accounts.

Imagine if Tusky was compromised and a new release deleted everyone's accounts.

At the very least it cannot use the same permission used for simply updating profile pictures. The authorization screen must say "This app can irreversibly delete your account". Even so I think it's better not to have this in the API.

2023-02-15 00:04 UTC, closed without merging