Fix CDN_HOST not affected on full_asset_url
mastodon/mastodon pull request #18662
Opened 2022-06-14 10:06 UTC by tribela

`CDN_HOST` env var is for packs assets. But it was not respected on `full_asset_url` function

2022-06-14 16:18 UTC, Gargron approved these changes

2022-06-15 02:34 UTC, Gargron requested changes
> undefined method `action_controler'

2022-06-15 03:31 UTC, tribela commented
> > undefined method `action_controler'

it is available on production but not on test env.
Add check logic?

2022-06-23 21:09 UTC, Gargron approved these changes

2022-06-23 21:09 UTC, merged