Add ability to select all accounts matching search for batch actions
mastodon/mastodon pull request #19053
Opened 2022-08-25 18:04 UTC by Gargron

2022-08-25 18:55 UTC, ykzts requested changes

2022-08-25 18:55 UTC, ykzts commented on app/javascript/packs/admin.js
> +}
```suggestion
};
```

> Missing semicolon

2022-08-25 21:28 UTC, ykzts approved these changes

2022-08-25 21:33 UTC, merged

2022-08-26 10:59 UTC, ClearlyClaire commented
I'm honestly confused as what this means or is supposed to do.