Add error boundary around routes in web UI
mastodon/mastodon pull request #19412
Opened 2022-10-22 14:39 UTC by Gargron

2022-10-22 18:58 UTC, ykzts requested changes

2022-10-22 18:58 UTC, ykzts commented on app/javascript/mastodon/features/ui/util/react_router_helpers.js
> +  componentDidCatch (error, componentInfo) {
```suggestion
  componentDidCatch (error) {
```

2022-10-22 18:58 UTC, ykzts commented on app/javascript/mastodon/features/ui/util/react_router_helpers.js
> +  static getDerivedStateFromError (error) {
```suggestion
  static getDerivedStateFromError () {
```

2022-10-22 20:41 UTC, ykzts approved these changes

2022-10-22 20:42 UTC, ykzts requested changes

2022-10-22 20:42 UTC, ykzts commented on app/javascript/mastodon/features/ui/components/bundle_column_error.js
> +    const { errorType, multiColumn, stacktrace, intl } = this.props;
```suggestion
    const { errorType, multiColumn, stacktrace } = this.props;
```

2022-10-22 21:15 UTC, ykzts approved these changes

2022-10-22 21:18 UTC, merged

2022-10-23 15:07 UTC, ClearlyClaire commented
This could use a link to the issue tracker…

2022-10-23 15:19 UTC, ClearlyClaire commented
Additionally, when the column is pinned in multi-column view, it could offer to unpin the column.