Change confirm prompt for relationships management
mastodon/mastodon pull request #19411
Opened 2022-10-22 12:14 UTC by tribela

On relationships manager, Just asking same "Are you sure?" for destructive action is not good.
Especially, for mobile interface, User cannot know if they touched different action

It maybe better if "Are you sure to ~~(action) for X users?", But it is fine with confirming with action like "Are you sure to follow selected followers?"

2022-10-22 19:01 UTC, ykzts approved these changes

2022-11-07 19:20 UTC, PabloRubio21 approved these changes

2022-11-14 10:32 UTC, TobyWilkes requested changes
PR is currently marked as approved, but the en yml has syntax issues

2022-11-14 10:32 UTC, TobyWilkes commented on config/locales/en.yml
> +    confirm_follow_selected_followers: Are you sure to follow selected followers?
```suggestion
    confirm_follow_selected_followers: Are you sure you want to follow selected followers?
```

2022-11-14 10:32 UTC, TobyWilkes commented on config/locales/en.yml
> +    confirm_remove_selected_followers: Are you sure to remove selected followers?
```suggestion
    confirm_remove_selected_followers: Are you sure you want to remove selected followers?
```

2022-11-14 10:32 UTC, TobyWilkes commented on config/locales/en.yml
> +    confirm_remove_selected_follows: Are you sure to remove selected follows?
```suggestion
    confirm_remove_selected_follows: Are you sure you want to remove selected follows?
```

2022-12-22 08:43 UTC, ClearlyClaire approved these changes

2023-01-13 12:26 UTC, ClearlyClaire commented
@tribela can you rebase it on latest main?

2023-01-14 13:00 UTC, merged