Fix targetname to match web deployment
mastodon/mastodon pull request #20690
Opened 2022-11-14 20:43 UTC by grrywlsn

2022-11-14 23:19 UTC, bocan commented
Not to be critical, but it seems the whole chart seems to be an afterthought - when it's arguably the more reliable way to build a properly scaling cluster.

Glad you noticed the HPA doesn't work.  It really needs one for -streaming and -sidekick too.

2022-11-24 08:58 UTC, emilweth requested changes
maybe renaming this hpa to `{{ include "mastodon.fullname" . }}-web` as well ?

2022-11-27 21:13 UTC, Gargron commented
Moving the Helm chart out to mastodon/chart

2022-12-09 06:10 UTC, ineffyble commented
Closing, there's been some refactoring in https://github.com/mastodon/chart which should make this PR unnecessary.

2022-12-09 06:10 UTC, closed without merging