fix media uploads with ffmpeg 5
mastodon/mastodon pull request #21191
Opened 2022-11-20 05:00 UTC by dead10ck

Fixes #21154. This was tested by running the ffmpeg command manually in a docker container on Ubuntu 20.04 and Debian 11, and this Ruby change was tested on my Fedora 36 server's mastodon instance.

2022-11-20 17:07 UTC, ClearlyClaire approved these changes

2022-11-24 02:16 UTC, ineffyble requested changes
Can you fix the linter complaint?

2022-11-24 08:03 UTC, ClearlyClaire commented
> Can you fix the linter complaint?

Nah, I wouldn't ask them to do it, it's unrelated to their change (annoyingly, the linter complains about already-existing issues anywhere in changed files, not just in the parts that were modified).

2022-11-25 02:48 UTC, dead10ck commented
No big deal, it's a simple fix

2022-11-25 05:33 UTC, dead10ck commented on app/models/media_attachment.rb
> +          'vf': 'scale=\'min(400\, iw):min(400\, ih)\':force_original_aspect_ratio=decrease',
Ah, thank you, it's been a long time since I've Ruby'd

2022-11-25 05:39 UTC, nightpool commented
Is this change backwards-compatible with older versions of FFMPEG? If so, which versions? Is there a link to the FFMPEG change in question that broke this, for posterity/reference?

2022-11-25 06:09 UTC, dead10ck commented
> Is this change backwards-compatible with older versions of FFMPEG? If so, which versions? Is there a link to the FFMPEG change in question that broke this, for posterity/reference?

I looked, but I was not able to find any specific mention of this breakage. The change logs are extremely terse:

https://github.com/FFmpeg/FFmpeg/blob/1ff9c07fa696443d2d243e45d5794c8b19946a1b/Changelog#L57

But as I mentioned in the issue, I tested that adding `b:v` works in Ubuntu 20.04 (ffmpeg 4.2.7), and Debian 11 (4.3.5). This test was just manually invoking the CLI though, so it would be prudent for someone to test this on their mastodon instance on one of those two distros for sanity before putting the change into a stable release.

2022-11-25 13:04 UTC, ClearlyClaire commented
> Is this change backwards-compatible with older versions of FFMPEG? If so, which versions? Is there a link to the FFMPEG change in question that broke this, for posterity/reference?

Making a few online searches, I could not find when this argument was introduced exactly, but I could find references to the `b:v` argument in pages dating back from around 10 years ago, so I think we should be safe with regards to backward compatibility.

> No big deal, it's a simple fix

It is! But the comment was more about not introducing unrelated changes and e.g. muddying the output of `git blame`!

2022-11-25 14:58 UTC, dead10ck commented
> It is! But the comment was more about not introducing unrelated changes and e.g. muddying the output of `git blame`!

Oh I see, ok, I've reverted the fix then

2022-11-25 15:20 UTC, merged