Validate nodeinfo schema
mastodon/mastodon pull request #21395
Opened 2022-11-22 14:42 UTC by MFTabriz

2022-11-24 02:08 UTC, ineffyble requested changes
Can you address the build failures? Looks like you need to regenerate the Gemfile.lock

2022-11-24 15:42 UTC, MFTabriz commented
> Can you address the build failures? Looks like you need to regenerate the Gemfile.lock

I did a `bundle lock --update`. Now the tests pass for [ruby2.7](https://app.circleci.com/pipelines/github/mastodon/mastodon/67830/workflows/f0f3296b-2834-4885-b8be-5fd4d1b4e3dd/jobs/253460) but fail for [ruby3.0](https://app.circleci.com/pipelines/github/mastodon/mastodon/67830/workflows/f0f3296b-2834-4885-b8be-5fd4d1b4e3dd/jobs/253462). Did I break something? Can you please check this?

2022-12-01 08:26 UTC, MFTabriz commented
Hi @ClearlyClaire ! Can you please check this out or ask someone to review it?

2022-12-01 10:45 UTC, MFTabriz commented on spec/support/matchers/json/match_json_schema.rb
> +    schema_path = "#{schema_directory}/#{schema}.json"
Done!

2022-12-10 13:36 UTC, ClearlyClaire requested changes
It looks like there's a bunch of unrelated dependency updates. Can you revert those changes?

2022-12-10 13:36 UTC, ClearlyClaire commented on Gemfile.lock
> +    browser (5.3.1)
Unrelated dependency update.

2022-12-10 13:36 UTC, ClearlyClaire commented on Gemfile.lock
> +    chewy (7.2.7)
Unrelated dependency update.

2022-12-10 13:36 UTC, ClearlyClaire commented on Gemfile.lock
> +    public_suffix (5.0.1)
Unrelated dependency update.

2022-12-10 13:36 UTC, ClearlyClaire commented on Gemfile.lock
> +    rails-settings-cached (0.7.2)
Unrelated dependency update.

2022-12-10 13:36 UTC, ClearlyClaire commented on Gemfile.lock
> +    redis (4.8.0)
Unrelated dependency update.

2022-12-10 13:36 UTC, ClearlyClaire commented on Gemfile.lock
> +      json (~> 2.3)
Unrelated dependency update.

2022-12-10 13:36 UTC, ClearlyClaire commented on Gemfile.lock
> +   2.2.33
This shouldn't be saved to the `Gemfile.lock`!

2022-12-10 17:18 UTC, MFTabriz commented
> It looks like there's a bunch of unrelated dependency updates (I made in-line comments for some of them but not all). Can you revert those changes?

Thanks for checking it. I think I fixed all of them.

2022-12-13 09:33 UTC, ClearlyClaire approved these changes

2022-12-13 12:14 UTC, MFTabriz commented
@ineffyble you asked for changez when this PR was a draft 3 weeks ago and you did not review it afterwards. I have to ask you again: Can you please check this out?

2022-12-13 12:38 UTC, ineffyble approved these changes

2022-12-13 12:39 UTC, ineffyble commented
@MFTabriz Claire is the one you need sign-off from, I've just been trying to help with PR hygiene :)

2022-12-15 14:43 UTC, merged