Add role badges to WebUI
mastodon/mastodon pull request #21393
Opened 2022-11-22 14:30 UTC by ClearlyClaire

Add moderation badges in the WebUI, as they were only available in the public pages.

![image](https://user-images.githubusercontent.com/384364/203337449-c7c02c97-1704-4c53-8e0b-7d9b04d07665.png)

I am not completely sure the display name is the best place for this, though, as people may use custom emoji to make it look similar to a role.

Also of note, I re-used `REST::RoleSerializer`, but it exposes `permissions`, that is not useful for this purpose and may actually be undesirable to expose to end-users.

2022-11-22 15:12 UTC, ClearlyClaire commented
Maybe a better design:
![image](https://user-images.githubusercontent.com/384364/203350102-6a99df01-73ec-4db0-832a-9c40505e9aca.png)

2022-11-22 16:29 UTC, ClearlyClaire commented
There's another proposal that could work:
![image](https://user-images.githubusercontent.com/384364/203366664-90896d3c-852f-4d33-b67e-bf19ed716caf.png)

My main concern with it though is that it'd eat even more screen space, which is already an issue with the recent redesign of profile fields.

2022-11-23 07:35 UTC, ykzts approved these changes

2022-11-23 21:58 UTC, wojtekxtx commented
Who cares about profiles when engine itself has critical errors unpatched?

2022-11-24 08:05 UTC, ClearlyClaire commented
> Any idea why codeclimate is stuck?

No idea, looks like it's just a fluke, and thankfully not on the test or linter results themselves.

2022-11-24 18:57 UTC, trankten commented
Hello. I've just wanted to add that it worked like a charm. 
Tested on my instance. Thanks for fixing.

Examples:
https://tkz.one/@tahurcete
https://tkz.one/@trankten
https://tkz.one/@arvidax
https://tkz.one/@solisto89

Not visible through Mastodon Android / iOS yet but works in Mobile Web perfectly too.

Thank you.

2022-11-25 02:07 UTC, trwnh commented
On that last one the purple is a bit hard to read, so I would suggest for this PR to use the default text color and have the role color only be applied to the outline and low-opacity background.

2022-11-25 13:31 UTC, ClearlyClaire commented
> On that last one the purple is a bit hard to read, so I would suggest for this PR to use the default text color and have the role color only be applied to the outline and low-opacity background.
> Before 	After
> ![image](https://user-images.githubusercontent.com/10606431/203885958-2abff3b5-c413-4860-98b7-02ca0d1af260.png) 	![image](https://user-images.githubusercontent.com/10606431/203886044-dddde31f-7b1d-4e84-91b3-0898e2cb4ad6.png)

That issue was already present with the old way this information was displayed. Nonetheless, changed the CSS to not use the provided color for text. Maybe there are better options though.

2022-11-25 14:23 UTC, trankten commented
> > On that last one the purple is a bit hard to read, so I would suggest for this PR to use the default text color and have the role color only be applied to the outline and low-opacity background.
> > Before 	After
> > ![image](https://user-images.githubusercontent.com/10606431/203885958-2abff3b5-c413-4860-98b7-02ca0d1af260.png) 	![image](https://user-images.githubusercontent.com/10606431/203886044-dddde31f-7b1d-4e84-91b3-0898e2cb4ad6.png)
> 
> That issue was already present with the old way this information was displayed. Nonetheless, changed the CSS to not use the provided color for text. Maybe there are better options though.

Actually it's really a matter of whoever creates the roles to choose correct colors as they have to fit for both dark and light themes. 

However, imho keeping the same color for the text and the border makes the badge look more unique and epic for the user who has it. Please reconsider keeping the way it was originally. It would be much appreciated.

2022-11-25 14:25 UTC, ClearlyClaire commented
> Actually it's really a matter of whoever creates the roles to choose correct colors as they have to fit for both dark and light themes.

That may not be entirely true, as the admin setting the roles would have to account for any theme (e.g. something that looks fine with the dark theme may not work fine with the light theme, or the other way around)

2022-11-25 15:03 UTC, trwnh commented
> Maybe there are better options though.

Discord has the role color as a circle instead of a background/border.

![image](https://user-images.githubusercontent.com/10606431/204011517-7a6d6b4c-1575-4af5-b3b8-60e9f2e31b06.png)

> Actually it's really a matter of whoever creates the roles to choose correct colors as they have to fit for both dark and light themes.

There's not just dark and light themes. There's also custom themes that could be any color. Text and background colors should only have to worry about contrast with themselves, and the role color shouldn't have to be considered because that would mean considering every single color.

2022-11-25 17:45 UTC, ClearlyClaire commented
> There's not just dark and light themes. There's also custom themes that could be any color.

That being said, available custom themes are decided by the admins as well, not end-users (unless we enter user CSS territory in which case the users can also override the badges)

2022-11-27 01:50 UTC, Sailanthresh commented
I tested it out on glitch and the badges are not visible for some reason, im sure im doing something wrong.

2022-11-27 08:53 UTC, ClearlyClaire commented
> I tested it out on glitch and the badges are not visible for some reason, im sure im doing something wrong.

glitch-soc ships with two front-ends, the “vanilla” flavour and the “glitch” flavour; if you applied the changes as-is, they'd only affect the “vanilla” flavour. You need to port the changes to files under `app/javascript/mastodon` to `app/javascript/flavours/glitch` too.

2022-11-27 09:03 UTC, Sailanthresh commented
> > I tested it out on glitch and the badges are not visible for some reason, im sure im doing something wrong.
> 
> glitch-soc ships with two front-ends, the “vanilla” flavour and the “glitch” flavour; if you applied the changes as-is, they'd only affect the “vanilla” flavour. You need to port the changes to files under `app/javascript/mastodon` to `app/javascript/flavours/glitch` too.

Thank you so much ^_^

2022-12-04 22:03 UTC, supernovae commented
This is fantastic - and much needed for some of my users i'd like to validate or offer supporter roles too.  What would be the effort to add PRs to the mastodon mobile apps to show these badges?

2022-12-11 10:52 UTC, ronilaukkarinen commented
Working great here!

![image](https://user-images.githubusercontent.com/1534150/206899453-f8d1365d-5f48-4f8e-b631-a77a1726ad1c.png)

2022-12-15 16:30 UTC, Gargron requested changes
I prefer the second design.

2022-12-16 14:01 UTC, ClearlyClaire commented
> I prefer the second design.

Which one would this be? This one? https://github.com/mastodon/mastodon/pull/21393#issuecomment-1323938329

My main concern about it is that it would make profiles take even more vertical space, which is already a complaint we get with 4.0 profiles.

2022-12-16 14:04 UTC, ronilaukkarinen commented
Without taking a stand in the layout alignment-wise, as a CSS/UI guy I'd say the slight border-radius supports the Mastodon brand best, I'd keep it, that's my 2 cents on the matter.

2022-12-19 15:44 UTC, supernovae commented
Any chance we could get something like this in for a 4.0.3 release?  I have some high profile accounts that I've verified over phone and i'd love to have a "Verified" role that shows up on profile page (and have the mobile apps expose this eventually)

2022-12-19 15:51 UTC, trankten commented
> Any chance we could get something like this in for a 4.0.3 release? I have some high profile accounts that I've verified over phone and i'd love to have a "Verified" role that shows up on profile page (and have the mobile apps expose this eventually)

You can push on your own like some of us did but keep in mind it's a beta stage and not final. In any case, please don't rush the developers :) It will be available when it's finally done. I'd suggest to keep this topic clean from non developer talk as any update usually notifies everyone in the thread.

Have a nice day.

2023-01-09 20:23 UTC, jippi commented
Any work needed on this to get traction back on? Been some fantastic discussions above, but can't find exactly the cause for it getting stuck (other than of course Christmas and New Year 👍 )

2023-01-15 19:11 UTC, craftxbox commented
Deployed this locally yesterday, it looks and functions great! Might I suggest an addition to display_name.js to show badges everywhere aswell? 
![7185b9933f32856e](https://user-images.githubusercontent.com/7443752/212561877-87a36616-9fb5-44d1-bcc7-7bc4214e86d6.png)
Three different placement options I could think of. I have the middle option deployed locally @ https://transfur.social for a live example.

2023-02-12 08:41 UTC, jaanus commented
Sad to see this still not available in 4.1 😢

2023-03-26 20:09 UTC, VyrCossont commented
Any chance we could get custom emoji included in roles before the API and UI are stabilized? Servers using roles for supporter badges, manual verification, etc. will want those. Servers using roles for fun will _definitely_ want those.

2023-07-27 14:12 UTC, closed without merging