Modify: score_at_threshold where query with date ranges style
mastodon/mastodon pull request #21402
Opened 2022-11-22 16:25 UTC by roharon

What about use data range style instead of defining comparative conditions on `where` query?

2022-11-22 17:06 UTC, ClearlyClaire commented
We're still targeting Ruby 2.6 for now, which doesn't have support for this notation!

2022-11-23 19:25 UTC, casaper requested changes

2022-11-23 19:25 UTC, casaper commented on app/models/trends/links.rb
> +      score_at_threshold  = PreviewCardTrend.where(language: language, allowed: true).order(rank: :desc).where(rank: ..options[:review_threshold]).first&.score || 0
Suggest code style fix, when you touch it for such a cosmetic change:

```rb
score_at_threshold = PreviewCardTrend.order(rank: :desc)
                                     .where(language: language, allowed: true, rank: ..options[:review_threshold])
                                     .first&.score || 0
```

2022-11-24 17:28 UTC, roharon commented
> We're still targeting Ruby 2.6 for now, which doesn't have support for this notation!

Oops I missed it!
Thanks for comment.

2022-11-24 17:34 UTC, ClearlyClaire commented
> > We're still targeting Ruby 2.6 for now, which doesn't have support for this notation!
> 
> Oops I missed it! Thanks for comment.

It appears we recently inadvertently dropped support for Ruby 2.6 anyway, so we're going to formally drop compatibility soon and update rubocop's config accordingly. So this PR is blocked by #21477 but can be merged right after.

2022-11-24 17:48 UTC, roharon commented
Okay 😅  I m gonna check Lint Code Base status again after ruby parser updated (maybe seems like after https://github.com/mastodon/mastodon/pull/21477 merged)

2022-11-28 15:44 UTC, ClearlyClaire commented
We've officially dropped 2.6 support, you can now rebase your change!

2022-11-28 15:56 UTC, roharon commented
@ClearlyClaire Head repository has been synced changes!

2022-11-28 16:21 UTC, ClearlyClaire approved these changes

2022-12-15 16:07 UTC, Gargron commented
I think this style is much less readable?

2023-12-01 17:10 UTC, mjankowski approved these changes

2024-02-26 14:15 UTC, closed without merging