Clarify language around unlisted and direct posts
mastodon/mastodon pull request #21659
Opened 2022-11-26 04:24 UTC by trwnh

- Renames "Unlisted" to "Not in public timelines"
- Emphasize "mentioned people only" applies to the current post

2022-11-26 04:29 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -        "defaultMessage": "Unlisted",
https://github.com/mastodon/mastodon/blob/fefda70ee063b1c53b2bbbdbfcfc7f043c2b3b4d/app/javascript/mastodon/components/status.js#L56

2022-11-26 04:29 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -        "defaultMessage": "Unlisted",
https://github.com/mastodon/mastodon/blob/fefda70ee063b1c53b2bbbdbfcfc7f043c2b3b4d/app/javascript/mastodon/features/compose/components/privacy_dropdown.js#L15

2022-11-26 04:30 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -        "defaultMessage": "Visible for all, but opted-out of discovery features",
https://github.com/mastodon/mastodon/blob/fefda70ee063b1c53b2bbbdbfcfc7f043c2b3b4d/app/javascript/mastodon/features/compose/components/privacy_dropdown.js#L16

2022-11-26 04:30 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -        "defaultMessage": "Visible for followers only",
https://github.com/mastodon/mastodon/blob/fefda70ee063b1c53b2bbbdbfcfc7f043c2b3b4d/app/javascript/mastodon/features/compose/components/privacy_dropdown.js#LL18

2022-11-26 04:30 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -        "defaultMessage": "Visible for mentioned users only",
https://github.com/mastodon/mastodon/blob/fefda70ee063b1c53b2bbbdbfcfc7f043c2b3b4d/app/javascript/mastodon/features/compose/components/privacy_dropdown.js#L20

2022-11-26 04:31 UTC, ykzts requested changes
If the origin file is not changed, it will rollback with `yarn manage:translations`.

2022-11-26 04:41 UTC, trwnh commented
@ykzts Changed all the components and source files corresponding to the changed messages, thank you ^_^;

2022-11-26 05:04 UTC, ykzts approved these changes

2022-12-01 16:20 UTC, ClearlyClaire commented
Unlisted also opts out of trending

2022-12-15 16:23 UTC, Gargron reviewed
Touching the descriptions just highlights how much "unlisted" doesn't fit in with the other options. There's no good way to summarize what it does. "Public with caveats". "Same as public, but won't appear in a hashtag timeline (if you use a hashtag) and won't appear in trends (if it becomes popular and you opted-in to being discoverable in a different place). It also won't appear in the local and federated timelines (but it won't appear anyway if it's a reply to someone, and it might still appear in a different implementation like Pleroma because "unlisted" isn't *really* an ActivityPub thing because local and federated timelines are not an ActivityPub thing at all)."

Other description changes look fine.

2022-12-16 00:11 UTC, trwnh commented
I think in the long term "unlisted" should be replaced by `toot:discoverable` flag being applied to statuses and not just profiles, and maybe making it a separate per-post toggle for discoverability, but so long as we have current privacy scopes, maybe calling it "Semi-Public" isn't so bad. In any case, we can't really control what other implementations do, and it doesn't feel worth mentioning non-self-reply-filtering from timelines either, as that could change. So what about the following?

"Semi-Public"

"Visible to anyone on your profile and in home timelines[, but not in public timelines, hashtags, or trends]"

I'm not sure if the second half is strictly necessary or implied by the first half, or if it could be replaced by the word "only". I'm inclined to think it might be. We already have a hint banner that appears when someone tries to use a hashtag in an unlisted post.

2023-12-04 16:01 UTC, mjankowski commented
Closing due to no activity in ~1 year, merge conflicts, and lack of consensus around the "unlisted" specific changes.

If you want to push the rest forward, can you rebase and reopen with just the non-unlisted-related changes in this PR?

2023-12-04 16:01 UTC, closed without merging