Clarify steps for and limitations on verification
mastodon/mastodon pull request #21703
Opened 2022-11-26 22:40 UTC by PrecisionWordcraft

1) The docs indicate that the link to a personal website should be in HTTPS format. That's been added here. 2) Only if the website uses at least one page of static HTML will verification succeed, and the link to Mastodon has to be within that static HTML. That's been clarified. The docs will be enhanced to clarify the limitation with respect to CMS websites. 3) What you should expect to see if verification succeeds has been added.

2022-11-27 01:38 UTC, afontenot commented
I think this might actually be more misleading than the previous version, because the (1) (2) ordering of steps incorrectly implies that verification will work if you put the link to your website in the profile metadata and *after that* add the link back to your profile on your website. In fact, the steps have to be done the other way around.

This may be obvious to some, but I've helped several people who couldn't verify because they didn't understand this ordering requirement.

2022-11-27 07:41 UTC, PrecisionWordcraft commented
Believe it or not the reverse order did eventually work for me, but the verification highlight didn't show up right away.

But I agree, the order you've suggested is a better idea as is making clear the type of link.  I'll make the edits shortly God willing.

I don't understand the i18n test failure: can you shed any light?

2022-11-27 09:02 UTC, afontenot commented
> Looks like the build has failed twice, the first time for an i18 test failure, the second time for a reason that is unclear. Can you shed any light?

I think it's probably because the line you added contains a single quote - `site's` - and the string itself is single quoted. So you're ending the string early.

> Believe it or not the reverse order did eventually work for me, but the verification highlight didn't show up right away.

Yeah, I think a recheck can get triggered in certain conditions, but I'm not sure what those are. I had a correct setup fail to show the verification check for days. I was resaving my profile, but my instance didn't recheck it until I removed it from the profile, saved it, and then added it back.

2022-11-27 09:15 UTC, PrecisionWordcraft commented
Just took out the single quote and clarified that the link on the profile page needs to lead back to the static HTML page you used for the Masto link.

2022-12-01 12:44 UTC, ClearlyClaire requested changes

2022-12-01 12:44 UTC, ClearlyClaire commented on config/locales/en.yml
> +    explanation_html: 'You can <strong>verify yourself as the owner of the links</strong> in your profile metadata. First, add the HTTPS URL for your Mastodon profile page, as an <a> or <link> tag, t
`<a>` and `<link>` are not escaped as they should be.

2023-12-04 16:54 UTC, mjankowski commented
Closing due to merge conflicts and lack of activity -- if you'd still like to push a version of this change forward, can you rebase,  address the requested feedback, and reopen?

2023-12-04 16:54 UTC, closed without merging