Hides superluous details on small screens
mastodon/mastodon pull request #2175
Opened 2017-04-19 21:48 UTC by ashfurrow

This is a follow up from https://github.com/tootsuite/mastodon/pull/2116 . It removes the "Getting Started" column header, and local/federated timeline links, on mobile. I'll add some comments inline in the PR looking for clarifications or further follow-up.

Before:

<img width="379" alt="screen shot 2017-04-19 at 5 47 01 pm" src="https://cloud.githubusercontent.com/assets/498212/25203709/37825632-2528-11e7-9dae-32e46019c78d.png">

After:

<img width="392" alt="screen shot 2017-04-19 at 5 45 55 pm" src="https://cloud.githubusercontent.com/assets/498212/25203683/1bf703ea-2528-11e7-82a6-895641da07df.png">

Fixes #2072.

2017-04-19 21:49 UTC, ashfurrow commented on app/assets/javascripts/components/features/ui/components/column_link.jsx
> -  display: 'block',
This is what I wasn't clear on; I don't know why the style is inline but I had to move the `display` property to CSS to be able to override it from within the stylesheet. If more/all of these should be moved over, or if there's a better way to do any of this, let me know 👍

2017-04-21 01:34 UTC, Gargron requested changes

2017-04-21 01:34 UTC, Gargron commented on app/assets/stylesheets/components.scss
> +    @media screen and (max-width: 600px) {
The "mobile" layout begins at 1024px, atm.

2017-04-21 16:17 UTC, Gargron approved these changes

2017-04-21 16:17 UTC, merged

2017-04-22 14:47 UTC, emmanuelclement commented
Thanx guys :-)