Add copy address button to account header
mastodon/mastodon pull request #21761
Opened 2022-11-27 22:55 UTC by pera

This PR adds a copy address button next to the address in the account header:

![1](https://user-images.githubusercontent.com/338659/204163847-a9878f78-f72e-4721-bfa4-0d7c57a62b70.png)

If the the account is locked the lock icon is listed first:

![2](https://user-images.githubusercontent.com/338659/204163850-a954eb2e-4b0b-4864-a438-fd4f7d4de0f1.png)

In case you wonder how it would look with the icons swapped:

![3](https://user-images.githubusercontent.com/338659/204163853-06748a5b-b0f2-410f-b6c3-18285b7a8791.png)

2022-11-27 23:00 UTC, connorshea commented
Should note that this resolves #21074 and #19850

2022-11-27 23:03 UTC, pera commented
Another font-awesome icon that could work is `fa-clipboard`:
![image](https://user-images.githubusercontent.com/338659/204164473-d3b12b85-78ab-44e1-accc-e9ae8921fad8.png)

2022-12-01 12:50 UTC, ClearlyClaire commented
Hi! Thank you for your contribution! It's a useful feature, although I'm not completely satisfied with how it looks when an account is locked… unfortunately, I don't have a better suggestion.

I also wonder if #21479 wouldn't be enough here in making the handle easier to copy.

2022-12-02 22:19 UTC, pera commented
Thanks very much for the feedback @ClearlyClaire, and I agree with your comment: having both an icon and an icon-button next to each other can be confusing. The only idea that comes to my mind right now would be to remove the lock icon from its current location:

1. The meaning of the lock icon differs between Mastodon and other social networks, so as an UI element it can be misleading
2. If a user wants to follow someone the attention goes to the Follow button (not the address)
3. The copy button pattern is quite standard nowadays and introducing this functionality would improve the UX on mobile

I propose then to update the "Follow" button to something like "Send follow request" when the account requires follow requests.

Cheers!

2022-12-15 17:18 UTC, Gargron requested changes
I remember talking with you about this in Discord, but I would like to use the UX pattern established by e.g. DigitalOcean and Hetzner for copying IP addresses on screen, and avoid adding another icon to that space. You should be able to click the string to have it copied to the clipboard, with a "Copied" message appearing shortly.

2023-12-01 17:06 UTC, mjankowski commented
Closing due to lack of activity for ~1 year, and different direction chosen from most recent comment.

If you want to push this forward and re-open, can you rebase it, and then do the copy-on-click approach instead of the icon?

2023-12-01 17:06 UTC, closed without merging

2024-01-01 12:12 UTC, pera commented
@mjankowski sorry I just saw this - tbh the current select-on-click functionality is enough for me as a user, but if you still think this could improve the UX I would be happy to rebase and do the changes.