Set OTP input to numeric input
mastodon/mastodon pull request #21876
Opened 2022-11-30 08:28 UTC by DBendit

Before, when entering an OTP on mobile, the full standard keyboard would be available, in spite of only needing numeric inputs for the OTC.

Now, the numeric keypad is displayed, making it easier to enter the OTP and following OTP best practices.

2022-11-30 08:41 UTC, Gargron approved these changes

2022-11-30 21:38 UTC, rinsuki requested changes
I think user may not able to input recovery codes, because recovery code including alphabets

2022-11-30 21:43 UTC, DBendit commented
> I think user may not able to input recovery codes, because recovery code including alphabets

Unfortunately, I think you're right. It looks like other sites that provide numeric inputs for OTP have a separate page for recovery codes. I'll look into what it'll take to set that up, though I admit I only undertook this in the first place on the belief that this would be a one-line change.

2022-12-15 14:55 UTC, Gargron commented
Looks like it's a no-go then?

2022-12-15 14:55 UTC, closed without merging