ActivityPub: Add basic, read-only support for Outboxes, Notes, and Create/Announce Activities
mastodon/mastodon pull request #2197
Opened 2017-04-20 06:54 UTC by evanminto

As part of ActivityPub integration, this branch adds Activity Streams 2.0 outboxes, accessible via URLs published in users' AS2 account representations. I tried to keep the changes fairly limited, but in order to create a functional outbox endpoint I needed to create a few related endpoints as well, for notes and activities. Those endpoints have basic support for reblogging and replies, which was *maybe* overkill, so I'm happy to take them out if we want to keep things simpler for now. There are fairly extensive tests of all of the endpoints.

Here's how I mapped from Mastodon-land to AP-land:
* Mastodon's statuses, which represent a user posting a message on the site, have two representations, in keeping with ActivityPub standards: a Note object representing the actual document that the user created, and a Create object representing the action of creating it.
* Why the distinction? Reblogging shows a clear case for it, since a reblog is represented as a single Announce activity, with the reblogged note as its object property.
* For now, **the outbox only shows public statuses**, which means it's basically like the public timeline, but for a single user. This seemed like the safest bet, but it may be more appropriate to include unlisted statuses as well (since this is what the profile page does). **Unlisted statuses are still accessible directly via their AP URL, but private and direct statuses are NOT.**

Potential areas to change:
* Should we use Announce for reblogs? AP lacks a clear reblogging function AFAICT. If so, should we announce the original note, or its creation activity? I went with the latter.
* Should we include unlisted statuses in the outbox?

Also my commit history is a *little* messy so I'd recommend squashing if you're not doing that already.

2017-04-20 11:22 UTC, Gargron requested changes
👍 

I feel like something could be said about the naming of the templates, but it's a minor detail that can be changed later.

2017-04-20 11:22 UTC, Gargron commented on app/controllers/accounts_controller.rb
> +        headers['Access-Control-Allow-Origin'] = '*'
You should check `config/application.rb` for CORS settings, and move all of the CORS stuff there.

2017-04-20 11:22 UTC, Gargron commented on app/controllers/api/activitypub/outbox_controller.rb
> +    unless @statuses.empty?
I feel like you could reuse logic from other API methods almost vebatim here, not sure why this complicated block

2017-04-20 11:22 UTC, Gargron commented on app/helpers/activitystreams2_builder_helper.rb
> +    account.display_name.empty? ? account.username : account.display_name
As I've learned, this should be written as `account.display_name.presence || account.username`

2017-04-20 11:22 UTC, Gargron commented on app/views/activitypub/types/announce.activitystreams2.rabl
> +node(:type) { 'Announce' }
ActivityPub has no verb for "share"?

Reblogs should definitely be "share [original note]", I don't feel like "announce [creation of original note]" is semantic at all

2017-04-20 11:22 UTC, Gargron commented on app/views/api/activitypub/outbox/show.activitystreams2.rabl
> +node(:updated) do |account|
Local statuses are always strictly chronological so it's enough to get the "first" time without loops and max.

2017-04-20 11:22 UTC, Gargron commented on config/locales/en.yml
> +  activitypub:
If this is only ever going to be seen by other servers, is i18n necessary here?

2017-04-20 15:45 UTC, evanminto commented on config/locales/en.yml
> +  activitypub:
This is an area I don't know enough about. I did this just to be sure, but I'll run through the AP documentation again to check if there's a need for internationalization.

2017-04-21 04:48 UTC, evanminto commented on app/controllers/accounts_controller.rb
> +        headers['Access-Control-Allow-Origin'] = '*'
I've been trying to do that, but it doesn't seem to be working. I may just leave it out of this PR (it's not strictly necessary right now).

2017-04-21 04:52 UTC, evanminto commented on app/views/activitypub/types/announce.activitystreams2.rabl
> +node(:type) { 'Announce' }
It's a little odd, but I did some more reading and it looks like Announce is the canonical AP way to do this: https://github.com/w3c/activitypub/issues/186

That said, it's not a bad idea to at least change the name of the activity to say "share."

2017-04-21 04:55 UTC, evanminto commented on config/locales/en.yml
> +  activitypub:
For reference, here's the AS2 section on natural language values: https://www.w3.org/TR/activitystreams-core/#naturalLanguageValues

It looks like we can either just do English or provide all of the language options that Mastodon supports in the same JSON object. I'd err on the side of the former for now, but whether to add full language support later is your call.

2017-04-21 06:44 UTC, evanminto commented
I realized when I took another look at this that my implementation of pagination isn't quite right for the AS2 spec. I'm taking another look at it right now.

2017-04-23 02:57 UTC, Gargron approved these changes

2017-04-23 03:21 UTC, merged