Change the "punitive action email" text in English to mention account locality
mastodon/mastodon pull request #22003
Opened 2022-12-03 19:11 UTC by limdingwen

The current text may mislead admins to think that emails are sent to remote reported accounts. This change clarifies that emails will only be sent to local reported accounts.

2022-12-06 23:00 UTC, Gargron requested changes
"Instance" is incorrect. Use "server".

2022-12-07 06:19 UTC, limdingwen commented
I've changed it.

2022-12-15 18:21 UTC, Gargron approved these changes

2023-01-13 09:53 UTC, ClearlyClaire commented
I approved it but I actually think #18388 makes more sense.

2023-01-13 10:03 UTC, closed without merging