add title to new user username input to show allowed pattern
mastodon/mastodon pull request #22008
Opened 2022-12-03 20:10 UTC by eslerm

Adds a title to the new username input field with the allowed username pattern. If an incorrect character is used, this change will notify the user of which characters are allowed.

example of patched UI in Firefox:
![example](https://user-images.githubusercontent.com/16212934/205459737-23adf785-dc25-4b58-97cb-d504176cabf3.png)

fixes https://github.com/mastodon/mastodon/issues/22007

2022-12-15 16:56 UTC, Gargron requested changes
This is not user-friendly, our target audience are not programmers who know regex.

2022-12-15 23:45 UTC, eslerm commented
hi @Gargron 

This PR avoided locales by using regex. Does a PR with user-friendly locale text sound appropriate to you?

2023-12-04 17:02 UTC, mjankowski commented
Closing due to merge conflicts and lack of activity -- if you still want to push this forward, can you rebase, and update the changed copy to be more user friendly? (remove regex)

2023-12-04 17:02 UTC, closed without merging

2023-12-04 17:39 UTC, eslerm commented
@mjankowski I responded in https://github.com/mastodon/mastodon/issues/22007