Fix unbounded recursion in account discovery
mastodon/mastodon pull request #22025
Opened 2022-12-04 10:39 UTC by ClearlyClaire

2022-12-04 10:59 UTC, ykzts approved these changes

2022-12-04 13:55 UTC, unarist approved these changes

2022-12-04 19:55 UTC, zunda approved these changes

2022-12-04 20:36 UTC, Deauthorized requested changes
Regarding the lint errors for parameter lists being longer than 5 parameters, maybe this could be applied towards it?

https://codereview.stackexchange.com/questions/200298/parameter-list-too-long-in-initialize-method

2022-12-04 21:52 UTC, ClearlyClaire commented
> Regarding the lint errors for parameter lists being longer than 5 parameters, maybe this could be applied towards it?
> 
> https://codereview.stackexchange.com/questions/200298/parameter-list-too-long-in-initialize-method

I honestly would prefer if we switched `CountKeywordArgs` to `false`, but I think it's kind of out of scope for this PR.

2022-12-05 15:11 UTC, simcop2387 commented
If it helps I've manually merged this to my own instance on www dot omeowgle dot com and can help provide logs or anything if additional testing is needed (it's a small single user instance for my cat).

2022-12-06 23:15 UTC, merged