Fix english sentence grammar
mastodon/mastodon pull request #2208
Opened 2017-04-20 10:01 UTC by pmatos

2017-04-20 10:50 UTC, mjankowski requested changes
I think this changes the meaning of the sentence in a way that's not accurate...?

If you want a pure grammar improvement, something like:

    The federated timeline lists public posts from everyone followed by people on {domain}

2017-04-20 11:17 UTC, pmatos commented
@mjankowski I have fixed according to suggestion.

2017-04-20 12:48 UTC, Gargron approved these changes

2017-04-20 14:46 UTC, mjankowski approved these changes

2017-04-23 00:46 UTC, yiskah commented
This PR is obsolete since #1964 was merged. This PR can be closed

2017-04-23 00:48 UTC, closed without merging