Stricter whitelist rules
mastodon/mastodon pull request #2213
Opened 2017-04-20 10:38 UTC by Fiaxhs

I was browsing an instance where you need a whitelisted email domain, however I figured out you could circumvent the protection by using the whitelisted domain as a subdomain of your email address.

2017-04-20 10:47 UTC, mjankowski reviewed
Could you add a spec showing that blacklist doesn't have the same issue?

Also ... instead of the regex approach here, what if we just extracted the hostname portion of the email and did a (case insensitive?) check that it was in the list?

2017-04-20 10:55 UTC, Fiaxhs commented
spec for blacklist: on it.
We could drop the regexp instance yes, but only for whitelisting then.

2017-04-20 11:28 UTC, Fiaxhs commented
I tried to ditch the whitelist regexp, but it created some important issue in my opinion: you can't use it as wildcard to whitelist subdomains.

The instance I found this issue on is a big institution using `institution.tld` as top domain for emails and every service within this instituion as a specific subdomain: `user@service1.institution.tld`, `user@service2.institution.tld` etc.

By removing the regexp, the admin has the tedious task to list all subdomain of whitelisted subdomains (and add them if they're ever created).

I added a spec for specific subdomain blacklist + top domain whitelist.

Anyway, tell me what's the desired approach :)

2017-04-24 20:43 UTC, Gargron requested changes

2017-04-24 20:43 UTC, Gargron commented on spec/models/user_spec.rb
> +    it 'should not allow a smart user to be created unless they are whitelisted' do
Instead of "smart user" could you just describe what is being tested? This will become unclear in the future.

2017-04-25 23:22 UTC, Gargron approved these changes

2017-04-25 23:22 UTC, merged