config/locales: Note app always disclosed to author
mastodon/mastodon pull request #22167
Opened 2022-12-08 19:31 UTC by wbnns

Context:

![image](https://user-images.githubusercontent.com/1130872/206549702-b155ff2a-c8d7-4d31-b4d5-aedc4bbfa33d.png)

I thought that perhaps there was an issue when I had this box unchecked but still saw the app used. I then saw in https://github.com/mastodon/mastodon/issues/13091 where @Gargron noted that an author can always see what app was used to detect misuse.

This PR adds that note as a string for additional clarification in case helpful.

2022-12-10 12:14 UTC, ineffyble commented
@wbnns You'll need to log in to CircleCI and grant it access to your fork for the "build-and-test" check to run.

2022-12-15 18:16 UTC, Gargron requested changes

2022-12-15 18:16 UTC, Gargron commented on config/locales/simple_form.en.yml
> +        setting_show_application: Disclose application used to send posts. The author of the toot can always see what app was used, to detect app misuse
"Toot" -> "post"

2022-12-15 18:16 UTC, Gargron commented on config/locales/simple_form.en_GB.yml
> +        setting_show_application: Disclose application used to send toots. The author of the toot can always see what app was used, to detect app misuse
Do not update this file.

2022-12-16 11:46 UTC, wbnns commented on config/locales/simple_form.en.yml
> +        setting_show_application: Disclose application used to send posts. The author of the toot can always see what app was used, to detect app misuse
Updated :+1:

2022-12-16 11:46 UTC, wbnns commented on config/locales/simple_form.en_GB.yml
> +        setting_show_application: Disclose application used to send toots. The author of the toot can always see what app was used, to detect app misuse
Dropped change

2022-12-16 14:28 UTC, wbnns commented
Oddly, Circle CI doesn't seem to be reporting that `build-and-test` completed successfully. :thinking: 

![image](https://user-images.githubusercontent.com/1130872/208120011-271293f1-6cbc-420c-87ae-c14b667b20b7.png)

2023-08-13 22:07 UTC, gunchleoc commented on config/locales/simple_form.en.yml
> +        setting_show_application: Disclose application used to send posts. The author of the post can always see what app was used, to detect app misuse
Suggestion to rephrase:
> In order to detect misuse, you will always see which application was used for your own posts.

2023-09-19 14:05 UTC, closed without merging