Fix error message when invalid username is provided during signup
mastodon/mastodon pull request #22369
Opened 2022-12-16 15:57 UTC by kailan

This resolves #22007

## Before

<img width="593" alt="Screenshot 2022-12-16 at 15 56 30" src="https://user-images.githubusercontent.com/3542064/208137917-be23de9a-1b08-4732-b62d-f0b9a28f5c6e.png">

## After

<img width="543" alt="Screenshot 2022-12-16 at 15 50 30" src="https://user-images.githubusercontent.com/3542064/208137088-44430620-8a4e-4178-8fec-d88a3d6d4c67.png">

2022-12-19 07:50 UTC, ClearlyClaire requested changes
Hi! Thank you for your contribution!

Setting a custom validation message is a good idea, but this can't be done through inline javascript!

2022-12-19 07:50 UTC, ClearlyClaire commented on app/views/auth/registrations/new.html.haml
> +      = ff.input :username, wrapper: :with_label, label: false, required: true, input_html: { 'aria-label': t('simple_form.labels.defaults.username'), autocomplete: 'off', placeholder: t('simple_form
Inline Javascript is not allowed by our Content Security Policy, so this will not work. Instead, have the JS `app/javascript/packs/public.js`.

2022-12-19 07:50 UTC, ClearlyClaire commented on config/locales/en.yml
> +    username_validity: Must contain only a-Z, 0-9, or _
I am not sure how user-friendly that text is. Maybe “Can only contain letters, numbers and underscores (_)”?

2023-05-03 20:37 UTC, ThisIsMissEm commented
I'm not sure if this is still needed given the current design: 
<img width="512" alt="Screenshot 2023-05-03 at 10 35 55 pm" src="https://user-images.githubusercontent.com/30827/236043821-451f1104-fea0-475b-9cce-ef04bf808fb1.png">

When the form is submitted, you still do receive the browser validation message, though:
<img width="525" alt="Screenshot 2023-05-03 at 10 37 19 pm" src="https://user-images.githubusercontent.com/30827/236044030-2f5e6ec7-6764-4c86-9634-93d90afe9471.png">

2023-05-04 03:43 UTC, closed without merging