Added API for single notification dismissal
mastodon/mastodon pull request #2251
Opened 2017-04-21 08:08 UTC by expenses

Adds a `/api/v1/notifications/dismiss` POST route that takes an `id` parameter and removes the notification with that id.

This is a start to solving #686 and #1900.

2017-04-21 16:10 UTC, Gargron requested changes

2017-04-21 16:10 UTC, Gargron commented on app/controllers/api/v1/notifications_controller.rb
> +    Notification.where(account: current_account, id: params[:id]).delete_all
Maybe `Notification.find_by!(account: current_account, id: params[:id]).destroy!` would be better here (throw 404 when bad ID, throw error if something wrong with deleting it)

2017-04-21 23:29 UTC, expenses commented on app/controllers/api/v1/notifications_controller.rb
> +    Notification.where(account: current_account, id: params[:id]).delete_all
And done!

2017-04-22 00:30 UTC, Gargron approved these changes

2017-04-22 00:30 UTC, merged

2018-10-05 20:15 UTC, Gargron commented
There is actually no reason why this shouldn't be `DELETE /api/v1/notifications/:id`, how did I not catch that...