Add preview card to public statuses
mastodon/mastodon pull request #2268
Opened 2017-04-21 15:44 UTC by mikoim

This make preview card displayable not only in the timeline but also in public statuses. It needs to brush up design because I just copied a style from React implement.

## demo
![](http://i.imgur.com/q3zdFec.png)

2017-04-27 16:45 UTC, mikoim commented
Could somebody review this PR?

2017-04-27 19:20 UTC, Gargron requested changes

2017-04-27 19:20 UTC, Gargron commented on app/assets/stylesheets/stream_entries.scss
> +    border: 1px solid lighten($color1, 8%);
This must be a way lighter color. $color3 maybe?

2017-04-28 18:38 UTC, mikoim commented
@Gargron thank you, I changed the color.

2017-05-03 12:50 UTC, mikoim commented
I rebased this branch to fix conflicts. Please review again.

2017-05-05 13:02 UTC, ykzts requested changes

2017-05-05 13:02 UTC, ykzts commented on app/helpers/routing_helper.rb
> +    URI(url).host
If you like `Addressable::URI.parse(url).display_uri.hostname` you can correspond to IDNA.

2017-05-05 13:02 UTC, ykzts commented on app/views/stream_entries/_preview_card.html.haml
> +    %p{:class => 'status-card__description'} #{card.description}
change to `%p.status-card__description`

2017-05-05 13:02 UTC, ykzts commented on app/views/stream_entries/_preview_card.html.haml
> +    %strong{:class => 'status-card__title', :title => card.title} #{card.title}
change to `%strong.status-card__title{ title: card.title }`

2017-05-05 13:02 UTC, ykzts commented on app/views/stream_entries/_preview_card.html.haml
> +    %span{:class => 'status-card__host', :style => 'display: block; margin-top: 5px; font-size: 13px'} #{hostname(card.url)}
change to `%span.status-card__host{ style: 'display: block; margin-top: 5px; font-size: 13px' }`

2017-05-05 13:02 UTC, ykzts commented on app/views/stream_entries/_preview_card.html.haml
> +      %img{:alt => card.title, :src => card.image, :style => 'display: block, width: 100%, height: auto, margin: 0, border-radius: 4px 0 0 4px'}
Why use the style attribute instead of the stylesheet?

2017-05-05 13:02 UTC, ykzts commented on app/views/stream_entries/_detailed_status.html.haml
> +    = render partial: 'stream_entries/preview_card', locals: { card: card }
change to `render 'stream_entries/preview_card', card: card`

2017-05-05 17:01 UTC, mikoim commented
@ykzts thank you for your review. I fixed problems.

2017-05-05 17:04 UTC, ykzts approved these changes

2017-05-09 12:15 UTC, mikoim commented
rebased

2017-07-19 20:16 UTC, m4sk1n commented
will this be merged?

2017-09-14 01:39 UTC, closed without merging