Fix issue for selecting the mark media as sensitive checkbox via tab.
mastodon/mastodon pull request #22868
Opened 2022-12-31 04:39 UTC by parthoghosh24

User was unable to select the Mark as sensitive checkbox when posting using tab and toggle it via space.

https://user-images.githubusercontent.com/2009988/210124975-809e7a55-bb25-493b-a074-89990e05716c.mp4

This fixes #22842

2023-01-03 04:33 UTC, hs4man21 commented
This change makes the checkbox technically keyboard-focusable, but there are no focus styles on the checkbox, so it is still very difficult to use. I have a PR up that addresses focus style issues similar to this (https://github.com/mastodon/mastodon/pull/22602), but this one is more complex because the component is built with two checkboxes, one that has the styles whereas the real one has this `opacity: 0` / `display: none` configuration. It seems like a better change to fix this issue would be to just have one checkbox that gets the focus and also has the right styles applied.

2023-01-04 03:24 UTC, parthoghosh24 commented on app/javascript/styles/mastodon/components.scss
> +      opacity: 0;
Issue with display:none was that it was causing the checkbox to be skipped when we are cycling the components via tab. Opacity:0 fixes that.

2023-01-04 04:31 UTC, Gargron approved these changes

2023-01-05 10:21 UTC, ClearlyClaire requested changes
The issue with `opacity: 0` instead of `display: none` is that we'll now have two checkboxes, each taking space, but only one visible.

![image](https://user-images.githubusercontent.com/384364/210756545-a90aa584-bd77-4aa5-86ac-cced85f67713.png)

The issue with styling the checkbox itself is that it's notoriously difficult and inconsistent across browsers. That being said, it should be possible to do something reasonable with `appearance: none` these days.

EDIT: See #22949 for an attempt at the latter.

2023-01-05 19:54 UTC, ClearlyClaire commented
The point of #22949 is to not render the fake checkbox but style the real one instead!

2023-04-12 11:59 UTC, ClearlyClaire commented
Closed in favor of #22949

Don't hesitate to let me know or submit PRs if there are still issues in that area!

2023-04-12 11:59 UTC, closed without merging