fix: allow verification when page size exceeds 1MB (using HTML5 parser)
mastodon/mastodon pull request #22879
Opened 2022-12-31 15:22 UTC by untitaker

Truncates the page after 1MB instead, and switches to nokogiri HTML5 parser to handle some edgecases.

Alternative to #22703, handles one edgecase differently, `<a href="https://google.com/"` is not considered as valid. I think this won't matter that much.

Closes #15316

2023-01-02 15:38 UTC, ClearlyClaire commented
That sounds fine on principle. I would advocate against changing unrelated lines to fix linting issues, though, it makes the changes more difficult to review and adds noise to tools like `git blame`.

2023-01-09 11:55 UTC, ClearlyClaire requested changes
Looks fine on principle, but can you avoid making changes to other parts of the code? As long as your changes themselves do not add linting errors, the linter task failing is not an issue.

2023-01-09 12:10 UTC, untitaker commented
i did not get that the linter failures do not block merge. fixed, PTAL

2023-01-09 12:14 UTC, ClearlyClaire approved these changes

2023-01-11 20:59 UTC, merged