change compose form placeholder after user clicked content wanrning button
mastodon/mastodon pull request #2326
Opened 2017-04-22 15:42 UTC by walf443

reading https://github.com/tootsuite/mastodon/pull/2305, I thinks it's difficult for beginner user to imagine what should write to spoiler placeholder field.

So how about like this?

Before Click CW Button:

<img width="291" alt="before_cw" src="https://cloud.githubusercontent.com/assets/2655/25305790/b6f94092-27bc-11e7-923e-f5a22f333b6e.png">

After Click CW Button:

<img width="287" alt="after_cw" src="https://cloud.githubusercontent.com/assets/2655/25305789/b3b079fa-27bc-11e7-8073-5f81e2f2585a.png">

I thinks it's not best message of it. Suggestions are welcome!!

2017-04-22 16:28 UTC, yumetodo commented
found reaction about this PR
https://ostatus.yoh2.ddo.jp/users/yoh2/updates/45

It is same as my opinion pointed out in #2310 that writing message to explain about the input area instead of writing example message.

2017-04-23 00:35 UTC, yiskah requested changes
There are some minor English grammatical errors. When you `hide` text, it is `hidden`. I'm unsure why you are removing lines from all the locales

2017-04-23 00:35 UTC, yiskah commented on app/assets/javascripts/components/features/compose/components/compose_form.jsx
> +  hide_text_placeholder: { id: 'compose_form.hide_text_placeholder', defaultMessage: 'This text hide by default.' },
This phrasing is a bit off for English, but a good try. I'd go for something like "Text to hide behind warning"

2017-04-23 00:35 UTC, yiskah commented on app/assets/javascripts/components/features/compose/components/compose_form.jsx
> +  spoiler_placeholder: { id: 'compose_form.spoiler_placeholder', defaultMessage: 'Write warnings before hide text.' },
Minor change, for English should be "Warning before hidden text" or "Write warning before hidden text"

2017-04-23 00:35 UTC, yiskah commented on app/assets/javascripts/components/locales/en.jsx
> +  "compose_form.spoiler_placeholder": "Write warnings before hide text.",
Another spot. `hide` should be `hidden`

2017-04-23 00:35 UTC, yiskah commented on app/assets/javascripts/components/locales/fr.jsx
>    "compose_form.spoiler": "Masquer le texte derrière un avertissement",
Is there a reason you are removing this line from the French locale?

2017-04-23 02:01 UTC, walf443 commented on app/assets/javascripts/components/locales/fr.jsx
>    "compose_form.spoiler": "Masquer le texte derrière un avertissement",
I changed compose_form.spoiler_placeholder meaning. so translation should change.

2017-05-10 03:47 UTC, beatrix-bitrot commented
the branch for this PR was deleted 16 days ago, should it be closed?

2017-05-10 14:22 UTC, walf443 commented
Thanks.

2017-05-10 14:22 UTC, closed without merging