Fix blocked domain appears from account feed
mastodon/mastodon pull request #23280
Opened 2023-01-28 00:42 UTC by tribela

AccountStatusesFilter wasn't filtering domain blocks

2023-01-30 07:47 UTC, ClearlyClaire requested changes
Looks fine except for the inline comment.

2023-01-30 07:47 UTC, ClearlyClaire commented on app/models/account_statuses_filter.rb
> +      .joins('LEFT OUTER JOIN accounts reblogs_accounts ON reblogs_accounts.id = reblogs_statuses.account_id')
I'm a bit confused by the position of the `where` here, wouldn't it be more understandable like this?
```suggestion
      .left_outer_joins(:reblog)
      .joins('LEFT OUTER JOIN accounts reblogs_accounts ON reblogs_accounts.id = reblogs_statuses.account_id')
      .where(reblog_of_id: nil)
```

An even more concise and idiomatic way may be:
```suggestion
    .left_outer_joins(reblog: :account)
    .where(reblog_of_id: nil)
```

Though that would rename `reblogs_accounts` to `accounts` and that may end up more confusing and more brittle.

2023-01-30 10:40 UTC, ClearlyClaire approved these changes

2023-01-30 14:23 UTC, ClearlyClaire commented
(The performance implications should be relatively minor, but I'm not sure whether we should merge that for 4.1.0 without evaluating them thoroughly first)

2023-09-06 15:52 UTC, ClearlyClaire commented
Oops! sorry we forgot this PR!

I'm going to create a new PR with this changes, as this is going to be easier for us to test. Thank you for your contribution!

2023-09-07 00:02 UTC, tribela commented
Closing this by #26823

2023-09-07 00:03 UTC, closed without merging