Add error message for when following own account
mastodon/mastodon pull request #23373
Opened 2023-02-02 16:28 UTC by gabrielcosta42

* Add a specific error message for when attempting to follow your own account via the API

It would handle the attempt to follow your own account as if the account record didn't exist.

* Add tests

fixes  #22690

2023-08-25 11:08 UTC, gunchleoc commented
English language fix suggestions:

> Following your own account is not allowed

or

> You can’t follow your own account

2023-12-28 19:30 UTC, vmstan commented
@gabrielcosta42 are you able to rebase this?

2023-12-28 19:31 UTC, vmstan requested changes

2023-12-28 19:31 UTC, vmstan commented on app/controllers/api/v1/accounts_controller.rb
> +    render json: { error: 'Follow your own account is not allowed' }, status: 403
```suggestion
    render json: { error: 'Following your own account is not allowed' }, status: 403
```

2023-12-28 19:31 UTC, vmstan commented on spec/controllers/api/v1/accounts_controller_spec.rb
> +          expect(json[:error]).to eq 'Follow your own account is not allowed'
```suggestion
          expect(json[:error]).to eq 'Following your own account is not allowed'
```

2024-05-26 15:53 UTC, mjankowski commented
Closing due to lack of activity, need for rebase, unresponded-to review comments, etc.

If you want to push forward, please rebase, reopen, address comments, etc.

2024-05-26 15:53 UTC, closed without merging