Language: Missing keys for pt and pt-BR
mastodon/mastodon pull request #2355
Opened 2017-04-23 11:07 UTC by camponez

2017-04-23 13:22 UTC, mjankowski requested changes
It looks like there are parse errors with the yaml here, can you investigate?

2017-04-23 20:51 UTC, camponez commented
Ok, I look at all keys. I don't get what
` can not load translations from /home/travis/build/tootsuite/mastodon/config/locales/pt-BR.yml: #<Psych::SyntaxError: (/home/travis/build/tootsuite/mastodon/config/locales/pt-BR.yml): did not find expected key while parsing a block mapping at line 309 column 5>`
mean exactly.

2017-04-23 22:09 UTC, nightpool commented on config/locales/pt-BR.yml
> +    instructions_html: "<strong>Scaneie este código QR no seu Google Authenticator ou aplicativo similar no seu telefone</strong>. A partir de agora seu aplicativo irá gerar tokens que deverão ser di
the period here has to be inside of the quotation marks, or else it's a syntax error. the quotation marks aren't part of the string, they're just part of the yml literal syntax

2017-04-23 22:11 UTC, nightpool commented on config/locales/pt.yml
> +    instructions_html: "<strong>Scaneie este código QR no seu Google Authenticator ou aplicativo similar no seu telefone</strong>. A partir de agora seu aplicativo irá gerar tokens que deverão ser di
same as above

2017-04-23 22:11 UTC, camponez commented on config/locales/pt-BR.yml
> +    instructions_html: "<strong>Scaneie este código QR no seu Google Authenticator ou aplicativo similar no seu telefone</strong>. A partir de agora seu aplicativo irá gerar tokens que deverão ser di
Thanks. Missed that!

2017-04-23 22:13 UTC, nightpool commented
I recommend using http://yaml-online-parser.appspot.com/ to test your YML if you have issues with it. it's error messages are often more informative then the standard ruby ones.

2017-04-24 00:40 UTC, mjankowski approved these changes

2017-04-24 00:49 UTC, merged