[WIP] Account domain blocks
mastodon/mastodon pull request #2381
Opened 2017-04-24 00:47 UTC by Gargron

- [x] Model
- [x] Filter from public timeline queries
- [x] Filter from notifications
- [ ] Filter from home feed
- [ ] Filter from streaming API
- [ ] Filter from "context" (conversation threads)
- [ ] API method to block/unblock domain
- [ ] API method to list blocked domains
- [ ] Web UI dropdown option to block domain on profile
- [ ] Web UI list of blocked domains

2017-04-24 01:05 UTC, mjankowski commented on app/models/account.rb
> +    AccountDomainBlock.where(account: self, domain: other_account.domain).exists?
Account could probably use a has_many for :account_domains_blocks, which this method could then use.

2017-04-24 01:06 UTC, mjankowski commented on app/models/status.rb
> +      domains = Rails.cache.fetch("exclude_domains_for:#{account_id}") { AccountDomainBlock.where(account: account).pluck(:domain) }
Instead of a local variable here, how about a (Rails cached) method like `Account#blocked_domains`? which the next line could call directly

2017-04-24 01:06 UTC, mjankowski commented on db/schema.rb
> +    t.integer  "type",               default: 0,  null: false
This schema change is likely from another PR.

2017-04-24 01:06 UTC, mjankowski commented on spec/fabricators/account_domain_block_fabricator.rb
> +  account_id 1
ONE!

2017-04-24 08:49 UTC, wxcafe commented
Closing #501 since this is the same feature and that old PR is not up to date anymore (by a long shot)

2017-05-14 21:22 UTC, Gargron commented
I can't imagine very well how the API for domain blocks should actually look.

```
GET /api/v1/domain_blocks - returns list of { id: domainBlockId, domain: blockedDomainString }
POST /api/v1/domain_blocks - creates domain block for "domain" param
```

How to unblock?! Use a DELETE route using the ID of the domain block? Use domains instead of IDs?

2017-05-18 22:56 UTC, beatrix-bitrot requested changes
overall looks good, only very minor stuff

2017-05-18 22:56 UTC, beatrix-bitrot commented on app/models/status.rb
> +    # FIXME: n+1 bonanza
Are you gonna fix the N+1 bonanza?

2017-05-18 22:56 UTC, beatrix-bitrot commented on app/controllers/api/v1/domain_blocks_controller.rb
> +  def show
curious why this is show and not index since it's giving a collection rather than an individual object

2017-05-18 22:56 UTC, beatrix-bitrot commented on config/routes.rb
> +      resource :domain_blocks, only: [:show, :create, :destroy]
again, wondering why show and not index

2017-05-18 22:56 UTC, beatrix-bitrot commented on spec/models/account_domain_block_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
indeed! add some tests or delete it

2017-05-18 22:58 UTC, Gargron commented on app/models/status.rb
> +    # FIXME: n+1 bonanza
No it's been present since day 1, it's a fix for another day with less time pressure

2017-05-18 22:59 UTC, Gargron commented on app/controllers/api/v1/domain_blocks_controller.rb
> +  def show
Because it's a "resource" route and not "resources" (so that we can send DELETE /api/v1/domain_blocks)

2017-05-18 23:07 UTC, beatrix-bitrot approved these changes
concerns addressed

2017-05-18 23:14 UTC, merged