Update Contributor Covenant to 2.1
mastodon/mastodon pull request #23980
Opened 2023-03-06 04:55 UTC by nschonni

Noticed there was a newer version of the covenant out, so grabed the markdown version from https://www.contributor-covenant.org/version/2/1/code_of_conduct/, ran `yarn format`, and updated the contact eamil back to the current address.

2023-03-20 21:51 UTC, mjankowski approved these changes

2023-04-23 20:45 UTC, Gargron requested changes

2023-04-23 20:45 UTC, Gargron commented on CODE_OF_CONDUCT.md
> +eugen@zeonfederated.com.
hello@joinmastodon.org would be better

2023-04-23 20:50 UTC, nschonni commented on CODE_OF_CONDUCT.md
> +eugen@zeonfederated.com.
```suggestion
[hello@joinmastodon.org](mailto:hello@joinmastodon.org).
```

2023-04-23 21:09 UTC, Gargron approved these changes

2023-04-23 21:11 UTC, merged