Support the PROXY protocol through the PROXY_PROTO_V1 env variable
mastodon/mastodon pull request #24064
Opened 2023-03-10 16:13 UTC by CSDUMMI

See: https://puma.io/puma/Puma/DSL.html#set_remote_address-instance_method for documentation on the set_remote_address method.

2023-03-12 23:12 UTC, Gargron approved these changes

2023-03-13 09:56 UTC, ClearlyClaire commented on config/puma.rb
> +end
Just a minor change to fit our code styles:
```suggestion
set_remote_address(proxy_protocol: :v1) if ENV['PROXY_PROTO_V1']
```

2023-03-13 13:07 UTC, ClearlyClaire requested changes

2023-03-13 13:07 UTC, ClearlyClaire commented on config/puma.rb
> +set_remote_address(proxy_protocol: :v1) if ENV['PROXY_PROTO_V1']
Sorry to ask you to change it again, but pretty much all boolean environment variables we use require being explicitly set to `true`. Can you change it to:
```suggestion
set_remote_address(proxy_protocol: :v1) if ENV['PROXY_PROTO_V1'] == 'true'
```

2023-03-14 13:47 UTC, ClearlyClaire approved these changes

2023-03-14 13:47 UTC, merged