Fixed mention regex to support unicode
mastodon/mastodon pull request #2420
Opened 2017-04-25 01:23 UTC by marrus-sh

I haven't been able to test this but it should be pretty straightforward; right now because the regex uses `\w` things like `niñ@s` will create an `@s` mention. This changes it to stop mentions after any unicode word character.

2017-04-25 02:08 UTC, Gargron commented
If you could write out the test case in words ("if x then it should y") I can add the tests for you. I don't feel comfortable merging this blindly.

2017-04-25 16:09 UTC, Artoria2e5 commented
Hmm, let me guess. If an `@` sign is preceded by anything that can form a word -- a latin character like `ñ`, an ASCII alphabet like `a`, a Han Character like `一`, then no at-mentions should be extracted. Current `\w` only handles the ASCII case while Ruby's `[:word:]` provides a more Unicode-oriented solution that handles the other two examples.

2017-05-02 21:39 UTC, Gargron requested changes

2017-05-02 21:39 UTC, Gargron commented on app/models/account.rb
> +  MENTION_RE = /(?:^|[^\/[:word:]])@([a-z0-9_]+(?:@[a-z0-9\.\-]+[a-z0-9]+)?)/i
It would be nice if you added a simple test case for old behaviour vs new behaviour

2017-05-11 01:34 UTC, Gargron approved these changes

2017-05-11 01:47 UTC, merged