Spec coverage on Settings/ controllers specs
mastodon/mastodon pull request #24221
Opened 2023-03-23 01:52 UTC by mjankowski

Adds more coverage to the /settings/ controllers.

Does not quite get to 100% on this group ... but pretty close. Mostly failure edge cases left to do, but I think the full happy path is covered after these changes.

2023-04-07 12:38 UTC, ClearlyClaire requested changes
In most cases, the tests you added only check for the HTTP response code. While that's still an improvement given these methods aren't currently tested at all, that makes the test descriptions misleading, whereas similar test descriptions read something like “returns http success” in our other tests.

I'd like that either the tests get changed to actually test what they claim, or their description be changed to reflect what they are actually testing.

2023-04-07 12:38 UTC, ClearlyClaire commented on spec/controllers/settings/aliases_controller_spec.rb
> +      expect(response).to redirect_to(settings_aliases_path)
I think it should also check that the record actually gets deleted.

2023-04-07 12:38 UTC, ClearlyClaire commented on spec/controllers/settings/aliases_controller_spec.rb
> +        expect(response).to redirect_to(settings_aliases_path)
I think it should also check that a record gets actually created.

2023-04-11 09:15 UTC, mjankowski commented
Pushed update with a few spec changes for better creation/deletion checks, and also some wording changes to make some of the descriptions less inaccurate.

You are correct that my current goal here is broad coverage and just getting all the lines executing in the spec. I'll continue to go deeper on actual behavior specs once the broad coverage is solid.

2023-04-11 09:23 UTC, ClearlyClaire requested changes

2023-04-11 09:23 UTC, ClearlyClaire commented on spec/controllers/settings/migration/redirects_controller_spec.rb
> +  end
I think those two tests still have misleading descriptions.

2023-04-11 09:27 UTC, mjankowski commented on spec/controllers/settings/migration/redirects_controller_spec.rb
> +  end
They sure do -- pushed another commit changing their descriptions as well.

2023-04-11 09:27 UTC, ClearlyClaire approved these changes

2023-04-11 09:35 UTC, merged