Fix description in /api/v1/instance
mastodon/mastodon pull request #24376
Opened 2023-04-03 12:12 UTC by HeitorMC

Solves #23946

Now, `/api/v1/instance` returns the same data as in the admin panel.

Also, `site_description` was removed from `config/settings.yml` since the field wasn't used anywhere in the codebase.

2023-04-05 13:46 UTC, ClearlyClaire reviewed
One issue is that IIRC the `description` field of `/api/v1/instance` is supposed to be plain text, while the extended description supports Markdown. This is probably a lesser issue than a description you can't update, though.

2023-04-14 13:46 UTC, HeitorMC commented
> One issue is that IIRC the `description` field of `/api/v1/instance` is supposed to be plain text, while the extended description supports Markdown. This is probably a lesser issue than a description you can't update, though.

Hey @ClearlyClaire, thank you for your reply. I'm a little confused, so is this PR ok and there is another issue related to the markdown support for the `extended_description`, or this issue is part of the actual problem related by @ledlamp

2023-04-17 08:11 UTC, ClearlyClaire commented
> Hey @ClearlyClaire, thank you for your reply. I'm a little confused, so is this PR ok and there is another issue related to the markdown support for the `extended_description`

What I meant is I believed that `site_description` was meant to be plain-text.

But I was mistaken, `Setting.site_description` did allow HTML. `Setting.site_extended_description` is Markdown-formatted though, so it should be rendered as HTML before being served in `/api/v1/instance`. See `REST::ExtendedDescriptionSerializer` for how it's done.

2023-04-23 20:32 UTC, Gargron requested changes

2023-04-23 20:32 UTC, Gargron commented on app/serializers/rest/v1/instance_serializer.rb
> +    object.extended_description
It is best to just alias this to `short_description`.

2024-05-25 15:30 UTC, mjankowski commented
Closing due to lack of activity.

If you want to nudge forward, can you rebase, re-open this issue, and address the prior review feedback?

2024-05-25 15:30 UTC, closed without merging