Add media dimensions
mastodon/mastodon pull request #2448
Opened 2017-04-25 16:50 UTC by siuying

See #1985

2017-04-25 18:36 UTC, Gargron approved these changes

2017-04-25 21:36 UTC, Gargron requested changes

2017-04-25 21:36 UTC, Gargron commented on spec/models/media_attachment_spec.rb
> +      expect(media.meta[:width]).to eq 600
I think this needs to be `media.file.meta`

2017-04-26 01:08 UTC, siuying commented on spec/models/media_attachment_spec.rb
> +      expect(media.meta[:width]).to eq 600
Fixed, sorry have not setup the test env, not got it sorted.

2017-04-26 01:48 UTC, Gargron approved these changes

2017-04-26 01:48 UTC, merged