Add Kab locale
mastodon/mastodon pull request #2457
Opened 2017-04-25 21:45 UTC by belkacem77

Add Kab locale

2017-04-25 21:52 UTC, Artoria2e5 requested changes

2017-04-25 21:52 UTC, Artoria2e5 commented on app/assets/javascripts/components/locales/index.jsx
> +import kab from './kab';
Your `kab.jsx` seems missing from this PR. Try adding with `git add kab.jsx` before doing `git commit`.

2017-04-25 22:21 UTC, belkacem77 commented on app/assets/javascripts/components/locales/index.jsx
> +import kab from './kab';
Thanks
The file is sent. The translation will be completed later.

2017-04-26 03:54 UTC, yookoala commented
I couldn't find Kabyle language preference in neither Chrome or Firefox. That means the only way you could select the language is from the account preference screen. You'd need to at least update `app/helpers/settings_helper.rb` to have that option available. You'd probably need to update several JS, Ruby and YAML files to get it properly working.

Please read the documentations for more details:
https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md

2017-05-07 16:51 UTC, BoFFire commented on app/assets/javascripts/components/locales/index.jsx
> +import kab from './kab';
Hi @belkacem77 thank you very much for answering my e-mail :)
And welcome to kabyle language into Mastodon :)
If you need any help just ping me :)
Tanmirt ik.

2017-05-07 16:56 UTC, BoFFire commented
@Artoria2e5 @yookoala I would like to notify you that @belkacem77 translated Mozilla Firefox (Thunderbird, VLC ...) into Kabyle language and many other software. Here is a web preview of this language, in case :) :
https://www.mozilla.org/kab/

2017-05-09 03:53 UTC, yookoala commented
@BoFFire

Thanks. But I couldn't find Kab in the "Accepted-Language" selection: "Firefox > Preferences > Content > Languages". He might have missed that. Not trying to stop him from translating Kab. Just want to see that really in use.

Meanwhile, please provide the Kab translations.

2017-05-09 07:59 UTC, belkacem77 commented
Please you can check here: https://transvision.mozfr.org/?recherche=toolkit%2Fchrome%2Fglobal%2Fintl.properties%3Aintl.accept_languages&repo=central&sourcelocale=en-US&locale=kab&search_type=entities&entire_string=entire_string

If someone uses  Firefox kab locale,  you can also check here : http://www.reliply.org/tools/requestheaders.php

2017-05-09 08:51 UTC, yookoala commented
The commit this PR based on is really old. The folder structure for javascripts has been vastly changed. I'd recommend you to redo your work on latest master and force push to your `patch-1` branch. Or you may finish you translation first. I can help do the relocating.

2017-05-11 01:36 UTC, Gargron commented
Seems like this PR is missing the actual translation, so closing.

2017-05-11 01:36 UTC, closed without merging

2017-05-11 01:49 UTC, belkacem77 commented
I will redo the work later. Thanks for help.

2019-11-24 10:22 UTC, BoFFire commented
@mozillakab Update : kabyle available on https://crowdin.com/project/mastodon/kab#

2019-11-24 10:52 UTC, mozillakab commented
Azul fell-ak.

Good thx

On Sun, Nov 24, 2019 at 11:22 AM ButterflyOfFire <notifications@github.com>
wrote:

> @mozillakab <https://github.com/mozillakab> Update : kabyle available on
> https://crowdin.com/project/mastodon/kab#
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tootsuite/mastodon/pull/2457?email_source=notifications&email_token=ABVVHDEQFLGW6YA4FMK4NMDQVJIUVA5CNFSM4DJAMNDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFAIANI#issuecomment-557875253>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVVHDF2ULWOGWFJQAZ6URLQVJIUVANCNFSM4DJAMNDA>
> .
>

2020-01-27 07:18 UTC, BoFFire commented
@mozillakab update https://github.com/tootsuite/mastodon/pull/12962