Fix  `tootctl accounts approve --number N` not aproving N earliest registrations
mastodon/mastodon pull request #24605
Opened 2023-04-20 16:30 UTC by danielmbrasil

Related to #24596 and #24597. This PR fixes the issue discussed in #24597.

When using the CLI to approve the N earliest registrations, the order in which accounts are approved is unspecified. Thus, there's no guarantee the N earliest accounts are being approved.

This PR adds and ordering in pending accounts closed on `created_at` in `Mastodon::AccountsCLI#approve` to guarantee the order in which accounts are being approved when using the `--number` options.

2023-04-23 20:26 UTC, Gargron requested changes

2023-04-23 20:26 UTC, Gargron commented on lib/mastodon/accounts_cli.rb
> +        User.pending.order(:created_at).limit(options[:number]).each(&:approve!)
```suggestion
        User.pending.order(created_at: :asc).limit(options[:number]).each(&:approve!)
```

2023-04-27 17:01 UTC, danielmbrasil commented
Hey @Gargron, I've applied the requested change. Could you review it again? Thanks!

2023-04-30 04:50 UTC, Gargron approved these changes

2023-04-30 04:50 UTC, merged