Add test coverage for `Mastodon::IpBlocksCLI`
mastodon/mastodon pull request #24935
Opened 2023-05-09 18:16 UTC by danielmbrasil

This PR adds tests for the following methods in `Mastodon::IpBlocksCLI`:
- `#add`
- `#remove`
- `#export`

**Code coverage (simplecov): 98.8%**

2023-05-10 16:26 UTC, ClearlyClaire requested changes

2023-05-10 16:26 UTC, ClearlyClaire commented on spec/lib/mastodon/ip_blocks_cli_spec.rb
> +                            )
That formatting is pretty weird, can we avoid that?

2023-05-10 20:12 UTC, nschonni commented
> I'm not sure what the failing check is about.

There is an issue with GitHub Actions today https://www.githubstatus.com/incidents/pr3498h3qkfy

2023-05-11 08:19 UTC, ClearlyClaire approved these changes

2023-05-11 08:19 UTC, merged