over linking
mastodon/mastodon pull request #2502
Opened 2017-04-26 18:12 UTC by masarakki

I found a problem in creating link tag.

Conditions:

- Status contains mentions
- Status contains url with `=@username` (in mentions)

For example,

```
@masarakki

http://example.com/?x=@masarakki
```

In this case,
At first, `encode_and_link_urls` convert url to `<a href="http://example.com/?x=@masarakki" rel="nofollow ...">http://example.com/?x=@masarakki</a>`. 
Then, because of `=@username` **matches to Account::ACCOUNT_RE**, `@masarakki` will be convert to link by `link_mentions`. 
At last, it will be `<a href="http://example.com/?x=<a href="/...">@masarakki</a> rel="nofollow ...">`

Sample: https://friends.nico/@masarakki/2717988

2017-04-26 18:21 UTC, Gargron commented
cc @abcang

2017-04-26 18:24 UTC, masarakki commented
I think simple replacement is dangerous, it is better to use `placeholder` like replacement.

for example, 

html, links = encode_and_link_urls("@masakki Hello, world!,  http://example.com/?x=@masarakki")
# html: "@masarakki Hello, world!, \1", links: ['<a href="http://example.com/?x=@masarakki">http://example.com/?x=@masarakki</a>']
html, links = link_mentions(html, link)
# html: "\2 Hello, world!, \1", links: ['<a href="http://example.com/?x=@masarakki>...</a>' '<a href="/users/1">@masarakki</a>']
....

2017-04-27 03:00 UTC, abcang commented
I think that it is safe to replace it after extracting the target like twitter-text.

2017-05-02 22:17 UTC, Gargron requested changes

2017-05-02 22:17 UTC, Gargron commented on app/lib/formatter.rb
> +  def rewite(text, entities)
Is this meant to be called rewrite?

2017-05-05 17:32 UTC, masarakki commented on app/lib/formatter.rb
> +  def rewite(text, entities)
oh sorry

2017-05-05 17:43 UTC, Gargron approved these changes

2017-05-05 17:48 UTC, merged