Add ability to delete avatar or header picture via the API
mastodon/mastodon pull request #25124
Opened 2023-05-24 16:30 UTC by danielmbrasil

This PR adds a new endpoint to the API which allows deleting the avatar or header picture of an account's profile.

**New endpoint:** `DELETE /api/v1/profile/:image`. Where `image` can be either `avatar` or `header`.
**Scope:** `write:accounts`.

If accepted, should close  #18921.

EDIT:

Documentation PR: mastodon/documentation#1238.

2023-05-24 16:31 UTC, danielmbrasil commented on app/controllers/api/v1/accounts/pictures_controller.rb
> +    raise(Mastodon::InvalidParameterError, 'Picture must be either "avatar" or "header"') unless valid_picture?
Not sure if it's a good way to handle this.

2023-06-29 14:12 UTC, renchap commented
This will need to be added to the documentation I assume?

2023-06-29 14:50 UTC, andypiper commented
Good point @renchap - as a side point, we should add a note to CONTRIBUTING.md that API additions are expected to have a documentation PR to accompanying them.

2023-06-30 14:06 UTC, danielmbrasil commented
> This will need to be added to the documentation I assume?

Working on it 👍🏻 

> we should add a note to CONTRIBUTING.md that API additions are expected to have a documentation PR to accompany them

Good point, I didn't know about it.

2023-06-30 18:19 UTC, danielmbrasil commented
>This will need to be added to the documentation I assume?
> > Working on it 👍🏻

Done.

2023-08-14 14:37 UTC, danielmbrasil commented
Any updates on this? Anything to be added in order to get this reviewed?

2023-08-14 15:28 UTC, ClearlyClaire requested changes
Thanks for your contribution! Apart from my inline comment, the code itself looks good to me!

I'm less sure about the API endpoint names, but I don't really have a better suggestion, so I won't block on it, but if anyone has an opinion on it that would be helpful!

2023-08-14 15:28 UTC, ClearlyClaire commented on app/controllers/api/v1/accounts/pictures_controller.rb
> +    UpdateAccountService.new.call(@account, { @picture => nil, "#{@picture}_remote_url" => '' }, raise_error: true)
The `#{@picture}_remote_url` bit should not be relevant for local users, which the endpoint is for. I'd rather remove it.

```suggestion
    UpdateAccountService.new.call(@account, { @picture => nil }, raise_error: true)
```

2023-08-16 03:26 UTC, trwnh commented
Mastodon API compatible implementations often extend off of `PATCH /api/v1/accounts/update_credentials`, which accepts explicit null values for `avatar` and `header`. This is probably not the best way to do it, but it is the most similar to current practice. If coming up with a new path, I'd propose `/api/v1/profile` as the stub for it. This would result in the following potential methods:

- `DELETE /api/v1/profile/avatar` (and the corresponding `PUT /api/v1/profile/avatar`)
- `DELETE /api/v1/profile/header` (and the corresponding `PUT /api/v1/profile/header`)

2023-08-18 16:23 UTC, ClearlyClaire commented
I think those are good suggestions. @danielmbrasil can you use those endpoint names? (not necessarily supporting `PUT` for now)

2023-08-21 06:44 UTC, ClearlyClaire approved these changes

2023-08-21 06:44 UTC, merged