Improve-follow-recommendations-sql
mastodon/mastodon pull request #25334
Opened 2023-06-07 14:54 UTC by renchap

A server admin reported that this query took 29 hours to run on their instance, using PostgreSQL 14 with up-to-date vacuum & statistics.

After some investigation, we found out that the plan was very wrong and resulted in 300B+ rows being generated in a temporary table.

Switching from a `JOIN` to `NOT EXISTS` fixes the issue and the query is now behaving as expected.

This has been tested on PostgreSQL 12 on a large server, and performs the same as with the `JOIN` on this server.

Fixes #25191

2023-06-08 16:59 UTC, ClearlyClaire requested changes
`follow_recommendations_v02.sql` describes a materialized view, and updating it will require a database migration: see `db/migrate/20210505174616_update_follow_recommendations_to_version_2.rb` for an example.

2023-07-24 11:58 UTC, Gargron commented
Should we rename this view? Would that unstall this PR? I wouldn't mind having the `FollowRecommendation` name be available for a different model.

2023-07-24 12:29 UTC, renchap commented
Yes we could rename it. But that would not solve the issue if one day we have another materialised view that needs to be updated.

The alternative I had in mind was to copy the way it is done in https://github.com/scenic-views/scenic/pull/387 into a helper, and use this helper for the migration.

2023-08-18 15:39 UTC, closed without merging

2023-08-18 15:39 UTC, renchap commented
Closing if favor of #26545