initial piwik support
mastodon/mastodon pull request #2553
Opened 2017-04-27 23:31 UTC by gled-rs

As I saw quite a bunch of instances using google analytics, here is a WIP to add Piwik support to Mastodon ( self hosted / opensource clone of GA ).

It is in production for us on mastodon.host, anonymisation of the data being done by Piwik quite well.

if there's interest let me know as there's TODO:
- a env variable to enable to feature
- a few variable to customize to which piwik setup and which site id.

2017-04-28 01:26 UTC, expenses commented on app/views/layouts/application.html.haml
> +        %img(src="https://analytics.remote-shell.net/piwik.php?idsite=2&rec=1" style="border:0;" alt="")
Why are you using a tracking pixel from [https://analytics.remote-shell.net](analytics.remote-shell.net)?

2017-04-28 02:43 UTC, gled-rs commented on app/views/layouts/application.html.haml
> +        %img(src="https://analytics.remote-shell.net/piwik.php?idsite=2&rec=1" style="border:0;" alt="")
second item of the TODO and in the commit logs ( urls are hardcoded right now ).

As I see some interest, working on dynamic for those parameters !

2017-04-28 02:57 UTC, expenses commented
While I think the default setting to not track users is a good one, supporting piwik is a good idea because it gives admins an easy alternative to GA.

2017-04-28 03:09 UTC, gled-rs commented
Thanks @expenses , I modified the PR so that now PIWIK_DOMAIN is dynamic and not anymore hardcoded. Indeed, I started that as I saw some other instances relying on GA, and to start digging into the code. 

Now I need to learn how to access PIWIK_ENABLED from application.html.haml and find a way to disable the _paq.push from status_containers.jsx if PIWIK_ENABLED != true ( thinking about a boolean in initial_state.json.rabl )

2017-04-28 03:16 UTC, ykzts commented
I do not think there is any reason why I have to include this upstream.

2017-04-28 04:05 UTC, gled-rs commented
@ykzts so you do not see also any reason not not to merge it ? ;) 

Actually, it just makes it easier for admins to setup piwik ( opensource and self hosted ) rather that hacking  google analytics all together in mastodon, and I rather have my data on piwik on a server I control than sending that to GA. It's a incentive for those instances, and it's disabled by default.

2017-04-28 04:14 UTC, ykzts commented
Isn't it contradictory to Mastodon's policy?

> Ethical design: no ads, no tracking

from: https://github.com/tootsuite/mastodon/blob/v1.3.1/config/locales/en.yml#L18

2017-04-28 04:19 UTC, expenses commented
@ykzts Policies like that can only really apply to Mastodon.social, because there is nothing stopping other instances from using tracking.

I get that people don't want to be tracked on mastodon instances, and for most instances, they won't be. But for the instances that _do_ implement tracking, being able to use Piwik easily instead of resorting to GA is a better solution.

2017-04-28 04:26 UTC, ykzts commented
@expenses In that case, I think you should hide the "Ethical design" ([code](https://github.com/tootsuite/mastodon/blob/v1.3.1/app/views/about/show.html.haml#L68-L70)) when `PIWIK_ENABLED` is `true`. It will fool the user.

2017-04-28 04:33 UTC, gled-rs commented
@ykzts concern noted.
Just also want to point you to this ;)

https://github.com/tootsuite/mastodon/blob/master/app/views/about/terms.en.html.haml#L7-L50

2017-04-28 04:35 UTC, nightpool commented on .env.production.sample
> +# PIWIK_ENABLED=true
This can probably be condensed down to two variables, no? if there is a piwik domain, then enable piwik, otherwise don't.

2017-04-28 04:36 UTC, nightpool commented on app/controllers/home_controller.rb
> +  before_action :authenticate_user!, :except => [:piwik] # rubocop:disable Style/HashSyntax
this could alternatively be `%i(piwik)`, which is a little cleaner.

2017-04-28 04:38 UTC, gled-rs commented on .env.production.sample
> +# PIWIK_ENABLED=true
That is correct. I wanted to adopt the same style as above for S3, and it was also useful not to put the piwik domain in the initial_state json, but I have no feelings toward it ;)

I'll change it tomorrow, need to go soon now :/

2017-04-28 04:39 UTC, gled-rs commented on app/controllers/home_controller.rb
> +  before_action :authenticate_user!, :except => [:piwik] # rubocop:disable Style/HashSyntax
Thanks for the tip !

I'm quite new or rusty in RoR/ruby pick one ;)

Correction pushed tomorrow !

2017-04-28 04:40 UTC, nightpool commented on config/piwik.yml
> +# id_site
why are these two things here and in `ENV`? they should be either one place or another but not both, right?

2017-04-28 04:41 UTC, gled-rs commented on config/piwik.yml
> +# id_site
me forgetting to clean the mess left by piwik gem ;)

By the way, would you prefer using the piwik gem or the simple solution implemented at the moment ?

2017-04-28 04:49 UTC, expenses commented
@gled-rs It's also worth noting that the Private Policy [is just copy-pasted at the moment](https://mastodon.social/@Gargron/3482305).

2017-04-28 04:51 UTC, gled-rs commented
I know @expenses , that is going to be one of the next subjects, putting the terms in a setting like the instance description ;)

2017-04-28 16:14 UTC, mjankowski requested changes
That's a lot of code to add for something which is optional, and maybe not used in that many instances?

Doing any sort of tracking or analytics strikes me as something best left to each instance, rather than mandated by the core app?

2017-04-28 18:04 UTC, gled-rs commented
72 lines of code is a lot ? ;) 

Anyway, there's around 5-6% of the instances out there today with some sort of GA deployed, just looked at the scrapping results.

2017-05-04 02:41 UTC, Gargron commented
I'm inclined to say that if you want to add tracking, you can modify the code downstream, but it doesn't need to be in the main repository.

2017-05-04 02:41 UTC, closed without merging