Add toast with option to open post after publishing in web UI
mastodon/mastodon pull request #25564
Opened 2023-06-23 19:22 UTC by Gargron

2023-06-26 09:05 UTC, ClearlyClaire commented
The code looks fine, and I thought I liked the idea, which can help with at least the onboarding page, but upon testing:
- it does feel distracting, especially on mobile where this takes a significant portion of the screen
- on a typical 16:9 screen on the default single-column view, the toast will appear pretty far from anything, thus might not get noticed and/or might need significant eye movement

![image](https://github.com/mastodon/mastodon/assets/384364/b0b2002d-d6b5-43fb-b150-21eef5c90f7a)

I'm also not sure the visual redesign is necessary and I'm not entirely convinced with the way it looks with regards to transparency and blur:
![image](https://github.com/mastodon/mastodon/assets/384364/d207064c-f8c4-40bb-9ec1-185ac93b194d)

2023-06-26 09:33 UTC, ClearlyClaire requested changes
There are inconsistent uses of `inset-inline-start` and `left` that will cause issues on RTL layouts.

2023-06-26 09:33 UTC, ClearlyClaire commented on app/javascript/styles/mastodon/components.scss
> +    left: 1rem;
This isn't consistent with `inset-inline-start: -100%` and will not override it.

2023-06-26 09:33 UTC, ClearlyClaire commented on app/javascript/styles/mastodon/components.scss
> +  inset-inline-start: -100%;
This is not consistent with `left: 1rem` at https://github.com/mastodon/mastodon/pull/25564/files#diff-edd345ee45838ecdc48d8b64ba5f0d4475300e2cc36e696a937fe012a6e025caR9044 and will not get overridden on RTL layouts. Furthermore, this is not consistent with `left: 0` at https://github.com/mastodon/mastodon/pull/25564/files#diff-edd345ee45838ecdc48d8b64ba5f0d4475300e2cc36e696a937fe012a6e025caR9017 and will not be positioned properly on RTL layouts.

2023-06-26 09:33 UTC, ClearlyClaire commented on app/javascript/styles/mastodon/components.scss
> +  left: 0;
This is not consistent with `inset-inline-start` a few lines later.

2023-06-30 23:31 UTC, Gargron commented
Made the background of the toast darker.

2023-07-08 18:01 UTC, merged