First pass at multi-database for read replica using Rails native adapter
mastodon/mastodon pull request #25693
Opened 2023-07-03 21:24 UTC by krainboltgreene

There's a desire to implement read replica usage. For mastodon instances without replicas this should just talk to the main database *as* a replica. More changes to come.

2023-07-03 22:37 UTC, Gargron approved these changes

2023-07-03 22:43 UTC, Gargron requested changes

2023-07-03 22:43 UTC, Gargron commented on app/workers/feed_insert_worker.rb
> +    ActiveRecord.connects_to(role: :primary) do
I think the syntax is `ActiveRecord::Base.connected_to`

2023-07-08 10:50 UTC, emilweth requested changes

2023-07-08 10:50 UTC, emilweth commented on config/database.yml
> +    username: <%= ENV['DB_REPLICA_NAME'] ||ENV['DB_USER'] || 'mastodon' %>
```suggestion
    username: <%= ENV['DB_REPLICA_USER'] ||ENV['DB_USER'] || 'mastodon' %>
```

2023-07-08 17:40 UTC, Gargron approved these changes

2023-07-08 17:45 UTC, merged