Hebrew translation
mastodon/mastodon pull request #2573
Opened 2017-04-28 08:25 UTC by seefood

Includes translation strings and small improvements to the RTL detection functions

2017-04-28 08:38 UTC, ykzts commented on app/helpers/stream_entries_helper.rb
> +    text.gsub!( /@[0-9A-Za-z_]+/, '' )
I think indent is necessary.

2017-04-28 08:39 UTC, ykzts commented on app/assets/javascripts/components/locales/he.jsx
> + */
I do not think I need this commented out message.

2017-04-28 08:49 UTC, ykzts commented on config/locales/devise.he.yml
> +      already_authenticated: &rlm;חשבון זה כבר מחובר.
When including "`&`" in YAML please surround it with single quotes like "`'&rlm;חשבון זה כבר מחובר.'`".

2017-04-28 17:10 UTC, seefood commented on app/assets/javascripts/components/locales/he.jsx
> + */
it helped me when I compared to the English string file to keep the line count so I can more easily detect changes that need updates to the translation file. Is that a problem?

2017-04-28 17:10 UTC, seefood commented on app/helpers/stream_entries_helper.rb
> +    text.gsub!( /@[0-9A-Za-z_]+/, '' )
true. fixing.

2017-04-28 17:10 UTC, seefood commented on config/locales/devise.he.yml
> +      already_authenticated: &rlm;חשבון זה כבר מחובר.
I'll go over those too.

2017-04-28 17:18 UTC, seefood commented
Question, should I rebase this on latest master or just the latest stable tag?

2017-04-28 17:23 UTC, seefood commented on config/locales/devise.he.yml
> +      already_authenticated: &rlm;חשבון זה כבר מחובר.
btw, some had %{references} in the string, so I used double quotes, as I've not checked what library is parsing the strings. If you prefer single quotes everywhere, I'll fix that.

2017-04-29 02:26 UTC, shimomaehayato commented on app/assets/javascripts/components/locales/he.jsx
> + */
Certainly. However, looking at other languages, either it does not exist or is translated. It would be better to combine.

2017-04-29 02:27 UTC, ykzts commented on app/assets/javascripts/components/locales/he.jsx
> + */
Certainly. However, looking at other languages, either it does not exist or is translated. It would be better to combine.

2017-04-29 02:30 UTC, ykzts commented
You should rebase to master if you can.

2017-04-29 07:50 UTC, seefood commented
Fixed the requested changes.

2017-04-29 09:15 UTC, ashfurrow approved these changes
Cool! I don't know Hebrew but from a code perspective this looks good.

2017-04-29 09:15 UTC, ashfurrow commented on app/assets/javascripts/components/rtl.jsx
> +  const justtext = text.gsub(/@[0-9A-Za-z_]+/, '')
Nice!

2017-04-29 12:48 UTC, happycoloredbanana commented on app/assets/javascripts/components/locales/he.jsx
> +  "account.mention": "פניה אל @{name}",
"אזכור של" would be better

2017-04-29 12:55 UTC, happycoloredbanana commented on app/assets/javascripts/components/locales/he.jsx
> +  "account.unblock": "הסרת חסימה מעם @{name}",
"מעם"?

2017-04-29 12:58 UTC, seefood commented on app/assets/javascripts/components/locales/he.jsx
> +  "account.mention": "פניה אל @{name}",
in the next round, maybe.

2017-04-29 13:46 UTC, seefood commented
Yay! Travis is happy at last!
Ready to merge...

2017-04-30 13:37 UTC, mjankowski requested changes

2017-04-30 13:37 UTC, mjankowski commented on app/helpers/stream_entries_helper.rb
> +      # Remove mentions before counting characters to decide RTL ratio
Can you add spec coverage showing what this change does?

2017-04-30 14:52 UTC, seefood commented on app/helpers/stream_entries_helper.rb
> +      # Remove mentions before counting characters to decide RTL ratio
Probably, but I don't have time to learn the lingo at the moment. Can I promise to add that at a later PR? :)

2017-04-30 15:14 UTC, mjankowski commented on app/helpers/stream_entries_helper.rb
> +      # Remove mentions before counting characters to decide RTL ratio
You can promise basically anything.

2017-05-01 06:14 UTC, seefood commented on app/helpers/stream_entries_helper.rb
> +      # Remove mentions before counting characters to decide RTL ratio
ok, I'll drop it from the PR. we'll use it on our instance till I find the time to study this.

2017-05-02 08:45 UTC, seefood commented
I CAN HAZ MERJBURGER?

2017-05-02 12:54 UTC, mjankowski approved these changes

2017-05-02 12:54 UTC, merged

2017-05-02 14:46 UTC, seefood commented
Thanks a bundle!