Allow account_warnings.account_id to be null
mastodon/mastodon pull request #25900
Opened 2023-07-11 03:17 UTC by xrobau

Fixes #25899

If the reporting account is deleted, the account_id is nulled by the constraint. However, the view wasn't able to understand that.

2023-07-26 12:52 UTC, ClearlyClaire requested changes

2023-07-26 12:52 UTC, ClearlyClaire commented on app/views/admin/account_warnings/_account_warning.html.haml
> +        = t(account_warning.action, scope: 'admin.strikes.actions', name: content_tag(:span, account_warning.account ? account_warning.account.username : 'Unknown Account (Deleted?)', class: 'usernam
Hi! Thank you for your contribution!

You should not use a harcoded string, but a translatable string instead (those are used with `t('translation_id')` and defined in `config/locales/en.yml`

2023-09-18 14:52 UTC, ClearlyClaire commented on app/views/admin/account_warnings/_account_warning.html.haml
> +        = t(account_warning.action, scope: 'admin.strikes.actions', name: content_tag(:span, account_warning.account ? account_warning.account.username : 'Unknown Account (Deleted?)', class: 'usernam
Hi! I ended up taking over and fixing it myself.

2023-09-18 14:52 UTC, ClearlyClaire approved these changes

2023-09-18 15:40 UTC, renchap approved these changes

2023-09-18 15:41 UTC, merged