Column Flexible Width, and Dropdown Menu Fix
mastodon/mastodon pull request #2596
Opened 2017-04-28 17:59 UTC by YaQ00

Account dropdown menu 140px => 25vw, 50vw, 90vw (responsive)

Width => drawer 20% (max-width 400px), column 80% / 3 (max-width 800px)

Width 2560px over => height 100vh, margin 0

Narrow column, smallest menu => Wide & modern column!

Sample Image (https://twitter.com/8_9_00/status/858012770947670016)

2017-04-30 12:27 UTC, mjankowski submitted a review, later dismissed
Can you add a better description of what's changing here, and move your screenshots onto this PR?

2017-05-01 21:07 UTC, stephenburgess8 requested changes
Overall I like the fact that you're making this responsive and allowing the columns to grow. If you could outline what all the changes you're making are for in a list, remove or comment the `!important`, avoid the use of the universal selector, and add some screenshots that would be helpful. Best.

2017-05-01 21:07 UTC, stephenburgess8 commented on app/assets/stylesheets/components.scss
> +    margin: 0;
Before only `margin-top` was applied but now we're applying margin to all sides. If you don't need to apply margin to all sides, you should avoid doing so.

2017-05-07 01:56 UTC, YaQ00 commented on app/assets/stylesheets/components.scss
> +    }
Thank you for your proposal. I take up all suggest.

2017-05-07 01:56 UTC, YaQ00 commented
take up all suggest.

2017-05-08 14:20 UTC, stephenburgess8 commented
Hi - I like the flexible column width idea.

I don't like the idea that the dropdowns will always be so wide. The current dropdowns are small at first, then expand with the content to fill up the column. Unless there text in the dropdowns is long, the width of the dropdown is still small. There is no need to make the dropdown so wide unless the content is also wide. Keep in mind that I will not be the one approving the pull request.

The new master branch now has columns that are centered on the page. It may help to see screenshots with the new style.

2017-05-08 16:01 UTC, YaQ00 commented
Thx for the reply, stephenburgess8.

But you forget about the long text such as CJK area. As a CJK user, I thought it was very hard to see.
I also think that even long texts will be in good condition if the change is made. It will have good touch device condition too.

Some people do not need the ID of the account menu, but I think that redundancy should not be eliminated.

What are your thoughts on my proposal? Tell me your idea.
![d](https://cloud.githubusercontent.com/assets/15644947/25809532/3aebf42a-3448-11e7-89ad-ca8fc89130cf.PNG)

2017-05-08 16:32 UTC, YaQ00 commented
How do you think? @Gargron @mjankowski @ykzts

2017-05-10 15:02 UTC, beatrix-bitrot approved these changes
as far as I can tell all reviewers' suggestions have been implemented

there are no merge conflicts

and this is an important usability fix

approving

2017-05-13 19:31 UTC, stephenburgess8 commented
Hi - 
I experienced a bug when my screen was less than 1024. The rest of the columns fall out of viewport.

This PR makes a stylistic change from going from fixed column widths to one with variable column widths.

Currently, the dropdowns expand only when there's additional content in them. In your version here, they are always as wide as the column. I like the way it is currently handled.

I hope I was helpful responding to your PR. Best -S

2017-05-17 00:58 UTC, Gargron commented
I am afraid we are not looking to make the columns flexible width. The general look and feel of the web UI is already set in stone. Thank you for your effort though!

2017-05-17 13:07 UTC, closed without merging

2018-04-26 13:17 UTC, STPKITT commented
> I am afraid we are not looking to make the columns flexible width. The general look and feel of the web UI is already set in stone

Are you seriously? This is ridicolous! There's so much space on many types of displays, yet Mastodon users have to scroll down every 3 or 4 toots (on a Full HD display with default zoom settings). Pretty much unusable the way it is currently.