Update of oc.jsx
mastodon/mastodon pull request #2597
Opened 2017-04-28 18:14 UTC by Quent-in

Now similar to the English one. I'll update oc.yml within a week.

2017-04-28 19:10 UTC, Quent-in commented
I don't really get why the Travis Cl build failed =/

2017-04-28 21:14 UTC, mcmarto commented
The CI build failed because a number of lines in oc.jsx are missing the trailing comma.

2017-04-29 10:04 UTC, Quent-in commented
I'm sorry but I don't know what it is =/

2017-04-29 10:20 UTC, ashfurrow requested changes
I think that's the only change needed to get Travis to work.

2017-04-29 10:20 UTC, ashfurrow commented on app/assets/javascripts/components/locales/oc.jsx
> +  "column.community": "Fil public local"
This line needs a comma `,` at the end.

2017-04-29 11:00 UTC, mcmarto commented on app/assets/javascripts/components/locales/oc.jsx
> +  "column.community": "Fil public local"
Lines 20, 29 (shown above) and 167 are all missing the comma at the end of the line.

2017-04-29 17:11 UTC, Quent-in commented
It should be okay now :)

2017-04-30 14:03 UTC, Quent-in commented on app/assets/javascripts/components/locales/oc.jsx
> +  "column.community": "Fil public local"
I changed it, I hope it's okay now.

2017-05-03 09:53 UTC, closed without merging