Master
mastodon/mastodon pull request #2641
Opened 2017-04-30 09:39 UTC by saggel

I submit some minor editing on the english confirmation instructions -
mostly as a test before I submit my Greek translation!

2017-04-30 12:13 UTC, mjankowski requested changes

2017-04-30 12:13 UTC, mjankowski commented on app/views/user_mailer/password_change.en.html.erb
> +<p>We're contacting you to notify you that your password on <%= @instance %> has been changed.</p>
Can you put this change in a separate PR?

2017-04-30 12:13 UTC, mjankowski commented on config/application.rb
> +	  :el,
alignment?

2017-04-30 12:13 UTC, mjankowski commented on config/locales/doorkeeper.el.yml
> +el:
did anything in this file change from en?

2017-04-30 12:13 UTC, mjankowski commented on config/locales/el.yml
> +el:
did anything in this file change from en?

2017-04-30 12:27 UTC, saggel commented on config/locales/el.yml
> +el:
The Greek code is el - did I do something wrong?

2017-04-30 12:27 UTC, saggel commented on config/locales/doorkeeper.el.yml
> +el:
The Greek code is el - did I do something wrong?

2017-04-30 12:27 UTC, saggel commented on config/application.rb
> +	  :el,
I can fix this on the next pull where I'll complete the translation!

2017-04-30 12:28 UTC, mjankowski commented on config/locales/el.yml
> +el:
It looks like nothing change in the file...

The `en` changed to `el`, which is correct ... but it looks like nothing was translated?

2017-04-30 12:28 UTC, saggel commented on app/views/user_mailer/password_change.en.html.erb
> +<p>We're contacting you to notify you that your password on <%= @instance %> has been changed.</p>
If you tell me how :-)

2017-04-30 12:30 UTC, saggel commented
If you think I should just do the pull again right from the beginning please do let me know! It was my first attempt!

2017-04-30 12:35 UTC, saggel commented on config/locales/el.yml
> +el:
Yes that's true - not done yet, but I thought it needs to be on the folder for the locale to work - the translation is done on 85% and I wanted to try it on an instance before completing it!

2017-04-30 12:43 UTC, mjankowski commented
Congrats on your first PR and thanks for the help! ... 

- The formatting changes to the mailers look good
- I'm not sure the change which adds `@instance` to the password change mailer will work, because I don't think that variable is in place in that mailer...
- I think the translations will just fall back to the `en` versions if some are missing

I think my preference would be to do one PR for the mailer changes, and another for all of the added `el` locale additions (including el mailers).

If you're working purely through the GH website and not a local copy, I can help create the mailer PR separately, and then we can update this one to only include the el changes.

2017-04-30 12:47 UTC, saggel commented
Awesome - let me know what I need to do - I use the github desktop app - but happy to do whatever is easier or faster for you!

2017-05-13 09:50 UTC, yookoala commented
Your works is based on an older version of Mastodon. Can you please rebase your work on the latest master branch? Or at least merge with the latest Mastodon's master?

2017-07-12 22:20 UTC, Gargron commented
Closing for inactivity

2017-07-12 22:20 UTC, closed without merging