Update mastodon.jsx
mastodon/mastodon pull request #2667
Opened 2017-04-30 21:31 UTC by diomed

adds Croatian [I forgot before]

2017-05-01 01:19 UTC, ykzts commented
You need to add `...hr` to [line 88](https://github.com/tootsuite/mastodon/pull/2667/files#diff-3be90834b38abeceee25882fc50dbdcfR88).

2017-05-01 13:34 UTC, Quent-in commented
What function has this file? It's lacking OC for occitan too, or maybe I haven't translated related files so far.

2017-05-01 15:08 UTC, diomed commented
@Quent-in I've just added occitan as well. 
This is apparently needed for translation to be shown in front end interface.
so, pretty big deal.

2017-05-01 15:27 UTC, Quent-in commented
Oh I see!
Line 60, it should be oc, not no ;)
Thank you very much for adding occitan too!

2017-05-06 05:40 UTC, ykzts requested changes
Can you resolve conflicts?

2017-05-06 09:06 UTC, Gargron approved these changes

2017-05-06 09:22 UTC, diomed commented
@ykzts care to tell me what to fix? coz I'm not sure.

2017-05-06 09:26 UTC, ykzts commented
@diomed I think that https://help.github.com/articles/resolving-a-merge-conflict-on-github/ will be helpful.

2017-05-06 09:30 UTC, ykzts commented on app/assets/javascripts/components/containers/mastodon.jsx
> +import oc from 'react-intl/locale-data/oc';
`react-intl/locale-data/oc` can not be found. React Intl seems not to supported to "oc".

2017-05-06 10:40 UTC, diomed commented on app/assets/javascripts/components/containers/mastodon.jsx
> +import oc from 'react-intl/locale-data/oc';
but all files are there!?!

2017-05-06 11:03 UTC, ykzts commented on app/assets/javascripts/components/containers/mastodon.jsx
> +import oc from 'react-intl/locale-data/oc';
I seen [`locale-data` directory](https://unpkg.com/react-intl@2.1.5/locale-data/) for [`react-intl`](https://github.com/yahoo/react-intl). `oc.js` does not seem to exist.

2017-05-06 12:01 UTC, diomed commented on app/assets/javascripts/components/containers/mastodon.jsx
> +import oc from 'react-intl/locale-data/oc';
is this repo inclued somewhere as part of mastodon?
I mean - ok, lets say I include it and it doesn't exist, wouldn't it just fallback to smth?
if this is part of mastodon, can u locate it, I'm sure @Quent-in can contribute.

2017-05-06 12:07 UTC, ykzts commented on app/assets/javascripts/components/containers/mastodon.jsx
> +import oc from 'react-intl/locale-data/oc';
This is due to external package. It is not included in this repository.

2017-05-06 14:55 UTC, yookoala commented
@Quent-in Sadly, [react-intl](https://github.com/yahoo/react-intl) does not provide default locale data for Occitan. `'react-intl/locale-data/oc'` simply do not exists and hence cannot be imported. You'd need to implement you own locale data with their [locale data API](https://github.com/yahoo/react-intl/wiki/API#locale-data-apis).

2017-05-06 15:07 UTC, yookoala commented
@Quent-in A simplified version of the 'en' locale data looks like this. You can create your own locale data in a similar structure. Then you may import and add with `addLocaleData`.

```javascript
[
  {
    locale: "en",
    pluralRuleFunction: function(e, a) {
      var n = String(e).split("."),
        l = !n[1],
        o = Number(n[0]) == e,
        t = o && n[0].slice(-1),
        r = o && n[0].slice(-2);
      return a ? 1 == t && 11 != r ? "one" : 2 == t && 12 != r ? "two" : 3 == t && 13 != r ? "few" : "other" : 1 == e && l ? "one" : "other"
    },
    fields: {
      year: {
        displayName: "year",
        relative: {
          0: "this year",
          1: "next year",
          "-1": "last year"
        },
        relativeTime: {
          future: {
            one: "in {0} year",
            other: "in {0} years"
          },
          past: {
            one: "{0} year ago",
            other: "{0} years ago"
          }
        }
      },
      month: {
        displayName: "month",
        relative: {
          0: "this month",
          1: "next month",
          "-1": "last month"
        },
        relativeTime: {
          future: {
            one: "in {0} month",
            other: "in {0} months"
          },
          past: {
            one: "{0} month ago",
            other: "{0} months ago"
          }
        }
      },
      day: {
        displayName: "day",
        relative: {
          0: "today",
          1: "tomorrow",
          "-1": "yesterday"
        },
        relativeTime: {
          future: {
            one: "in {0} day",
            other: "in {0} days"
          },
          past: {
            one: "{0} day ago",
            other: "{0} days ago"
          }
        }
      },
      hour: {
        displayName: "hour",
        relativeTime: {
          future: {
            one: "in {0} hour",
            other: "in {0} hours"
          },
          past: {
            one: "{0} hour ago",
            other: "{0} hours ago"
          }
        }
      },
      minute: {
        displayName: "minute",
        relativeTime: {
          future: {
            one: "in {0} minute",
            other: "in {0} minutes"
          },
          past: {
            one: "{0} minute ago",
            other: "{0} minutes ago"
          }
        }
      },
      second: {
        displayName: "second",
        relative: {
          0: "now"
        },
        relativeTime: {
          future: {
            one: "in {0} second",
            other: "in {0} seconds"
          },
          past: {
            one: "{0} second ago",
            other: "{0} seconds ago"
          }
        }
      }
    }
  }
]
```

2017-05-06 15:28 UTC, Quent-in commented
I'll translate it as soon as possible.
Can I send it somewhere too so it will be included in other projects using this " react-intl" thing?
Best regards

2017-05-06 15:30 UTC, closed without merging

2017-05-06 15:35 UTC, diomed commented
@Gargron why was this approved, then closed?
can u reopen? if all it takes is to remove oc, I'll remove it, 
so Croatian can be merged, and then @Quent-in can make a new patch for oc

2017-05-06 15:45 UTC, yookoala commented
@diomed: mastodon.js has been moved to another folder. The change in this PR is no longer valid. I have done the exact same change in #2844. Since it is included, this PR is consider resolved and hence closed.

2017-05-06 15:50 UTC, yookoala commented
@Quent-in: The react-intl is quite complicated. It took me some time to figure out that source data is not in any javascript files. It is extracted from data in [CLDR - Unicode Common Locale Data Repository](http://cldr.unicode.org/). So if you really want to backport your translations, you'd need to read their [New Developers guide](http://cldr.unicode.org/development/new-cldr-developers).

It is not a lot more complicated than a Github pull request, thou.

2017-05-06 15:53 UTC, Quent-in commented
Hello again!
I've just finished!
Here it is, I'll have a look at the link you put tonight, many thanks!

`[
  {
    locale: "oc",
    pluralRuleFunction: function(e, a) {
      var n = String(e).split("."),
        l = !n[1],
        o = Number(n[0]) == e,
        t = o && n[0].slice(-1),
        r = o && n[0].slice(-2);
      return a ? 1 == t && 11 != r ? "un" : 2 == t && 12 != r ? "dos" : 3 == t && 13 != r ? "pauc" : "autre" : 1 == e && l ? "un" : "autre"
    },
    fields: {
      year: {
        displayName: "an",
        relative: {
          0: "ongan",
          1: "l'an que ven",
          "-1": "l'an passat"
        },
        relativeTime: {
          future: {
            one: "dins {0} an",
            other: "dins {0} ans"
          },
          past: {
            one: "fa {0} an",
            other: "fa {0} ans"
          }
        }
      },
      month: {
        displayName: "mes",
        relative: {
          0: "aqueste mes",
          1: "lo mes que ven",
          "-1": "lo mes passat"
        },
        relativeTime: {
          future: {
            one: "dins {0} mes",
            other: "dins {0} meses"
          },
          past: {
            one: "fa {0} mes",
            other: "fa {0} meses"
          }
        }
      },
      day: {
        displayName: "jorn",
        relative: {
          0: "uèi",
          1: "deman",
          "-1": "ièr"
        },
        relativeTime: {
          future: {
            one: "dins {0} jorn",
            other: "dins {0} jorns"
          },
          past: {
            one: "fa {0} jorn",
            other: "fa {0} jorns"
          }
        }
      },
      hour: {
        displayName: "ora",
        relativeTime: {
          future: {
            one: "dins {0} ora",
            other: "dins {0} oras"
          },
          past: {
            one: "fa {0} ora",
            other: "fa {0} oras"
          }
        }
      },
      minute: {
        displayName: "minuta",
        relativeTime: {
          future: {
            one: "dins {0} minuta",
            other: "dins {0} minutas"
          },
          past: {
            one: "fa {0} minuta",
            other: "fa {0} minutas"
          }
        }
      },
      second: {
        displayName: "segonda",
        relative: {
          0: "ara"
        },
        relativeTime: {
          future: {
            one: "dins {0} segonda",
            other: "dins {0} segondas"
          },
          past: {
            one: "fa {0} segonda",
            other: "fa {0} segondas"
          }
        }
      }
    }
  }
]`

2017-05-06 16:22 UTC, yookoala commented
@Quent-in: I'm working on a PR with your translations. Stay tuned.

2017-05-06 18:26 UTC, Quent-in commented
Many thanks @yookoala !
I'm proud to spread my language, thank you for helping me.

2017-05-09 10:41 UTC, yookoala commented
@Quent-in: Upon re-reading your translation, I think the locale data could be wrongly done.

Please take a look and the [pluralRuleFunction here](https://github.com/tootsuite/mastodon/blob/e4b84c7ba5bc4fa92f97aa8853d07931e460f87a/app/javascript/mastodon/locales/locale-data/oc.js#L6,L13). I think the usage of the pluralRuleFunction is to provide the correct key to search for plural translation.

If the field to translate is "year" and the plural function returns "one", then the program will look for "one" in the translations that structure like this:
```
future: {
     one: "dins {0} an",
     other: "dins {0} ans"
},
```

The purpose is to find the correct plural form for a given noun. If it were English, a singular item ("one") should have a string without "s", while a plural item ("other") should have a string with "s". In Chinese, there is no separated plural form so the function always returns "other".

Now. Back to your case.

Your plural function seems to return locale strings instead of "one" or "other". But your translations are still using "one", "other" and key. It could run into problem.

My advice:
1. If your language has no plural form, the plural function should just return "other".
2. If your language has 1 plural form, the plural function should return "one" or "other. No need to translate.
3. If your language has more than 1 plural form, you should have a different key for each plural form cases (preferable in English noun like "one", "two", "three", "four"). And you should have the exact same set of keys in all your translations below.

If you're not sure about git, you can give me an update version of the JS here. I can commit them for you :-)