Add infinite scrolling for search results in web UI
mastodon/mastodon pull request #26784
Opened 2023-09-03 22:30 UTC by Gargron

First of all, this resolves the issue where if you selected the quick action "Profiles matching..." or "Posts matching..." the results screen would show the "All" tab as selected. Now it will show the correct tab, and clicking *other* tabs will re-run the search query to display the appropriate results (vs showing a blank screen as previously). I've increased the number of results per page from 5 to 10, except now I'm also doing peeking (querying for 11 and using the extra item to determine if there's a next page or not). When a specific search type is selected, we now use infinite scroll. On the "all" page, this is not possible, and "Load more" buttons are displayed under each section as before. Clicking one of them will switch you to the tab and enable infinite scroll.

2023-09-04 00:42 UTC, ykzts approved these changes

2023-09-04 08:47 UTC, ClearlyClaire requested changes

2023-09-04 08:47 UTC, ClearlyClaire commented on app/javascript/mastodon/features/explore/results.jsx
> +    }
In conjunction with `getDerivedStateFromProps`, it means it's not possible to switch from the “All” tab, as `submittedType` will be unset, and `type` will revert to `all`.

2023-09-05 01:20 UTC, Gargron commented
I've updated it once more. The "all" tab will now show at most 4 items of each type, with "See all" above each category. This is so you can more easily scroll between categories. The tab design changed as well.

2023-09-05 09:52 UTC, ClearlyClaire requested changes
This requires `yarn i18n:extract`. Otherwise I'm a bit split about the redesign, but overall it seems good.

2023-09-05 21:54 UTC, merged