feat(character-count): Do not embed dynamic value in sentence
mastodon/mastodon pull request #2685
Opened 2017-05-01 14:04 UTC by stephenburgess8

Restructure label to not embed dynamic value in sentence. This allows for grammatical correctness whether the number is one or not one.

#2678

<img width="432" alt="screen shot 2017-05-01 at 10 03 37 am" src="https://cloud.githubusercontent.com/assets/6003351/25581384/776cf0dc-2e55-11e7-8e26-ed11a8eecf45.png">

2017-05-01 17:09 UTC, stephenburgess8 commented
Feel free to close if you would prefer this not be changed.

2017-05-02 18:58 UTC, Gargron requested changes

2017-05-02 18:58 UTC, Gargron commented on config/locales/simple_form.en.yml
> +        display_name: 'Characters left: %{counter}'
You know you can do something like:

```yml
display_name:
  one: 1 character left
  other: "%{count} characters left"
```

You just have to rename counter to count.

2017-05-13 14:39 UTC, stephenburgess8 commented
Thanks for your note on this. https://webtranslateit.com/docs/file_formats/yaml/

I've tested this view in all the languages that I've changed here. I've noticed two things which looks like either cruft or something is wrong:

For Brazilian Portuguese, the profile edit view isn't being translated. (this is happening before the changes I made)
The Turkish `devise.tr.yml` file uses these translations, but these aren't translated in that part of the code AFAICT. That should possibly be deleted from the Turkish translation file. Should I open an issue for either of those? I don't use them, I just noticed it when testing.

2017-05-13 15:06 UTC, Gargron approved these changes

2017-05-13 15:13 UTC, merged