Update zh-CN translations.
mastodon/mastodon pull request #2699
Opened 2017-05-02 01:08 UTC by KenOokamiHoro

2017-05-02 01:28 UTC, PeterCxy approved these changes
Translations are generally acceptable.

2017-05-02 15:25 UTC, Artoria2e5 requested changes
Mostly good. Awoo.

2017-05-02 15:25 UTC, Artoria2e5 commented on config/locales/zh-CN.yml
> +      one: In the process of soft-blocking followers from one domain...
Remove the `one` line as Chinese won't use it anyway.

2017-05-02 15:25 UTC, Artoria2e5 commented on config/locales/zh-CN.yml
> +    closed_registrations: 这个实例暂时（或者永久）不开放注册 _(:3」∠)_
I do not like the idea of "temporarily (or permanently)". How about "目前" (currently)? Let's not try to probe into the future...

2017-05-02 15:25 UTC, Artoria2e5 commented on app/views/user_mailer/reset_password_instructions.zh-cn.html.erb
> +<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>
Change my password -> 更改密码

2017-05-02 15:25 UTC, Artoria2e5 commented on app/views/user_mailer/confirmation_instructions.zh-cn.text.erb
> +<%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %>
Confirm my account -> 确认帐号

2017-05-02 15:25 UTC, Artoria2e5 commented on app/views/user_mailer/confirmation_instructions.zh-cn.text.erb
> +别忘了看看 <%= link_to 'terms and conditions', terms_url %>。
missing translation, 使用条款

2017-05-02 15:29 UTC, Artoria2e5 commented on config/locales/doorkeeper.zh-CN.yml
> -
Ahem..

2017-05-02 15:41 UTC, KenOokamiHoro commented
😌…… & @Artoria2e5 😅   

2017-05-02 16:01 UTC, Artoria2e5 commented on app/views/user_mailer/reset_password_instructions.zh-cn.html.erb
> +<p>有人（可能是你）请求更改你 Mastodon 账户的密码。如果是你的话，请点击下面的链接：</p>
What about "hopefully you"（但愿是你）?

2017-05-03 04:44 UTC, KenOokamiHoro reviewed
awoo~

2017-05-03 05:41 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-CN.json
> +  // intentional departure from https://github.com/tootsuite/mastodon/blob/f864fee1/config/locales/zh-CN.yml#L126:
Why the change to json? The zh-CN file used to have some react magic inherited from zh-HK that has to be run as actual executable code. And json does not play well with comments.

2017-05-03 05:41 UTC, Artoria2e5 commented on app/views/user_mailer/reset_password_instructions.zh-cn.html.erb
> +<p>有人（但愿是你 ~ ）请求更改你 Mastodon 账户的密码。如果是你的话，请点击下面的链接：</p>
Please, no tildes, no ASCII tildes, and no spaces around tildes or before a closing parenthesis.

2017-05-03 10:16 UTC, Gargron requested changes

2017-05-03 10:16 UTC, Gargron commented on app/javascript/mastodon/locales/zh-CN.json
> +  "video_player.video_error": "视频无法播放啦……",
This is a JSON file now, so no trailing comma, and nothing after the closing }

2017-05-03 10:39 UTC, Gargron requested changes

2017-05-03 10:39 UTC, Gargron commented on config/locales/doorkeeper.zh-CN.yml
> +     scopes:
There seems to be some sort of YML syntax error in this file, but I am not sure which exactly.

`I18n::InvalidLocaleData: can not load translations from /home/travis/build/tootsuite/mastodon/config/locales/doorkeeper.zh-CN.yml: #<Psych::SyntaxError: (/home/travis/build/tootsuite/mastodon/config/locales/doorkeeper.zh-CN.yml): did not find expected key while parsing a block mapping at line 19 column 5>`

2017-05-03 10:46 UTC, KenOokamiHoro commented on config/locales/doorkeeper.zh-CN.yml
> +     scopes:
unexpected indent ? 😂

2017-05-03 11:01 UTC, Gargron commented
Looks like the last failing part is these unused keys:

```
Unused keys (3) | i18n-tasks v0.9.13

+--------+------------------------------+--------------------------------+

| Locale | Key                          | Value                          |

+--------+------------------------------+--------------------------------+

| zh-CN  | media_attachments            |                                |

| zh-CN  | validations.images_and_video | 已经有照片的嘟文里没法加入视频 |

| zh-CN  | validations.too_many         | 文件太多（>4）                 |

+--------+------------------------------+--------------------------------+
```

2017-05-03 12:03 UTC, Gargron approved these changes

2017-05-03 12:03 UTC, merged

2017-06-02 14:01 UTC, Artoria2e5 commented
Hmm, I will probably change all the 账 to 帐 -- Mastodon is not a banking app after all.