Added japanese version of terms of service and privacy policy
mastodon/mastodon pull request #2703
Opened 2017-05-02 02:45 UTC by gentarok

Added japanese version of terms of service and privacy policy

2017-05-02 13:06 UTC, akihikodaki requested changes

2017-05-02 13:06 UTC, akihikodaki commented on app/views/about/terms.ja.html.haml
> +  %p この文章のライセンスはCC-BY-SAです。このページは2013年5月31日が最終更新です。
I suggest to update the date, as the Norwegian version does.
https://github.com/tootsuite/mastodon/commit/e1264bbd92718cd6d78bed8c2d1ad9cb96384fea#diff-f38cf3cfcef9d50514d9021e86477a4cR71

2017-05-02 16:33 UTC, takahashim commented on app/views/about/terms.ja.html.haml
> +  %p ライバシーポリシーを変更する場合は、このページへ変更内容を掲載します。
`ライバシーポリシー` should be `プライバシーポリシー`.

2017-05-02 16:36 UTC, takahashim commented on app/views/about/terms.ja.html.haml
> +  %p ときどき、このサービスの方針にもとづいてこのサイトや第三者のサービスを提供することがあります。これらの第三者のサイトには、個別の独立したプライバシーポリシーがあります。従って、これらのリンク先のサイトに関するコンテンツや活動にかんしては一切責任を負いません。ですが、サイトの完全性やこれらのサイトに関するフィードバックは非常に重要なものであると認識しております。
`Occasionally` means `必要に応じて` (not `ときどき`) in this context.

2017-05-02 16:51 UTC, takahashim commented on app/views/about/terms.ja.html.haml
> +  %h3#data-retention どのようにデータは保存されますか？
How about `データ保持のポリシーはどのようになっていますか？` ?

2017-05-02 16:56 UTC, takahashim commented on app/views/about/terms.ja.html.haml
> +  %p このサービスは次のことを行います:
`make a good faith effort` is 「努力義務」 in Japanese.
So `このサービスはデータ保持に関して次のことを行うよう努めます。`.

2017-05-02 17:10 UTC, takahashim commented on app/views/about/terms.ja.html.haml
> +  #{site_hostname} Terms of Service and Privacy Policy
How about `#{site_hostname} 利用規約・プライバシーポリシー`?

2017-05-06 00:05 UTC, gentarok commented on app/views/about/terms.ja.html.haml
> +  %p この文章のライセンスはCC-BY-SAです。このページは2013年5月31日が最終更新です。
Fixed.

2017-05-06 00:05 UTC, gentarok commented on app/views/about/terms.ja.html.haml
> +  %p ライバシーポリシーを変更する場合は、このページへ変更内容を掲載します。
Fixed.

2017-05-06 00:06 UTC, gentarok commented on app/views/about/terms.ja.html.haml
> +  %p ときどき、このサービスの方針にもとづいてこのサイトや第三者のサービスを提供することがあります。これらの第三者のサイトには、個別の独立したプライバシーポリシーがあります。従って、これらのリンク先のサイトに関するコンテンツや活動にかんしては一切責任を負いません。ですが、サイトの完全性やこれらのサイトに関するフィードバックは非常に重要なものであると認識しております。
Fixed.

2017-05-06 00:06 UTC, gentarok commented on app/views/about/terms.ja.html.haml
> +  %h3#data-retention どのようにデータは保存されますか？
Fixed.

2017-05-06 00:07 UTC, gentarok commented on app/views/about/terms.ja.html.haml
> +  %p このサービスは次のことを行います:
Good translation.

2017-05-06 00:07 UTC, gentarok commented on app/views/about/terms.ja.html.haml
> +  #{site_hostname} Terms of Service and Privacy Policy
Fixed.

2017-05-06 00:23 UTC, Gargron approved these changes

2017-05-06 00:23 UTC, merged