Add Elasticsearch index size to Admin dashboard
mastodon/mastodon pull request #27301
Opened 2023-10-05 21:32 UTC by vmstan

Implements #27292

See feature request for details, but screenshot of code as implemented
![CleanShot 2023-10-05 at 16 27 46@2x](https://github.com/mastodon/mastodon/assets/3002053/a22de6b7-ba91-4b62-bf37-84c4f83156cc)

2023-10-05 22:20 UTC, Gargron approved these changes

2023-10-06 09:44 UTC, ClearlyClaire requested changes

2023-10-06 09:44 UTC, ClearlyClaire commented on app/lib/admin/metrics/dimension/space_usage_dimension.rb
> +    [postgresql_size, redis_size, media_size, search_size]
This doesn't correctly handle the case where Elasticsearch is disabled.

```suggestion
    [postgresql_size, redis_size, media_size, search_size].compact
```

2023-10-06 15:02 UTC, ClearlyClaire approved these changes

2023-10-06 15:02 UTC, merged