Likely fix #2458, fix #2031 - handle out-of-order deletes for statuses
mastodon/mastodon pull request #2734
Opened 2017-05-03 00:24 UTC by Gargron

If a delete arrives before the original status, cache that information
for 6h, and if the original status arrives in that window, ignore it

2017-05-03 06:09 UTC, Taekiro commented on app/services/process_feed_service.rb
> +        redis.setex("delete_upon_arrival:#{id}", 6 * 3_600, id)
Typo : 6 * 3600 (no underscore)

2017-05-03 07:07 UTC, ykzts commented on app/services/process_feed_service.rb
> +        redis.setex("delete_upon_arrival:#{id}", 6 * 3_600, id)
It is not typo. Integer including "`_`" is valid Ruby syntax.

2017-05-03 07:08 UTC, Taekiro commented on app/services/process_feed_service.rb
> +        redis.setex("delete_upon_arrival:#{id}", 6 * 3_600, id)
my bad, sorry.

2017-05-03 20:39 UTC, mjankowski commented on app/services/process_feed_service.rb
> +
whitespace here!

2017-05-03 20:39 UTC, mjankowski requested changes
We should probably have at least one spec that shows that an incoming status which has a delete key present does get ignored...

2017-05-04 00:47 UTC, Gargron commented
Added as requested

2017-05-04 01:24 UTC, mjankowski approved these changes

2017-05-04 02:34 UTC, merged