MAX_POST_CHARS Env
mastodon/mastodon pull request #27629
Opened 2023-10-31 01:32 UTC by shleeable

I completed a quick survey of 10,000+ Mastodon instances and found that 21% of them change their MAX_POST length in some way... that's more than 2100 instance admins messing with the code.... and causing problems/extra work for themselves for upgrades and merge conflicts.

Results here: https://gist.github.com/shleeable/101b131653c0ff0e21a81bf99a31c7f0

As such, I've stolen the code from Glitch for MAX_POST_CHARS.... @ClearlyClaire please make sure I'm not missing anything

2023-10-31 01:34 UTC, shleeable commented
Example of the survey
```
   10335 | TOTAL LINES
     140 | DISTINCT LINES

COUNT    | LINE
-----------------------------------------------------
    8138 | 500
     942 | 5000
     445 | 3000
     135 | 1000
      81 | 10000
      77 | 2000
      49 | 1500
      35 | 100000
```

2023-10-31 08:50 UTC, ClearlyClaire requested changes

2023-10-31 08:50 UTC, ClearlyClaire commented on app/serializers/initial_state_serializer.rb
`max_post_chars` is missing from the `attributes`

2023-10-31 08:50 UTC, ClearlyClaire commented on app/serializers/rest/v1/instance_serializer.rb
I wouldn't change this file, as we have the V2 serializer already exporting that bit of information.

2023-10-31 10:33 UTC, shleeable commented on app/serializers/rest/v1/instance_serializer.rb
change reverted

2023-10-31 10:34 UTC, shleeable commented on app/serializers/initial_state_serializer.rb
Added attributes

2023-10-31 10:36 UTC, shleeable commented
@ClearlyClaire updated.

2023-10-31 11:02 UTC, ClearlyClaire approved these changes

2023-11-28 01:10 UTC, vmstan commented
Fixes #12265

2023-12-14 23:29 UTC, vmstan commented
I wonder why the rebase required hasn't triggered for this? The initializer file was redone in #28363 and the patch won't apply anymore.

2023-12-17 09:28 UTC, shleeable commented
Cite: https://aus.social/@rolle@mementomori.social/111595035041587931

2023-12-24 07:09 UTC, adulau commented
Can we expect a merge for the release 4.2.4 ? This would be awesome.

2024-01-05 14:03 UTC, ClearlyClaire commented
I don't think @Gargron's stance against making the character limit customizable has changed.

2024-01-06 00:20 UTC, jgillich commented
OP does make a strong case for this change in my opinion: 21% of admins already jump through the hoops to change this. It is a frequent request by users, and most other fediverse servers support custom character limits. Gargron is against this because the UI/UX is designed for 500 characters, but you could also mention this in the documentation for this option and make it clear that a limit of 500 is the official recommendation. The majority of admins will stick with the default, but you'll remove pain points for those who'll change it anyhow.

2024-01-06 01:48 UTC, PinballsWizard commented
I would be interested to know if the survey data collected also includes the version each instance is running, as compared to the then-current most up to date version.  The additional code changes add complexity to upgrades and simplifying this may be beneficial to ensuring more instance admins update in a more timely manner.

2024-01-08 00:03 UTC, shleeable commented
The battle of MAX_CHAR Hill continues.

2024-01-08 00:14 UTC, nightpool commented
my stance has always been that I think it's much more healthy for the ecosystem for thousands of admins to learn how to make changes and customize the software they run rather than having to shoulder the complexity of infinite possible customizations in thr base code. additionally I mostly agree wrt the UI. By not adding this to the base mastodon codebase, we encourage the development of alternative server software and client UI that's more purpose built for longer posts, like Tumblr.

2024-01-08 05:23 UTC, shleeable commented
> we encourage the development of alternative server software and client UI that's more purpose built for longer posts, like Tumblr.

Me too pal.

2024-01-17 03:47 UTC, mwt commented
> > we encourage the development of alternative server software and client UI that's more purpose built for longer posts, like Tumblr.
> 
> Me too pal.
> 
> It's been a dark time for people like me that believe Tumblr is the superior social network.... maybe 2024 is the year of the FediTumblr clone.

or just fedi support in tumblr, which is likely!

2024-01-17 09:53 UTC, gabboman commented
> > we encourage the development of alternative server software and client UI that's more purpose built for longer posts, like Tumblr.
> 
> 
> 
> Me too pal. 
> 
> 
> 
> It's been a dark time for people like me that believe Tumblr is the superior social network.... maybe 2024 is the year of the FediTumblr clone.

wafrn added fedederation in 2023 but maybe 2025 will be the year of wafrn (I am trying to be real)

2024-01-20 22:49 UTC, cmdr-nova commented
I support a max post toggle, this would be amazing

2024-01-28 17:18 UTC, adulau commented
Can we expect a merge for the release 4.2.5 ? This would be awesome. I must admit it will be soon my trigger to move to a fork if it's not finally in Mastodon....

2024-01-28 18:25 UTC, arazilsongweaver commented
Most of the UI/UX functionality to support this feature was recently merged in via pull request #28928 ... AFAIK the only thing left to do is to implement the server side of things and clean up any resulting QA/QC items.

2024-01-29 10:55 UTC, closed without merging

2024-03-27 12:11 UTC, rahilarious commented
Instead of being dictated by _one_ guy and his decision, Mastodon should use it's own feature and take a **poll** to make decision. 

I shouldn't be needing to compile from source or use fork just for one simple env variable