Changed the background color of welcome email handle in mailer.scss
mastodon/mastodon pull request #27708
Opened 2023-11-05 17:32 UTC by Elgueromiranda

The handle isnt legible because the text is black and the background is dark

2023-11-05 17:43 UTC, Elgueromiranda commented
[https://github.com/mastodon/mastodon/issues/27707](url)

2023-11-07 08:25 UTC, Elgueromiranda commented
Closes #6938

2023-11-07 08:32 UTC, Elgueromiranda commented
fixes #6938

2023-11-09 11:05 UTC, rugk commented
Awesome!

Just FYI, cause you tried it: You can (automatically) [let issues close](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when a PR is merged by adding some "magic" text to your PR _body_. Or manually link it at the right. Using the codeword in a comment does not help.

2023-11-09 11:43 UTC, renchap requested changes

2023-11-09 11:43 UTC, renchap commented on app/javascript/mastodon/features/emoji/unicode_to_filename.js
> +export const unicodeToFilename = (str) => {
This change is unrelated, please remove your first commit from your PR. The issue you are trying to fix here has been fixed in `main`, so a rebase should fix this.

2023-11-09 11:43 UTC, renchap commented on app/javascript/mastodon/features/emoji/unicode_to_unified_name.js
> +export const unicodeToUnifiedName = (str) => {
Same here

2023-11-09 11:53 UTC, Gargron commented
We are working on an e-mail redesign.

2023-11-11 02:34 UTC, closed without merging