Streamline javascript translation by improving translationRunner
mastodon/mastodon pull request #2808
Opened 2017-05-05 11:06 UTC by yookoala

Allow translator to use nodejs script for translation detection and stuff.

To check the language file(s) you're interested in, you may use this routine:
```
yarn install
yarn build:babel
yarn manage:translations [language code]
```

If you do not pass in any language code in the last command, you'd be checking all the available languages.

If you are not sure, you may use this command:
```
yarn manage:translations -- --help
```

2017-05-05 15:29 UTC, Gargron requested changes

2017-05-05 15:29 UTC, Gargron commented on package.json
> +    "build:babel": "babel app/javascript --out-dir ./build",
Surely this should be "build" running a webpack build? I'm not sure babel alone will handle everything given there are lots of requires.

2017-05-05 15:34 UTC, yookoala commented on package.json
> +    "build:babel": "babel app/javascript --out-dir ./build",
This task for me is mainly for generating the translation strings source (so I can run `yarn manage:translations` with no error). I think it is not necessary for actually generating the webpack bundle.

Open for suggestion how to name / modify it.

2017-05-05 16:40 UTC, yookoala commented on package.json
> +    "build:babel": "babel app/javascript --out-dir ./build",
Rewritten as tasks "build:production" and "build:development".

2017-05-06 02:05 UTC, Gargron approved these changes

2017-05-06 02:05 UTC, merged