Handling failed http response
mastodon/mastodon pull request #2823
Opened 2017-05-05 19:00 UTC by alpaca-tc

Raise readable error for failed request.

Current error isn't clearly.

```
A RuntimeError occurred in accounts#follow:

  Could not parse document
  app/services/follow_remote_account_service.rb:78:in `get_feed'
```

2017-05-05 19:31 UTC, Gargron approved these changes

2017-05-06 02:04 UTC, Gargron requested changes

2017-05-06 02:04 UTC, Gargron commented on app/services/follow_remote_account_service.rb
> +    raise "Feed attempt failed for #{url}: HTTP #{response.code}" unless response.code == 200
I think this should be raised as a Goldfinger::Error because we already rescue_from those in ApiController

2017-05-06 09:16 UTC, alpaca-tc commented
I fixed 😸

2017-05-06 09:18 UTC, ykzts approved these changes

2017-05-06 10:55 UTC, Gargron approved these changes

2017-05-06 10:56 UTC, merged