l10n: Improved RTL character count
mastodon/mastodon pull request #2884
Opened 2017-05-07 14:51 UTC by seefood

* Drop mentions from text before counting the text, JS function.

* Same for Ruby function, plus updates to spec by @JoelQ 

Also attn @mabkenar @yookoala @BoFFire 

Thanks!

2017-05-07 14:56 UTC, mabkenar commented
This is great! I really appreciate your work on this. 
Could you also remove URLs before counting RTL/LTR chars? Based on my tests, at the moment links are counted twice (I guess the entire HTML string like <a href="http://domain.tld">domain.tld</a> is counted). It would be nice if URLs are completely removed.

2017-05-07 15:01 UTC, seefood commented
Naturally that would be the next logical step, but that RegEx is _a bit_ more complicated :-)
Once I get this baby step into the code, I'll research the right way to surgically remove URLs, Latin-only hashtags too maybe? what about stock symbols? and emoji? :)

2017-05-07 15:13 UTC, mabkenar commented
Anything that is language independent by nature, but is **represented** with Latin characters should be removed IMO. Therefore, I think emojis and symbols and image upload URLs should be removed, but Latin hashtags should not.

2017-05-07 16:59 UTC, Gargron requested changes

2017-05-07 16:59 UTC, Gargron commented on app/helpers/stream_entries_helper.rb
> +      justtext = text.gsub(/@[0-9A-Za-z_@]+/, '')
Probably `Account::MENTION_RE`?

2017-05-08 09:24 UTC, seefood commented on app/helpers/stream_entries_helper.rb
> +      justtext = text.gsub(/@[0-9A-Za-z_@]+/, '')
sounds like a plan... Wish you had a ready-made RE for URLs :)

2017-05-08 13:27 UTC, seefood commented
I don't have a test env handy, so I'm closing this for now. I'll reopen once I had a change to test it (Or if one of you can please test)

2017-05-08 13:27 UTC, closed without merging

2017-05-12 12:45 UTC, mabkenar commented
@seefood I absolutely think this PR should make progress. While I cannot set up a dev environment for you myself, I can gladly help by setting up a paid Mastodon instance using http://masto.host/ (which makes it possible to have it based on any git repo instead of the official Mastodon repo). If you agree, I can do it for you and give you the credentials.

2017-05-13 12:58 UTC, seefood commented
I have one set up at home, I just get to it rarely (too busy between work and family, I rarely turn on my home desktop).

But today is saturday, and I'm at the keyboard, I hope to test it some and fire it off again...

2017-05-13 21:35 UTC, seefood commented
OK! I have improved and tested the code, I'll go make a PR.