Redundant return
mastodon/mastodon pull request #29095
Opened 2024-02-05 14:28 UTC by shleeable

2024-02-05 15:33 UTC, mjankowski approved these changes

2024-04-04 08:41 UTC, shleeable commented
@renchap this is the worlds least important PR but it's an easy merge.

2024-04-04 09:05 UTC, renchap requested changes

2024-04-04 09:05 UTC, renchap commented on app/controllers/api/web/embeds_controller.rb
> +        not_found
I think the `return` is important here. With your code, what will be executed if there is an `ArgumentError` is:

```ruby
not_found

render json: oembed
```

The `render json: oembed` needs to be in the `begin` block if you do want the same behaviour

2024-04-04 16:34 UTC, mjankowski commented
With the linked PR merged, if you rebase this you'll see a failure with just this change.

2024-04-08 01:14 UTC, shleeable commented
ooh in that case. Don't want to cause a regression.

2024-04-08 01:14 UTC, closed without merging