fix(column): Fix rightmost column height in safari
mastodon/mastodon pull request #2916
Opened 2017-05-08 14:48 UTC by stephenburgess8

Removing styles causing bug in Safari. Tested in Firefox, Chrome, and Safari on Mac. #2899

2017-05-08 14:52 UTC, ykzts approved these changes

2017-05-08 14:53 UTC, stephenburgess8 commented
@akihikodaki Any reason why these styles would be needed that is not immediately obvious? Thanks.

2017-05-08 14:58 UTC, akihikodaki commented
@stephenburgess8 I commented to the issue. https://github.com/tootsuite/mastodon/issues/2899#issuecomment-299890927

2017-05-08 14:59 UTC, akihikodaki requested changes
As I mentioned at https://github.com/tootsuite/mastodon/issues/2899#issuecomment-299890927.

2017-05-08 15:16 UTC, akihikodaki requested changes
Still failing; open a timeline in multi-column layout and then make the screen smaller.

2017-05-08 15:17 UTC, akihikodaki commented
Thank you for working on this. I do not have Mac, so that helps much.

2017-05-08 15:21 UTC, stephenburgess8 commented
I have been having to recompile with webpack in order to get my CSS changes to show up. After I make this change and recompile, this change shows up and works for me. Can you confirm that `overflow-y` is compiled as `auto` and not `scroll` on the `scrollable` class? That said, I would like to spend a little time with this and do some more cross-browser testing before accepting it. `scrollable` class is used in many places.

2017-05-08 15:26 UTC, akihikodaki commented
Ah, sorry. Actually webpack was failing as you pointed out. However I now see it goes wrong on Chrome with the single-column layout.

2017-05-08 15:28 UTC, stephenburgess8 commented
I can return to this a little later today.

2017-05-14 01:39 UTC, akihikodaki requested changes
This breaks scroll (and possibly other states) preservation.
Also, lease rebase rather than creating a merge commit instead.

2017-05-14 01:39 UTC, akihikodaki commented on app/javascript/styles/containers.scss
> +  display: none;
This breaks scroll (and possibly other states) preservation.

2017-05-14 01:46 UTC, akihikodaki commented
Perhaps it is too difficult to keep everything correct on every supported browsers.
The current design of the UI is inconsistent in terms that only the scroll bar is tied to the window, leaving the column independent of the window in the single-column layout. In the multiple-column layout, each column has the scroll bar and they are completely independent of the window.
We may need issues or pull requests to fix the inconsistency.

2017-05-14 01:51 UTC, akihikodaki commented on app/javascript/styles/containers.scss
> +  display: none;
(reproducible on `Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0`, with the single-column layout)

2017-05-14 04:46 UTC, stephenburgess8 commented
I'm sorry, I hadn't registered that you were doing visibility:hidden in order to save the scroll position.

When you get a chance, if you could please check this out one more time. I have made it so that scroll position is saved. I have tested in the following browsers in both desktop view and smaller mobile view:

Safari 9
Firefox 53.0.2 
Chrome 58.0.3029.110

NOT IE11 (have not been able to get my VM to work with localhost:3000)

There is a small visual bug in Safari in Mobile view but it is still usable and it's a much better Safari experience overall now. Should have a slightly improved UI in Chrome and Firefox.

2017-05-14 04:48 UTC, akihikodaki commented
The composer died on `Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0`, with the mobile view. :/

2017-05-14 04:49 UTC, akihikodaki commented
By the way, Mastodon does not work on IE. Test with Edge for Windows.

2017-05-14 04:52 UTC, stephenburgess8 commented
The wrapper I added around mobile column must be disrupting the compose. However, I think it's getting closer. I think it's worth it to provide support for more browsers, as that makes the software accessible to more people. Thanks for your help on this.

2017-05-14 05:39 UTC, akihikodaki commented
b94f0bd5db54fdb7487f145865bbea435d01fdbc looks good for me (`Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0` and `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36`)

2017-05-14 05:49 UTC, stephenburgess8 commented
Sorry, display none was not needed. Rechecked in Safari, Chrome, Firefox

2017-05-14 05:52 UTC, ykzts approved these changes

2017-05-15 00:09 UTC, ykzts commented
@stephenburgess8 Can you solve this problem in #3062?

2017-05-22 00:09 UTC, Gargron commented
I think this is no longer a problem.

2017-05-22 00:09 UTC, closed without merging