Add nan-TW locale
mastodon/mastodon pull request #29184
Opened 2024-02-13 09:31 UTC by gunchleoc

Taiwanese is being translated on Crowdin. See https://github.com/mastodon/mastodon/pull/27705

2024-02-14 07:12 UTC, ykzts approved these changes

2024-03-01 18:00 UTC, renchap requested changes
The `nan-TW` language does not seem to exist in Crowdin, so this PR is invalid.

We can accept it with the compose menu change only, but it will need to be created in Crowdin and translated before we can add it to the main codebase.

2024-03-07 09:25 UTC, gunchleoc commented
> The `nan-TW` language does not seem to exist in Crowdin, so this PR is invalid.
> 
> We can accept it with the compose menu change only, but it will need to be created in Crowdin and translated before we can add it to the main codebase.

This is a chicken and egg problem. I don't have management access to Crowdin, so I can only do the software side. Somebody who has access needs to create the project in Crowdin so that the translator can follow the normal translation procedure. If Crowdin doesn't support the locale out of the box, you can create a custom locale. I'll head over to https://github.com/mastodon/mastodon/pull/27705 and ask the translator what the plural rules are, since it's not listed in the CLDR.

2024-11-21 23:13 UTC, mjankowski commented
Looks like this had a failing CI job (logs are gone) and a non-finishing one -- might need bump.

Separately - not sure where this one stands. Is the consensus that we want to add this and just need someone to add it in crowdin?

2024-11-23 08:12 UTC, gunchleoc commented
> Looks like this had a failing CI job (logs are gone) and a non-finishing one -- might need bump.
> 
> Separately - not sure where this one stands. Is the consensus that we want to add this and just need someone to add it in crowdin?

Like I commented above, somebody needs to add the locale to Crowdin first. Until that's done the i18n job will fail. I don't have any project managing powers on Crowdin, so I can't do that myself.

I think we really need more people to be able to manage our Crodwin, the translator has now been waiting for this since February.

2024-11-23 14:57 UTC, mjankowski commented
> Like I commented above, somebody needs to add the locale to Crowdin first. Until that's done the i18n job will fail. I don't have any project managing powers on Crowdin, so I can't do that myself.

cc @renchap  - who has access to crowdin management?, and who decides on super minor language addition stuff like this?

> I think we really need more people to be able to manage our Crowdin, the translator has now been waiting for this since February.

That does not sound enjoyable at all, but I commend them for their patience and continued commitment to the collective translation aspirations we all have for a better tomorrow.

2024-11-23 16:18 UTC, gunchleoc commented
> > I think we really need more people to be able to manage our Crowdin, the translator has now been waiting for this since February.
> 
> That does not sound enjoyable at all, but I commend them for their patience and continued commitment to the collective translation aspirations we all have for a better tomorrow.

Let's just hope that they haven't given up

2024-11-25 20:49 UTC, renchap commented
As the language does not exists in Crowdin, we need to add a custom language. Unfortunately, I do not have access to those, but I can try to have it added. 

I will need those informations, as per [Crowdin docs](https://support.crowdin.com/project-settings/languages/#adding-custom-languages):
- language name
- is it a dialect of another language?
- crowdin code (probably `nan-tw`?)
- 3 letter code
- locale code (`nan-tw`?)
- text direction
- plural forms

2024-12-03 09:34 UTC, renchap commented
The language is now created and enabled on Crowdin

2024-12-03 09:45 UTC, Yoxem commented
> The language is now created and enabled on Crowdin

The taigi (tai; which is an invalid ISO 639 code) can be merged to nan-TW (valid ISO 639), and then delete taigi.
![圖片](https://github.com/user-attachments/assets/a27554d1-7b1c-4639-8064-4db0600db022)

2024-12-03 10:07 UTC, winstonsung commented
We should consider split nan-TW into 3 writing systems:

* https://github.com/WeblateOrg/language-data/issues/1408
* https://github.com/WeblateOrg/language-data/commit/80792eb

2024-12-03 10:24 UTC, Yoxem commented
> We should consider split nan-TW into 3 writing systems:
> 
>     * [Split "nan-Latn" into "nan-Latn-pehoeji", "nan-Latn-tailo" WeblateOrg/language-data#1408](https://github.com/WeblateOrg/language-data/issues/1408)
> 
>     * [WeblateOrg/language-data@80792eb](https://github.com/WeblateOrg/language-data/commit/80792eb)

However, the writing system is not determined among the potential translators, it should be discussed, although I prefers mixture of CJKV and Romainzations.

2025-02-22 10:15 UTC, gunchleoc commented
@renchap I can't find the code on Crowdin - can you please double-check? https://crowdin.com/project/mastodon/nan-TW

@winstonsung @Yoxem Who many volunteer localizers do you have in your language community? It's probably best to start off with 1 locale until you get a feel for the maintenance burden. You can always ask for sub-locales later.

2025-02-22 10:20 UTC, winstonsung commented
> I can't find the code on Crowdin - can you please double-check? https://crowdin.com/project/mastodon/nan-TW

It's right here:

https://crowdin.com/project/mastodon/nan-tw

2025-04-26 01:00 UTC, winstonsung commented
We could now use `nan-Hntl-TW` as the ISO 15924 script code is now approved and registered:

https://www.unicode.org/iso15924/codechanges.html

2025-05-28 20:09 UTC, gunchleoc commented
> We could now use `nan-Hntl-TW` as the ISO 15924 script code for Hant + Latn is now approved and registered:
> 
> https://www.unicode.org/iso15924/codechanges.html

Sounds good to me. Can somebody with Crowdin powers take care of it?

BTW the reason I didn't find the language on Crowdin was because it was registered as `nan-tw` instead of `nan-TW`. This is an inconsistency with the casing of the country codes for all other locales. So, no matter which one of the 2 codes we pick, it needs fixing over there.

2026-08-04 17:32 UTC, renchap commented
I believe this has been done in https://github.com/mastodon/mastodon/pull/34923

2026-08-04 17:32 UTC, closed without merging