Update languages_helper.rb
mastodon/mastodon pull request #29237
Opened 2024-02-16 03:48 UTC by VaultAusir

Ladino (language code: lad) translation on Crowdin is complete.

2024-02-17 15:15 UTC, ykzts approved these changes

2024-03-01 17:48 UTC, renchap submitted a review, later dismissed

2024-03-01 17:50 UTC, renchap commented
Your change adds this language to the composer language selector. If you want to add it to the list of available languages for the UI, then it needs to be added to `config/initializers/i18n.rb` as well.

2024-03-01 18:07 UTC, renchap requested changes
Your change adds this language to the composer language selector. If you want to add it to the list of available languages for the UI, then it needs to be added to config/initializers/i18n.rb as well.

2024-11-21 19:44 UTC, mjankowski commented
Closing based on lack of addressing prior feedback.

That said, this seems pretty simple and was previously approved -- if you'd like to nudge forward, please rebase, reopen, address the feedback, etc.

2024-11-21 19:44 UTC, closed without merging