Use modern ES syntax rather than `.call`
mastodon/mastodon pull request #29368
Opened 2024-02-22 22:33 UTC by renchap

I replaced `Object.prototype.hasOwnProperty.call` with the new ES2022 `Object.hasOwn`.

It is not transpiled by Babel in the final files, because this function is supported by all the browsers our BrowsersList is targetting.

If this causes issues, then we can change our supported browsers list and target earlier versions, then it will be polyfilled accordingly.

2024-02-22 22:34 UTC, ykzts submitted a review, later dismissed

2024-02-23 14:57 UTC, ClearlyClaire requested changes
Typo, plus `some` and `every` are not defined on `NodeList` afaik

2024-02-23 14:57 UTC, ClearlyClaire commented on app/javascript/packs/admin.jsx
> +    target.querySelectorAll('input[type="datetime-local"]').foreach(element => {
Typo:
```suggestion
    target.querySelectorAll('input[type="datetime-local"]').forEach(element => {
```

2024-02-27 12:23 UTC, ClearlyClaire requested changes

2024-02-27 12:23 UTC, ClearlyClaire commented on app/javascript/packs/public.jsx
> +          component.children.forEach((child) => {
`component.children` is a `HTMLCollection`, which doesn't have `forEach`

2024-02-27 15:11 UTC, ClearlyClaire approved these changes
Looks good now, although I'd like to see it run with the test introduced in #29424 first.

2024-02-27 15:26 UTC, renchap commented
Rebased to include your new test

2024-02-27 15:47 UTC, merged