Revert HTML CW changes
mastodon/mastodon pull request #3020
Opened 2017-05-12 17:40 UTC by beatrix-bitrot

set spoiler_text back to just be text, the way it was before. clients will have to link hashtags themselves if they want!

partly reverts changes from #2970 
completely reverts changes from #2683

2017-05-12 17:47 UTC, Gargron requested changes

2017-05-12 17:47 UTC, Gargron commented on app/javascript/mastodon/components/status_content.js
> +    if (e.target.localName === 'a' || (e.target.parentNode && e.target.parentNode.localName === 'a')) {
We wanna keep this and 77

2017-05-12 17:47 UTC, Gargron commented on app/javascript/mastodon/components/status_content.js
> +      } else if (media) {
This should stay gone

2017-05-12 17:47 UTC, Gargron commented on app/javascript/mastodon/components/status_content.js
> +        <div className='status__content' onMouseDown={this.handleMouseDown} onMouseUp={this.handleMouseUp}>
All of below can stay as they were

2017-05-12 17:47 UTC, Gargron commented on app/lib/atom_serializer.rb
> +    append_element(entry, 'summary', status.spoiler_text, 'xml:lang': status.language) if status.spoiler_text?
Doesn't really matter but I liked summary be before content. Otherwise correct

2017-05-12 18:01 UTC, beatrix-bitrot commented on app/javascript/mastodon/components/status_content.js
> +    if (e.target.localName === 'a' || (e.target.parentNode && e.target.parentNode.localName === 'a')) {
are you sure? cause we introduced a regression where clicking the CW button would also open the detailed status and after this changeset it is fixed, which I suspect is related to this  particular change though i didn't test it in isolation

2017-05-12 18:20 UTC, Gargron commented on app/javascript/mastodon/components/status_content.js
> +    if (e.target.localName === 'a' || (e.target.parentNode && e.target.parentNode.localName === 'a')) {
I couldn't reproduce that behaviour, it shouldn't depend on button vs a anyway, but button is more a11y-friendly

2017-05-12 18:54 UTC, beatrix-bitrot commented on app/javascript/mastodon/components/status_content.js
> +    if (e.target.localName === 'a' || (e.target.parentNode && e.target.parentNode.localName === 'a')) {
agreed ok, will do so

2017-05-13 01:28 UTC, Gargron approved these changes

2017-05-13 02:03 UTC, merged