Check media attachment size limit on client side before uploading
mastodon/mastodon pull request #30475
Opened 2024-05-29 23:17 UTC by rgroothuijsen

This is a continuation of #17708, rebased and making use of the values already loaded into the client-side store to avoid an extra backend call. The hardcoded limits have thus been removed from the frontend code.

2024-09-23 07:07 UTC, oneiros requested changes

2024-09-23 07:07 UTC, oneiros commented on app/javascript/mastodon/actions/compose.js
> +    const maxMediaAttachments = serverConfiguration.getIn(['statuses', 'max_media_attachments']);
Is this not the same as `uploadLimit` above?

(FWIW, I prefer the name `maxMediaAttachments` as I think it is clearer, so maybe `uploadLimit` could be renamed.)

2024-09-23 07:07 UTC, oneiros commented on app/javascript/mastodon/actions/compose.js
> +        || (files.length + media.size + pending > maxMediaAttachments))) {
This last condition does not rely on any single file. As such it does not need to be repeated for every single file. Also, as this is probably cheaper than looping over all the files, you might want to check this first.

2024-11-22 13:32 UTC, mjankowski commented
I can't tell from the history here if all feedback was addressed and this is ready for re-review, or if there's still something pending...

2024-11-26 22:28 UTC, rgroothuijsen commented
I did address the review points above, so it's ready for re-review as far as I'm concerned.

2024-11-26 22:35 UTC, mjankowski commented
Excellent, thanks ... will see if we can get re-review.

2025-06-24 15:48 UTC, oneiros approved these changes, later dismissed

2025-06-24 15:48 UTC, oneiros commented
Thanks for the contribution and sorry it took so long.

2025-06-24 17:12 UTC, renchap commented
This probably needs a rebase

2025-06-25 01:44 UTC, shleeable commented
@rgroothuijsen Please rebase.

2025-06-25 08:13 UTC, oneiros commented
The patch is really small and still applied cleanly. I rebased anyway, but it had, as I expected, no effect. Something else is going on here. Investigating.

2025-06-25 10:34 UTC, oneiros commented
I identified the issue, which is an existing one that is only surfaced by the changes here: The upload code tries to get server settings that need to be fetched from the instance API endpoint. If a user (or a spec driving a headless browser) uploads a file very quickly, or if the endpoint is very slow, these may not have fully loaded yet.

2026-02-19 15:29 UTC, mjankowski commented
> I identified the issue, which is an existing one that is only surfaced by the changes here: The upload code tries to get server settings that need to be fetched from the instance API endpoint. If a user (or a spec driving a headless browser) uploads a file very quickly, or if the endpoint is very slow, these may not have fully loaded yet.

Given that it's a preexisting issue, is this good to go forward now? (needs another rebase after quote work, I suspect) ... or do we want to first put some better handling in place for that scenario where the UI is ready and being used faster than the API can respond, and then re-do this after?

2026-04-07 16:27 UTC, mjankowski commented
Going through some older approved but not merged PRs. This one is blocked on needing rebase and needing a decision/input on the question about whether to try to pre-address the API/loading/timing thing here or not.

2026-09-10 13:06 UTC, mjankowski commented
@oneiros (or whoever) - any opinion on above questions/blockers/etc here?

2026-09-11 11:55 UTC, ChaosExAnima approved these changes, later dismissed

2026-09-11 12:18 UTC, ChaosExAnima commented
there were a few issues that i resolved: firstly the server config is a plain JS object and not Immutable, which caused errors. second is that if the data isn't set it just defers the check to the server.

should be good to merge.

2026-09-11 13:07 UTC, oneiros approved these changes

2026-09-11 13:59 UTC, merged

2026-09-11 14:44 UTC, shleeable commented
Thanks.