Add setting to disable hover cards
mastodon/mastodon pull request #30931
Opened 2024-07-05 12:46 UTC by ClearlyClaire

2024-07-06 07:21 UTC, renchap commented
If we do this, we probably need to reinstate the `title` attributes what were removed from the hover cards PR and merge my commit that disables the `title` attribute on hover anchors.

2024-07-08 07:10 UTC, ClearlyClaire commented
> If we do this, we probably need to reinstate the `title` attributes what were removed from the hover cards PR and merge my commit that disables the `title` attribute on hover anchors.

Do you mean #30948?

2024-07-08 08:50 UTC, renchap commented
For handling the `title` attribute, yes, but the PR introducing the hover cards removed the `title` attributes in some places, it probably needs to be added back.

2024-07-09 10:01 UTC, Gargron commented on config/locales/simple_form.en.yml
> +        setting_disable_hover_cards: Disable hover cards
Should we call them "rich tooltips"? Would that be intuitive?

2024-07-09 13:05 UTC, Gargron commented on config/locales/simple_form.en.yml
> +        setting_disable_hover_cards: Disable hover cards
"Disable profile preview on hover"?

2024-07-11 18:34 UTC, Gargron requested changes

2024-07-11 18:34 UTC, Gargron commented on config/locales/simple_form.en.yml
> +        setting_disable_hover_cards: Disable hover cards
```suggestion
        setting_disable_hover_cards: Disable profile preview on hover
```

2024-07-11 19:30 UTC, Gargron approved these changes

2024-07-11 19:53 UTC, merged