feat(babel): Strip prop types
mastodon/mastodon pull request #3122
Opened 2017-05-18 22:32 UTC by sorin-davidoi

No need to ship our `propTypes`. Unfortunately this does not strip them from imported modules and does not remove the two modules from the bundle.

Before:
```bash
> ls -l --block-size=KB public/packs | grep 'application.*.js'
-rw-r--r-- 1 sorin sorin 1015kB May 19 01:22 application-e2333eb5abd97b680820.js
-rw-r--r-- 1 sorin sorin  241kB May 19 01:22 application-e2333eb5abd97b680820.js.gz
-rw-r--r-- 1 sorin sorin 6357kB May 19 01:22 application-e2333eb5abd97b680820.js.map
```

After:
```bash
> ls -l --block-size=KB public/packs | grep 'application.*.js'
-rw-r--r-- 1 sorin sorin 1007kB May 19 01:26 application-4cc778a2892b9ed4f620.js
-rw-r--r-- 1 sorin sorin  240kB May 19 01:26 application-4cc778a2892b9ed4f620.js.gz
-rw-r--r-- 1 sorin sorin 6305kB May 19 01:26 application-4cc778a2892b9ed4f620.js.map
```

2017-05-18 23:29 UTC, ykzts commented on .babelrc
> +        }],
replace indent format

2017-05-18 23:51 UTC, ykzts approved these changes

2017-05-18 23:53 UTC, ykzts requested changes

2017-05-18 23:53 UTC, ykzts commented on package.json
> +    "babel-plugin-transform-react-remove-prop-types": "^0.4.5",
move to `depedencies`. `rails assets: precompile` runs `yarn install` with `NODE_ENV=production`.

2017-05-19 00:09 UTC, nolanlawson approved these changes

2017-05-19 00:10 UTC, ykzts approved these changes

2017-05-19 00:42 UTC, merged