Harmonize persistent scrollbar styles
mastodon/mastodon pull request #31445
Opened 2024-08-15 19:34 UTC by vmstan

This seeks to bring some harmony to the various browser scrollbars after a couple of previous changes to adapt to the new border styles. 

- Tweaks the Safari desktop style to include a more macOS style rounded thumb/throbber in the tray which is slightly wider to accommodate being able to grab it with the mouse pointer
- Uses the same coloring for the native scrollbars in Firefox and Chrome/Edge on all platforms.

Safari on macOS insists on making the scrollbars visible if any styles are applied. Not styling it will cause them to appear (in a discolored tray) in advanced mode and other places after the session has been sitting for some time. I'm open to ideas to get around this. Everything I looked at included additional JavaScript to detect the state of the mouse/scrollbar which I wasn't keen in introducing.

Firefox and Chrome/Edge will respect the OS behavior to only throw the scroll thumb if you're hovering over the section with the mouse. When "always show scrollbar" is applied to the OS/browser then they will all appear to be similarly correct per platform.

**macOS Safari**
<img width="1512" alt="Screenshot 2024-08-15 at 1 36 31 PM" src="https://github.com/user-attachments/assets/1569b4f0-31f3-43eb-a04d-7eb897d05132">

**macOS Firefox**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/99b8977f-8e61-4ddd-8a97-c689fc452abe">

**macOS Chrome/Edge**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0c86ab63-8ae0-4e93-a995-03c0f324f402">

**Windows Firefox**
<img width="1512" alt="Screenshot 2024-08-15 at 1 25 57 PM" src="https://github.com/user-attachments/assets/cc1c991e-e910-4118-b17a-e18131972a31">

_Example Without Persistent Scrollbars_
<img width="1512" alt="Screenshot 2024-08-15 at 1 34 49 PM" src="https://github.com/user-attachments/assets/028af026-70dd-4976-b403-41cbfea7fb3c">

**Windows Chrome/Edge**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/35554932-d7e0-48ba-a09c-990bada16193">

**Linux Firefox**
<img width="1512" alt="Screenshot 2024-08-15 at 2 12 18 PM" src="https://github.com/user-attachments/assets/7b4bd6f4-380e-47e5-bd00-6d80b9563908">

2024-08-16 07:59 UTC, ClearlyClaire commented
The overall consistency is a net improvement (though I have a different behavior with Chromium on Linux for some reason, as shown in the screenshot). I'm also not very happy with the colors, with the track feeling too visible/distracting when it is shown, and there being too little contrast between the track and the thumb.

I personally preferred the old colors (`lighten($ui-base-color, 4%) rgba($base-overlay-background, 0.1)`), although they were probably a bit too subtle.

![image](https://github.com/user-attachments/assets/28ae7e83-a5ea-40b1-96d4-21fe5e93d033)

2024-08-16 08:02 UTC, ClearlyClaire commented
The Chromium styling issue seems to come from a recent Chromium change in which they added support for `scrollbar-color` and `scrollbar-width`, but when those are applied, the other webkit-specific properties are ignored:
https://syntackle.com/blog/changes-to-scrollbar-styling-in-chrome-121/

2024-08-16 14:52 UTC, vmstan commented
@ClearlyClaire yeah I was having issues getting Chrome loaded in my Debian VM, so I didn't test it directly but the rendering appears consistent with the Windows behavior.

I'm also not sold on the purple thumb, it was just an idea I tossed out that got merged. Playing around with options this might also be more subtle and keep the flow of the border lines matching.

**WebKit**
<img width="611" alt="Screenshot 2024-08-16 at 9 48 09 AM" src="https://github.com/user-attachments/assets/ccdf8e26-52a4-4b56-85af-8b866a17d3a9">
<img width="608" alt="Screenshot 2024-08-16 at 9 48 30 AM" src="https://github.com/user-attachments/assets/77101f5d-81ec-424e-9c99-1d8b5a7dd988">


**HTML**
<img width="614" alt="Screenshot 2024-08-16 at 9 47 55 AM" src="https://github.com/user-attachments/assets/15cc1dfd-7c92-48cc-a825-e43601eaf7f0">
<img width="612" alt="Screenshot 2024-08-16 at 9 48 51 AM" src="https://github.com/user-attachments/assets/7b13de5b-9c33-40ff-90af-69a542666026">

2024-08-16 15:27 UTC, ClearlyClaire commented
Was there a reason not to keep the previous colors?

2024-08-16 16:52 UTC, vmstan commented
> Was there a reason not to keep the previous colors?

My goal was to eliminate the gaps creates at the edges of the horizontal lines in column views.

<img width="616" alt="image" src="https://github.com/user-attachments/assets/acf330c1-04cf-4a19-9651-fb6dcf6e0263">

2024-08-16 19:01 UTC, vmstan commented
Updated screenshots with all theme options on all platforms and reflect thumb color adjustments.

2024-08-19 13:17 UTC, ClearlyClaire requested changes
I still think the contrast between the thumb and the track is too little, and the track is too visible, but it's better than previously and more in line with the colors of the themes.

The scrollbars are still not properly styled in recent chromium (see screenshot), presumably because using `scrollbar-color` disables the webkit-specific attributes. A workaround is to skip `scrollbar-color` if the browser supports the webkit-specific attributes.
![image](https://github.com/user-attachments/assets/5c6e1dd5-e231-4e82-b723-709766e1ad78)

2024-08-19 13:17 UTC, ClearlyClaire approved these changes, later dismissed

2024-08-19 13:57 UTC, vmstan commented
> The scrollbars are still not properly styled in recent chromium (see screenshot), presumably because using `scrollbar-color` disables the webkit-specific attributes. A workaround is to skip `scrollbar-color` if the browser supports the webkit-specific attributes. 

I didn't see where this was possible, at least in reviewing https://developer.chrome.com/docs/css-ui/scrollbar-styling and such.

2024-08-19 14:02 UTC, ClearlyClaire commented
I haven't tried, but https://syntackle.com/blog/changes-to-scrollbar-styling-in-chrome-121/ suggests wrapping the use of `scrollbar-color` and `scrollbar-width` with `@supports not selector(::-webkit-scrollbar) { }`

2024-08-19 14:03 UTC, vmstan commented
Actually I see now in https://stackoverflow.com/a/77931548 wrapping it in `@supports not selector(::-webkit-scrollbar)` does the trick. I honestly don't know if this is preferable or not because now it forces the scrollbars there for Chrome and Safari regardless of the browser/OS setting, but I suppose this was the behavior up until 121 which isn't that long ago.

2024-08-19 14:59 UTC, ClearlyClaire commented
I don't remember having set any scrollbar setting in Chromium, nor can I remember anything similar at the level of my desktop environment, so I'm afraid using `scrollbar-width` and `scrollbar-height` unconditionally is going to cause those chunky scrollbars with square chunks (also, I played a bit with it and `scrollbar-width` does not seem to have any effect on Chromium 126)

2024-08-19 16:24 UTC, vmstan commented
I put the wrong version in the commit, should have been 121+, but I've applied the CSS to force Chromium 121+ to continue using the webkit scrollbar styling for as long as that works.

2024-08-19 18:34 UTC, vmstan commented
As seen in Chrome/Edge
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/3df6d71a-25fc-47d2-9e57-65fcaeba4f48">

2024-08-20 07:48 UTC, ClearlyClaire approved these changes

2024-08-20 07:58 UTC, merged