Implement hash tag completion
mastodon/mastodon pull request #3196
Opened 2017-05-21 06:43 UTC by orekyuu

This PR implements completion of hashtags.
The tooted hashtag is included in the candidate.
Candidates are stored localStorage.

<img width="285" alt="2017-05-21 15 23 35" src="https://cloud.githubusercontent.com/assets/2792624/26281766/1b462da4-3e3c-11e7-9c9b-ec29371bdce3.png">

2017-05-22 19:17 UTC, beatrix-bitrot reviewed
overall this is really cool and i like it!

2017-05-23 05:09 UTC, orekyuu commented on app/javascript/mastodon/components/autosuggest_textarea.js
> -  word = word.trim().toLowerCase().slice(1);
I thought the hashtag would distinguish between uppercase and lowercase letters.
I found it to be all lowercase so fixed it.

2017-05-28 15:01 UTC, ykzts commented
resolve conflicts.

2017-05-31 23:41 UTC, nolanlawson requested changes

2017-05-31 23:41 UTC, nolanlawson commented on app/javascript/mastodon/actions/compose.js
> +      }
Storing large amounts of data in LocalStorage is [inefficient](https://hacks.mozilla.org/2012/03/there-is-no-simple-solution-for-local-storage/). I'd advise using IDB instead via a library like [Dexie](http://dexie.org/). You can also use it for range queries, meaning you don't need to constantly re-parse a big string of JSON and then search through it using JavaScript.

2017-06-13 03:59 UTC, ykzts commented
@orekyuu ping

2017-09-30 20:50 UTC, Gargron commented
Closing due to inactivity.

2017-09-30 20:50 UTC, closed without merging