Right align text in last child `td` elements
mastodon/mastodon pull request #32149
Opened 2024-09-28 19:27 UTC by mjankowski

A few befores...

<img width="895" alt="Screenshot 2024-09-28 at 15 07 29" src="https://github.com/user-attachments/assets/e2af9f55-4b61-4fc7-9e9e-1879dd280791">
<img width="923" alt="Screenshot 2024-09-28 at 15 07 34" src="https://github.com/user-attachments/assets/61f073ed-c8f7-4b09-b07e-a9e5cc74a5c2">
<img width="927" alt="Screenshot 2024-09-28 at 15 07 39" src="https://github.com/user-attachments/assets/e298b2f6-6645-425a-a686-491ff977f240">

After:

<img width="892" alt="Screenshot 2024-09-28 at 15 09 15" src="https://github.com/user-attachments/assets/cc988fdd-c87a-4bb7-af83-ad943955aef6">
<img width="847" alt="Screenshot 2024-09-28 at 15 09 20" src="https://github.com/user-attachments/assets/47379a84-08ad-4890-8679-13d00a49abad">
<img width="854" alt="Screenshot 2024-09-28 at 15 09 24" src="https://github.com/user-attachments/assets/3926636d-c74b-4494-ae9f-39c5764b991b">

2024-10-01 13:49 UTC, vmstan approved these changes

2024-10-07 09:51 UTC, Gargron requested changes

2024-10-07 09:51 UTC, Gargron commented on app/javascript/styles/mastodon/tables.scss
> +      text-align: right;
`text-align: end` to support RTL.

2024-10-07 12:59 UTC, mjankowski commented on app/javascript/styles/mastodon/tables.scss
> +      text-align: right;
Updated to use `end`

2024-10-23 14:05 UTC, mjankowski commented
Converted this to `end` - anything else needed?

2024-11-08 14:59 UTC, mjankowski commented
Can I do anything to advance this?

2024-11-20 13:55 UTC, closed without merging