Add option to mute boosts from a user (#648)
mastodon/mastodon pull request #3271
Opened 2017-05-24 00:12 UTC by spinda

This implements #648, adding an additional relationship allowing users to mute particular users' boosts without muting them entirely. I've found myself wanting this quite a bit, as some of the users I follow are a bit over-eager with the boost button.

A new menu item is added to user profiles:

![user profile menu screenshot](https://cloud.githubusercontent.com/assets/7958605/26381572/9ce3fea0-3fda-11e7-8c49-aa602212d3db.png)

A menu item is also added to boosted statuses, to mute boosts from the user doing the boosting:

![status menu screenshot](https://cloud.githubusercontent.com/assets/7958605/26381582/abe2bd42-3fda-11e7-8349-50acd4b3be71.png)

This is my first time contributing to Mastodon, or even writing Ruby, so please let me know where I've messed up. 🌈

2017-05-24 00:13 UTC, spinda commented
Documentation: https://github.com/tootsuite/documentation/pull/260

2017-05-24 14:02 UTC, ykzts commented on app/javascript/mastodon/components/account.js
> +  handleMuteBoosts () {
`handleMuteBoosts = () => { /* ... */ }`

2017-05-24 14:04 UTC, ykzts reviewed
It may be better to name the internal process "MuteReblog" instead of "MuteBoost". Internally the word "Reblog" is used until now.

2017-05-25 18:23 UTC, spinda commented
@ykzts I've applied the requested changes and rebased against the latest `master`.

2017-05-25 23:28 UTC, ykzts commented on db/schema.rb
> +
unused?

2017-05-26 01:09 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> +]
did you run `yarn manage:translations`?

2017-05-26 05:39 UTC, spinda commented on db/schema.rb
> +
I was just mimicking the schema for `mutes` here. Will take it out.

2017-05-26 05:43 UTC, spinda commented on app/javascript/mastodon/locales/defaultMessages.json
> +]
I did not, that's very convenient. It should probably be added to the development docs.

2017-05-26 05:48 UTC, spinda commented
@ykzts I've made the requested changes.

2017-05-26 12:19 UTC, ykzts commented on db/schema.rb
> +
I'm sorry for lack of a word. You don't need to delete timestamps.

Delete the `boosts_mutes` table.

2017-05-29 11:12 UTC, akihikodaki approved these changes

2017-05-29 11:37 UTC, ykzts requested changes

2017-05-29 11:37 UTC, ykzts commented on db/schema.rb
> +  end
Please delete this `create_table`.

2017-05-29 11:37 UTC, ykzts commented on db/migrate/20170525214746_create_reblogs_mutes.rb
> +      t.integer :target_account_id, null: false
Add `t.timestamps`.

2017-05-30 13:26 UTC, Gargron commented
Have you considered whether it'd be worth it to store this on the follows table, as a kind-of "option" of following someone? I am not saying that's definitely the better choice, but want to raise the possibility.

Pros: no extra table, no extra queries to get that value

Cons: follows table is usually huge, modifying it could take a long time, muted reblogs might be a rarely enough used feature that adding a boolean for *all* follows might be worse in terms of disk usage

2017-07-07 02:22 UTC, ykzts commented
@spinda ping

2017-07-07 13:40 UTC, nightpool commented
@Gargron if it's a nullable value, shouldn't that be very quick to add to the table?

2017-07-07 14:58 UTC, Gargron commented
@nightpool Booleans shouldn't be nullable!

2017-11-17 00:12 UTC, Gargron commented
@ekiru @aschmitz Anyone want to revive this PR in the same style as optional notification muting?

2017-11-17 00:50 UTC, aschmitz commented
Well, not to stomp over this PR, but I did just write up glitch-soc/mastodon#212 for the same feature with much the same UI accidentally. I can make that a PR here too, if you like.

2017-11-28 14:00 UTC, closed without merging