API for updating attribution domains
mastodon/mastodon pull request #32730
Opened 2024-10-31 21:08 UTC by c960657

Add API support for updating attribution domains.

This moves the existing validation and normalization from the dynamic attribute (...`_as_text`) to the “real” database attribute, so it is shared with the API. The text↔array conversion is not used by the API, so this is moved to the controller for the settings page.

This feature may be useful e.g. for online newspapers that want to update the setting for all staff writers.

2024-11-01 13:13 UTC, mjankowski reviewed
If for whatever reason we don't want the API change here, we should pull out the normalization/validation changes and do those.

2024-11-15 14:18 UTC, ClearlyClaire commented
Is `too_many_lines` still used at all? I can't see any sign of it being used, and indeed, trying to add more domains than the maximum, I get the following:
```
Validation failed: Attribution domains is too long (maximum is 100 characters) (ActiveRecord::RecordInvalid)
```

2024-11-17 13:02 UTC, c960657 commented
> Is `too_many_lines` still used at all? 
No, good catch. I have removed it now.

2025-01-08 15:25 UTC, ClearlyClaire reviewed
This looks ok to me, but I'd like to have another pair of eyes on it.

The added request specs should most probably be system specs instead.

There is already a documentation PR (https://github.com/mastodon/documentation/pull/1558) but it may also warrant an API version bump (see `Mastodon::Version.api_version`)

2025-01-08 15:25 UTC, ClearlyClaire commented on spec/requests/settings/verification_spec.rb
This should rather be a system spec, there is already some in `spec/system/settings/verifications_spec.rb`

2025-01-08 16:23 UTC, c960657 commented on spec/requests/settings/verification_spec.rb
I thought that request specs were the current best practice. I can see that new request specs are still being added.

What is the guideline on using system specs vs request specs?

2025-01-08 16:29 UTC, ClearlyClaire commented on spec/requests/settings/verification_spec.rb
Controller specs are discouraged, request specs are preferred for API and low-level HTTP checks, and system specs are preferred for user interaction. In this case, we're testing the settings interface, not the API, so using system specs is useful in asserting that not only the controller does the right thing when sent the right data, but that the right data is sent through the generated form as well!

2025-01-09 07:44 UTC, ClearlyClaire approved these changes, later dismissed

2025-01-09 10:00 UTC, oneiros requested changes
Overall I think this good, thanks a lot.

I did find two more minor problems though. Please have a look at my comments when you have time.

2025-01-09 10:00 UTC, oneiros commented on app/serializers/rest/account_serializer.rb
> +             :group, :created_at, :note, :url, :uri, :avatar, :avatar_static, :header, :header_static,
Adding this here would mean the API would return attribution domains in a lot of places, as this serializer is quite widely used.

As this PR is about changing the value via the `api/v1/accounts/credentials` controller, how about moving this to the `REST::CredentialAccountSerializer` that is used there and only a handful of other (related) places?

2025-01-09 10:00 UTC, oneiros commented on lib/mastodon/version.rb
> +      5
This is actually the release version. The next release will definitely be 4.4, so this is wrong.

You probably meant to change the API version. This is an internal version number our official apps make use of to determine which features the API supports. This is defined a couple of lines below in the `#api_versions` method.

2025-01-09 10:10 UTC, ClearlyClaire commented on lib/mastodon/version.rb
> +      5
Oops, sorry I overlooked that!

2025-01-15 10:39 UTC, oneiros approved these changes

2025-01-15 10:43 UTC, oneiros commented
Thank you for taking the time to consider my remarks. This looks good to me now.

The accompanying docs PR (https://github.com/mastodon/documentation/pull/1558) is no longer accurate after the latest changes. Would you be so kind and update that as well? Thanks!

(Oh, and when you do: The first version this will most probably be introduced in will be 4.4.)

2025-01-17 08:28 UTC, merged