Multiple lines of Content Warning area
mastodon/mastodon pull request #3284
Opened 2017-05-24 18:39 UTC by pfm-eyesightjp

Added change the Content Warning area from Input tag to Textarea tag.
The purpose is to enrich the user's toot expression more.

![cw](https://cloud.githubusercontent.com/assets/28813809/26419676/73cd60a2-40fb-11e7-90ed-62f471712cb3.jpg)

2017-05-24 19:20 UTC, pfm-eyesightjp commented
Travis CI has a problem?
My repository failed the first time and passed the second time.
I have not fixed anything...
https://travis-ci.org/pfm-eyesightjp/mastodon

2017-05-29 03:27 UTC, akihikodaki requested changes
CW is different from the body by nature and has several different features. For example, hashtag is not functioning in CW.
Is there any reason to change _only_ the size of input box, rather than to align the behavior of CW to the body completely or to keep as it is?

2017-05-29 10:57 UTC, pfm-eyesightjp commented
As it stands, CW can only be entered on one line.
The user can not write much description about the body including the spoiler.

The greater embraces the less.

2017-07-12 22:24 UTC, Gargron commented
We would like to not encourage people to write long content warnings. There mustn't be confusion about the equality of content warning and content - they are not equal, content warning has no formatting features. No mentions, hashtags, or links. So I think it should stay a single line input for clarity.

2017-07-12 22:24 UTC, closed without merging