Go to root (home) after login in single user mode
mastodon/mastodon pull request #3289
Opened 2017-05-25 00:51 UTC by knu

In single user mode, visitors are redirected to the single user's profile page.  So, if you are the owner without a session, you start from that page, click the login button and authenticate yourself expecting you'll soon get started with the home page, but in reality you'll get redirected back to where you started from -- your own profile page.

This fixes the behavior by redirecting you home after login if you have started from your own profile page.

2017-05-25 00:59 UTC, ykzts requested changes

2017-05-25 00:59 UTC, ykzts commented on app/controllers/auth/sessions_controller.rb
> +        last_url == short_account_path(username: resource.account))
can you use private method for conditions?

2017-05-25 01:07 UTC, knu commented on app/controllers/auth/sessions_controller.rb
> +        last_url == short_account_path(username: resource.account))
OK.  Do you want the whole condition set to be factored out or just the part after `||` which I added?

2017-05-25 01:14 UTC, ykzts commented on app/controllers/auth/sessions_controller.rb
> +        last_url == short_account_path(username: resource.account))
I think that the whole is desirable.

2017-05-26 11:35 UTC, knu commented
@ykzts It didn't seem very clean to me to extract the whole condition set which actually included two variables (`last_url`<sup>[*](#fn1)</sup> and `resource`), so I made a method to take `resource` and return a list of paths from where user should be redirected to `root_path`.

<a name="fn1"></a>*: `stored_location_for()` is a destructive method you shouldn't call many times, so you have to pass and reuse it.

2017-05-26 12:12 UTC, Gargron approved these changes

2017-05-26 12:13 UTC, ykzts approved these changes

2017-05-26 12:14 UTC, merged

2017-05-26 12:45 UTC, knu commented
Thanks!