Improve default language decision and spec
mastodon/mastodon pull request #3351
Opened 2017-05-27 09:10 UTC by akihikodaki

2017-05-30 13:14 UTC, mjankowski requested changes
The spec coverage improvements are solid.  One comment about the impl change.

2017-05-30 13:14 UTC, mjankowski commented on app/controllers/concerns/localized.rb
> +    http_accept_language.preferred_language_from([env]) ||
This is a lot of conditionals happening in one method...

What about breaking this out to something like...

`request_locale || env_locale || I18n.default_locale`

The impl of `request_locale` would then be like `preferred_locale || compatible_locale` and those methods would then check both the env and available.

2017-06-03 07:48 UTC, akihikodaki commented
062332ae3c30910377ce0e5d7c8b0283dd149e7a applied a change request at https://github.com/tootsuite/mastodon/pull/3351#discussion_r119094822. Sorry for late submission.

2017-06-08 13:56 UTC, mjankowski submitted a review, later dismissed

2017-06-08 13:56 UTC, mjankowski commented on app/controllers/concerns/localized.rb
> +    preferred_locale || http_accept_language
Should this be `preferred_locale || compatible_locale` ?

2017-06-08 13:56 UTC, mjankowski commented on spec/controllers/concerns/localized_spec.rb
> +      default_locale = ENV['DEFAULT_LOCALE']
We could probably use climate_control gem here as well

2017-06-10 04:39 UTC, akihikodaki commented
ba00df7dbfcc8b77cb8272e653a68b5377a2c70d applied https://github.com/tootsuite/mastodon/pull/3351#pullrequestreview-42896370.

2017-06-10 05:48 UTC, Gargron approved these changes

2017-06-10 07:44 UTC, merged