Settings imports
mastodon/mastodon pull request #3360
Opened 2017-05-27 12:13 UTC by akihikodaki

2017-05-30 13:17 UTC, mjankowski requested changes

2017-05-30 13:17 UTC, mjankowski commented on app/controllers/settings/imports_controller.rb
> +    if params[:import].nil?
Can this whole conditional go in a `before_action` check?

2017-05-30 13:17 UTC, mjankowski commented on app/controllers/settings/imports_controller.rb
> +    @import = Import.new(params[:import].permit(:data, :type))
Why move this out of the `import_params` method?

2017-05-30 13:17 UTC, mjankowski commented on app/controllers/settings/imports_controller.rb
> +      return
Try to avoid explicit returns.

2017-05-30 13:17 UTC, mjankowski commented on app/controllers/settings/imports_controller.rb
> +    ImportWorker.perform_async(@import.id)
This change of pulling these out of the `if @import.save` and down here instead doesn't feel like an improvement..?

2017-05-31 08:59 UTC, akihikodaki commented on app/controllers/settings/imports_controller.rb
> +    if params[:import].nil?
I don't know why it should be done in `before_action`. It is a role of `create` to `render :show`.

2017-05-31 08:59 UTC, akihikodaki commented on app/controllers/settings/imports_controller.rb
> +    @import = Import.new(params[:import].permit(:data, :type))
Because the combination of the conditional and the statement is atomic.

2017-05-31 08:59 UTC, akihikodaki commented on app/controllers/settings/imports_controller.rb
> +      return
Yes, but I think it is the best solution for this case. Do you have any other idea?

2017-05-31 08:59 UTC, akihikodaki commented on app/controllers/settings/imports_controller.rb
> +    ImportWorker.perform_async(@import.id)
How could I deal with exception handling then?

2017-05-31 13:17 UTC, mjankowski requested changes
I think you can make all of the added specs here pass with a change to one line in the controller:

```
  def import_params
    params.fetch(:import, {}).permit(:data, :type)
  end
```

2018-03-30 11:02 UTC, closed without merging