Feature refactor timelines reducer
mastodon/mastodon pull request #3686
Opened 2017-06-10 15:03 UTC by Gargron

Fix #3665

2017-06-10 15:33 UTC, ykzts approved these changes
The code looks good.

2017-06-10 15:35 UTC, ykzts commented
@beatrix-bitrot I will ask you to check with the production:smile:

2017-06-10 15:51 UTC, unarist commented
I found some warnings and errors on Chrome console:

```
./app/javascript/mastodon/features/report/index.js
88:24-46 "export 'refreshAccountTimeline' was not found in '../../actions/accounts'
./app/javascript/mastodon/features/report/index.js
93:26-48 "export 'refreshAccountTimeline' was not found in '../../actions/accounts'
```

Also this patch brings back account timeline issue #3447. Second fetching (with since_id) may not return next link, then it prevents load more.

2017-06-10 15:57 UTC, Gargron commented
@unarist `expandTimeline` uses `max_id: ids.last()`, ignoring the `next` path. This is because timelines can be cropped at around 40 items, and if you were using the `next` header, scrolling down again would bring you further and further into the past, skipping past the cropped items. Plus, as far as timelines are concerned `max_id` uses the primary ID

2017-06-10 16:04 UTC, unarist commented
@Gargron `next` path isn't used actually, but existence of it is important, because `handleScrollToBottom()` checks it as `hasMore`.

```
  handleScrollToBottom = () => {
    if (!this.props.isLoading && this.props.hasMore) {
      this.props.dispatch(expandAccountTimeline(Number(this.props.params.accountId)));
    }
  }
```

2017-06-10 16:42 UTC, Gargron commented
@unarist You are right. Perhaps `hasMore` should always be true. That's how it used to be at the very start...

2017-06-10 17:18 UTC, clworld commented
@unarist @Gargron 
I deployed this on my production. (my staging environment does not have enough number of toots…)
This PR reproduces issue https://github.com/tootsuite/mastodon/issues/3447.

2017-06-10 17:49 UTC, clworld commented
I caught some errors in Console.
![timeline](https://user-images.githubusercontent.com/1680550/27005045-a0313616-4e50-11e7-8654-fd0460a3eb81.png)

2017-06-10 19:11 UTC, unarist commented
actions/timelines.js:

```js
export function updateTimeline(timeline, status) {
  return (dispatch, getState) => {
    const references = status.reblog ? getState().get('statuses').filter((item, itemId) => (itemId === status.reblog.id || item.get('reblog') === status.reblog.id)).map((_, itemId) => itemId) : [];
```

`getState().get('statuses')...` has `includes()` method, but `[]` has `include()` method...slightly different name.

And in `updateTimeline()` in reducers/timelines.js...
```
if (status.getIn(['reblog', 'id'], null) !== null) newIds = newIds.filterNot(item => references.include(item));
```

It only works for an array, not for Immutable.Map.

2017-06-10 20:29 UTC, Gargron commented
@unarist @clworld I have fixed the includes typo.

I am surprised if #3447 re-appears again, because expandTimeline does not use next? Let me double check

2017-06-10 20:30 UTC, Gargron commented
Oh wait! The problem is *only* because hasMore *blocks* the loading of more stuff, right?

2017-06-10 21:01 UTC, clworld commented
@Gargron 
I deployed fix and I checked r.include error does not happen.
unarist seems already go to sleep 1.5 hour ago.. (5:55 a.m. now in Japan)

2017-06-11 07:16 UTC, unarist commented
@Gargron

> hasMore blocks the loading of more stuff,

Right. `account/:id/statuses` with `since_id` may returns response without `next` link header, then it overwrites `timelines.['accounts:xxx'].next` with null. This means making `hasMore` to be false, and blocks the loading. We shouldn't overwrite that property on the loading *newer* statuses.

Well, maybe `account/:id/statuses` with `since_id` option should returns next link header, since we don't know there are more records below since_id.

2017-06-11 10:10 UTC, Gargron commented
@unarist Ah, I was thinking of a slightly different scenario. Same bug currently occurs in notification column too:

1. Scroll down to load more posts, or wait until >40 posts are loaded
2. If you are scrolled to top and a new post arrives, all posts after the 40th will be cut off
3. Scroll down again to the bottom to load more posts.

Expected: It will load the posts after the last visible one, without gaps  
Reality: It will load posts after the last invisible one, because that's where the "next" pointed already

So I think that the usage of "next" in the timelines specifically should be removed, and hasMore should always be true.

2017-06-11 12:02 UTC, unarist commented
> hasMore should always be true.

We shouldn't make hasMore *always* true, because it allows the user loading more statuses infinitely (#2066).

Also timelines may have "end" especially on remote account timeline.  So I've changed `accounts/:id:/statuses` API to return `next` link only if needed (#3311), to reduce redundant requests. but If you think handling this is too complicated, how about to set next to true on TIMELINE_REFRESH and keep current behavior on TIMELINE_EXPAND? This allows loading more at least once even on too short timeline, but it's not a huge problem.

Well, maybe we should store boolean value for `next` state instead of link header value itself to prevent misuse...

2017-06-11 12:33 UTC, Gargron commented
@unarist Okay, I think my last commit should take care of the issue. I think I had just accidentally removed the fix that was already there, i.e. only set "next" if previous "next" wasn't set in refreshTimeline (that's the since_id case)

I also found that there was a typo in expandNotifications, which had been there for a long time, and fixed that too.

2017-06-11 12:46 UTC, unarist requested changes

2017-06-11 12:46 UTC, unarist commented on app/javascript/mastodon/actions/notifications.js
>      const lastId = getState().getIn(['notifications', 'items']).last();
Oh, it's whole entity, not id...

2017-06-11 12:54 UTC, clworld commented
@unarist Yes. notifications stop doing load more...

2017-06-11 13:01 UTC, clworld commented
I found glitch reported by beatrix on Discord exists.
It happens when:
1. open Mastodon with home timeline  (scroll position is top of timeline)
2. new toot arrived.
3. Title indicates there is unread toots but scroll position is top of timeline already.
4. After scrolling (scroll down and move to top), unread indicator works good.

2017-06-11 14:57 UTC, Gargron commented
@clworld @beatrix-bitrot @unarist Okay, fixed!

2017-06-11 15:06 UTC, unarist approved these changes

2017-06-11 15:07 UTC, merged