Dispatch scrollTopNotification only if changed
mastodon/mastodon pull request #3700
Opened 2017-06-11 15:52 UTC by unarist

2017-06-13 21:05 UTC, Gargron commented
Perhaps this is a case for debounce? I don't like storing state outside of React (it is against the React philosophy, only acceptable for corner cases)

2017-06-13 21:08 UTC, unarist commented
Ah, I found similar fixes using debounce in our code. I will rewrite with that.

2017-06-23 17:37 UTC, Gargron approved these changes

2017-06-23 17:40 UTC, Gargron requested changes

2017-06-23 17:40 UTC, Gargron commented on app/javascript/mastodon/features/notifications/index.js
> +    dispatchExpandNotifications();
Should be `this.dispatchExpandNotifications()`

2017-06-23 23:52 UTC, unarist commented on app/javascript/mastodon/features/notifications/index.js
> +    dispatchExpandNotifications();
Oops, I've rebased and fixed it.

2017-06-24 00:43 UTC, Gargron approved these changes

2017-06-24 00:43 UTC, merged