Enable filtering toots with visibility
mastodon/mastodon pull request #3793
Opened 2017-06-16 09:21 UTC by almichest

I am a member of developing Naumannni, a kind of mastodon client.

This PR is to filter toots from status API with `visibility` parameter, in order to implement talking on mastodon DM.

Thanks.

2017-06-16 09:22 UTC, pe-ter- commented on spec/controllers/api/v1/accounts/statuses_controller_spec.rb
> +    it 'retures http success' do
not `retures` but `returns`..?

2017-06-16 09:23 UTC, almichest commented on spec/controllers/api/v1/accounts/statuses_controller_spec.rb
> +    it 'retures http success' do
Right. It must be fixed.

2017-06-16 23:13 UTC, Gargron requested changes

2017-06-16 23:13 UTC, Gargron commented on app/controllers/api/v1/accounts/statuses_controller.rb
> +    Status.where(visibility: Status.visibilities[visibility])
You can't do this because it would likely conflict with Status#permitted_for and possibly leak statuses you aren't authorized to view.

2017-06-23 00:31 UTC, pe-ter- commented
Hey @Gargron, now I took over this PR and fixed you pointed out.
What do you think?

2018-03-30 10:49 UTC, Gargron commented on app/controllers/api/v1/accounts/statuses_controller.rb
> +      statuses.merge!(filter_with_visibility_scope(params[:visibility])) if params[:visibility]
When anonymous viewer requests this, the timeline's default filter is "WHERE visibility IN (public, unlisted)", doesn't this essentially replace that, allowing access to "WHERE visibility = private"? This is the main reason I haven't merged this PR, and I don't think I should. This messes with access controls.

2018-03-30 11:02 UTC, closed without merging