Lazy load components
mastodon/mastodon pull request #3879
Opened 2017-06-20 23:44 UTC by sorin-davidoi

Roadmap:
- [x] Display progress bar while fetching bundles
- [x] Routes
   - [x] Lazy load ([react-router guide](https://reacttraining.com/react-router/web/guides/code-splitting))
   - [ ] Loading state
      - [x] Empty column
      - [ ] Move styles to SCSS
   - [x] Replay request (if bundle could not be fetched)
- [ ] Other components - onboarding, video player, gallery...
- [ ] Optimize bundles - perhaps tweak `minChunks`?

2017-06-21 11:58 UTC, sorin-davidoi commented
When a modal bundle could not be fetched, the following is displayed, allowing users to retry the download
![image](https://user-images.githubusercontent.com/2109702/27383045-849885da-5689-11e7-9aa2-b2957458f855.png)

Same thing with route bundles
![image](https://user-images.githubusercontent.com/2109702/27383084-ae5829ac-5689-11e7-93c1-6f195dcfa3dd.png)

2017-06-21 19:40 UTC, sorin-davidoi commented
This reduces the size of `application.js` by 27% (673kB -> 485kb), while creating ~25 extra bundles. The progress bar is being used to show the download progress of each bundle. While the bundle is fetched, it displays a loading state in accordance with the content. If the fetch fails, an error component is shown, which provides a "refresh" button, allowing the user to replay the download.

<img src="https://user-images.githubusercontent.com/2109702/27402982-0257a570-56c9-11e7-843d-ae268eb431a8.png" width="300" />

<img src="https://user-images.githubusercontent.com/2109702/27403085-676acc30-56c9-11e7-8982-3e93a549b375.png" width="300" />

2017-06-21 21:21 UTC, nolanlawson commented
Nice work! Based on the Webpack Bundle Analyzer output, though, it does appear that there are lots of common modules that are repeated throughout the async chunks – `status.js`, `video_player.js`, etc. I suppose WebpackCommonsChunkPlugin doesn't include those if they're included in async chunks? It seems useful to put those in `common.js`, given that there will probably be lots of users who load at least two of home/localTL/federatedTL/accountTL/hashtagTL/etc.

2017-06-22 14:33 UTC, nightpool commented
I'm not sure I see the practical benefit of this—won't it just increase latency on mobile due to the extra round trip requests?

Is there a way to measure whether the decreased bundle size will actually reflect real world usage?

2017-06-22 14:34 UTC, sorin-davidoi commented
It should decrease time to first paint (less JavaScript to parse, which is the main bottleneck on mobile), as well as memory usage. Don't think we are currently measuring those?

2017-06-22 14:37 UTC, sorin-davidoi commented
As a side note, it would be nice to set up Lighthouse integration, to measure these metrics for each PR.

2017-06-22 15:27 UTC, sorin-davidoi commented
Unscientific findings (running Lighthouse against current master and this branch):
 - Performance score: +3 (51 -> 54)
 - Render blocking scripts: -200ms (2070ms -> 1820ms)
 - First paint: -140ms (7060ms -> 6950ms)
 - First interactive: -600ms (7570ms -> 6950ms)

I would prefer to take the average of a few tests but I don't have the time to do it (is there a tool for it?).

2017-06-22 16:25 UTC, nolanlawson commented
> won't it just increase latency on poor connections due to the extra round trip requests?

That can be fixed by adding `<link rel=preload>`s for each of the chunks that we expect are very likely to get loaded by the user. I think this would be a smart addition; @sorin-davidoi you can add it to `application.html.haml` like so:

```haml
%link{:rel => "preload", :as => "script", :src => (asset_pack_path 'application.js')}/
```

Also for your Lighthouse score, what page did you test against? There are a few I think we want to prioritize:

* `/web/getting-started` – main home
* `/web/timelines/home` – mobile PWA home (defined in `manifest.json`)

I also imagine there are people who bookmark local/federated/home timelines, so those would be worthwhile to preload as well.

Overall, I believe it is worthwhile to only load those routes that the user explicitly requested, since it limits overhead of JS parse/exec (and also memory). But avoiding extra network roundtrips is important, and also I'd like to see some deduplication of the shared modules across async chunks.

2017-06-22 16:27 UTC, sorin-davidoi commented
I tested the local timeline (mobile UI). `<link rel=preload>` sounds nice, will try to add them! :+1:

2017-06-22 16:52 UTC, sorin-davidoi commented
I think we could also lazy-load some reducers (see https://stackoverflow.com/questions/32968016/how-to-dynamically-load-reducers-for-code-splitting-in-a-redux-application), but that is a can of worms I don't want to open for now.

2017-06-22 19:04 UTC, beatrix-bitrot commented
Is this ready for review?

2017-06-22 19:05 UTC, sorin-davidoi commented
Just a few final touches to do.

2017-06-22 19:08 UTC, sorin-davidoi commented
Nah, this is it for this PR. @beatrix-bitrot

2017-06-22 20:54 UTC, sorin-davidoi commented
I'd say this is ready for review. Sometimes there is a crash when loading the HomeTimeline (hard to reproduce) which I need to look into, but otherwise, it looks alright.

2017-06-22 22:11 UTC, sorin-davidoi commented
I'd say it is now ready for review.

2017-06-23 05:46 UTC, beatrix-bitrot commented
nice, because it's a big PR and not my area of expertise I will test this branch on glitch.social to make my review

2017-06-23 14:49 UTC, nolanlawson requested changes
Codewise this looks great to me; I just have a few small suggestions. This is also deployed at malfunctioniong.technology (with service worker as well) for those who want to take a look.

2017-06-23 14:49 UTC, nolanlawson commented on app/javascript/mastodon/features/ui/index.js
> +import '../../components/status';
nice fix

2017-06-23 14:49 UTC, nolanlawson commented on app/views/layouts/application.html.haml
> +    = javascript_pack_tag 'features/public_timeline', integrity: true, crossorigin: 'anonymous', rel: 'preload'
These should have `as="script"` as well; it's explained what the browser does with this extra information [here](https://developers.google.com/web/updates/2016/03/link-rel-preload).

2017-06-23 14:50 UTC, nolanlawson commented
In terms of bundle sizes this also looks great. I rebuilt and put a Webpack Bundle Analyzer view [here](http://bl.ocks.org/nolanlawson/raw/c8884382fb17c4cb5e733b8190e900c9/) for those who want to see. (Protip: make a Gist with an index.html and bl.ocks.org can host it for you. :smiley:)

2017-06-25 17:59 UTC, Gargron commented
@nolanlawson Waiting on you to check the changes.

2017-06-27 17:31 UTC, nolanlawson approved these changes
This looks great to me, and is live on malfunctioning.technology to test. (You may need to hard-refresh due to ServiceWorker.)

We may want to warn admins when we ship this that they will probably want to enable HTTP/2 since we are now preloading 13 JS files, which will be slow on HTTP/1 due to the 6-connections-per-origin limit. We may also want to tweak the preloading to limit it to only those components that are guaranteed to be loaded (e.g. "getting started" will only be loaded for first-time users; maybe we can detect that somehow with cookies?).

But those are minor concerns; overall this looks awesome to me and I'm :+1: to merge. I especially love the new `async-components.js` so we can keep all of those components in one place. Great work!

2017-06-29 21:08 UTC, nolanlawson commented
BTW http2 is recommended [in the tootsuite/documentation nginx config](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#nginx) so hopefully most admins already have it.

2017-06-30 14:17 UTC, unarist commented
Component which is loaded before also seem to be lazy loaded.

![image](https://user-images.githubusercontent.com/705555/27738094-670d380e-5de5-11e7-8188-a57252f37bac.png)

I think it can be avoided by caching result of `import()`. (sample: https://github.com/unarist/mastodon/commit/4cf1fde8a2834cc42a2daa46da4d4d3270fef1ba)

![image](https://user-images.githubusercontent.com/705555/27739134-8a011a76-5de8-11e7-84fa-dc52b7f14c30.png)

Pros: avoid flashing of loading view, slightly reduces total time
Cons: single script execution will be longer, i.e. blocks browser longer


How about this?

2017-06-30 14:23 UTC, sorin-davidoi commented
Sounds like a good idea :+1:

2017-06-30 16:21 UTC, nolanlawson commented
Yup sounds like a good tradeoff!

2017-07-04 15:34 UTC, nolanlawson commented
@Gargron I propose we merge this PR along with https://github.com/unarist/mastodon/commit/4cf1fde8a2834cc42a2daa46da4d4d3270fef1ba; it should be a big win for the initial bundle size and I also really like how it cleans up the async route logic. :)

2017-07-07 22:06 UTC, merged

2017-07-08 02:50 UTC, Gargron commented
@sorin-davidoi Please guide me through where the "loading" and "error" views are defined and how to get to see them without a slow connection so I can make sure I like how they look visually.

2017-07-08 09:13 UTC, sorin-davidoi commented
@Gargron Open the Network tab in the Chrome development tools and tick "Disable cache".

For columns:
 - Loading state - Load a timeline, throttle the connection to GPRS, click on a toot.
 - Error state - Load a timeline, tick the "Offline" checkbox, click on a toot. After the error state is shown you can uncheck "Offline" and click retry, the normal page should appear.

For modals:
 - Loading state - throttle the connection to GPRS and open a media modal
 - Error state - tick "Offline" and open a media modal - same behavior with retry