Add notification's time to timeline
mastodon/mastodon pull request #3927
Opened 2017-06-24 11:59 UTC by pfm-eyesightjp

![timeline](https://user-images.githubusercontent.com/28813809/27508429-9958f91c-591f-11e7-8282-1c22d8039437.jpg)
![timeline2](https://user-images.githubusercontent.com/28813809/27508430-9ceacb1e-591f-11e7-9767-47078d569d47.jpg)

2017-06-27 03:41 UTC, akihikodaki requested changes
Thank you for your contribution. I like this feature. I've added a comment.

2017-06-27 03:41 UTC, akihikodaki commented on app/javascript/mastodon/components/status.js
> +            <span className='separator'>-</span>
I think it needs `aria-hidden`.

2017-06-27 13:18 UTC, akihikodaki approved these changes

2017-06-27 13:27 UTC, pfm-eyesightjp commented
Thank you for your review.

This PR is based on @matz 's [opinion](https://mstdn.jp/@matz/22956868).
I agree with his opinion. It is certainly necessary for us.

2017-06-27 13:54 UTC, matz commented
Thank you for taking time to consider my opinion.

2017-08-05 15:53 UTC, nightpool requested changes
Sorry for leaving this PR to linger for so long.

Consensus among the developers was that we **should** expose this information, but right now that area is already somewhat cluttered, and we think adding a title attribute with the relative created_at timestamp is the correct way to proceed here. That way users can still see the information, but it's more of a power-user thing and not as overwhelming, visually, for the casual user. Using a title attribute means users on desktop can see it on hover, and users on mobile could see it on a long-press.

Unfortunately, this was from an informal discussion, and none of us remembered to update this issue with our decision. That really sucks, and I'm sorry that this PR has needlessly been in "limbo" for so long.

2017-08-06 08:58 UTC, pfm-eyesightjp commented
thanks for reply.

> We think adding a title attribute with the relative created_at timestamp is the correct way to proceed here.

Where are you supposed to add title attribute?
I want your advice.

2018-02-07 18:20 UTC, roipoussiere commented
Note: fix #6210

2018-02-07 18:22 UTC, roipoussiere commented
Any news here? I find this PR really useful! It's very disturbing to see only the date of the original post...

2018-06-04 00:28 UTC, closed without merging