#3649 Added option return note in plain text (enoded HTML) in verify_credentials API.
mastodon/mastodon pull request #3988
Opened 2017-06-28 18:20 UTC by debanshuk

In `simplified_format` function (which is used to format HTML note) there is following condition at the beginning:

`return reformat(account.note) unless account.local?`

I have kept the same condition in new `simplified_plain_text_format` function too.

2017-06-28 22:10 UTC, akihikodaki requested changes
I'm not really for this feature. It prohibits future extensions allowed in the federation protocol and causes inconsistency with other APIs.
Applications can still convert HTML into plain text by themselves, which is also compatible for remote accounts. I understand `verify_credentials` does not require to support remote accounts, but I wonder it should have an option for such a limited usage.

Apart from my preference for the feature, I have added some comments, so I'd like you to review them.

2017-06-29 07:29 UTC, debanshuk commented on db/schema.rb
> +    t.index ["status_id"], name: "mentions_status_id_index"
@akihikodaki, I don't remember doing any schema change. Not sure how it got it. I'll remove this.

2017-06-29 11:08 UTC, debanshuk commented
@akihikodaki, I have done changes according to your comments.

2017-06-29 11:20 UTC, akihikodaki submitted a review, later dismissed

2017-06-29 11:20 UTC, akihikodaki commented on app/lib/formatter.rb
> +    raise Mastodon::ValidationError, 'Got remote account. Excepting local.' unless account.local?
Nice. It would be better to tell that `plain` option caused the error.

2017-06-29 15:06 UTC, nightpool commented
Can you lay out the usecase for this? I think allowing clients to discard the formatting users have done on their bios is a pretty bad behavior to encourage.

2017-07-03 06:26 UTC, debanshuk commented
@nightpool, What should be the right way according to your to solve this problem?

2017-07-05 14:48 UTC, nightpool commented
I think the approach in https://github.com/tootsuite/mastodon/pull/4075 is better, but not perfect.

The key distinction here isn't that the account is local—it's that it's an account you can edit, so you need to be able to figure out the specific text used for editing, which is distinct from the text used for display.

My concern with #4075 is that it overloads the existing verify_credentials route, but I think it's much cleaner to add a new property to accounts that you can edit, one that shows the exact note text, to a new route.

2017-07-06 07:41 UTC, debanshuk commented
@nightpool, If I am understanding correctly, you are asking to add a new attribute (something like 'note_plain' or 'note_raw') in the response of verify_creadentials, which can be used for editing and the current 'note' attribute will be used for display purpose only. 

That actually does sound better to me too. 

I can do changes according to this logic.

2017-07-10 01:30 UTC, ykzts commented
Resolved with #4075

2017-07-10 01:30 UTC, closed without merging