Add a setting allowing the use of system's default font in Web UI
mastodon/mastodon pull request #4033
Opened 2017-07-02 07:12 UTC by eramdam

![screen shot 2017-07-02 at 12 08 35 am](https://user-images.githubusercontent.com/1409924/27767905-9d84ff5e-5eba-11e7-80e1-16996e6ae619.png)

This will use the following font stack:
`-apple-system, BlinkMacSystemFont, "Segoe UI", Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Roboto, sans-serif`

In order:
- `-apple-system` for Safari (Helvetica Neue on macOS <10.11 and San Francisco on macos 10.11 and above)
- `BlinkMacSystemFont` same as `-apple-system` but for Chrome/Opera on Mac
- `Segoe UI` for Windows 7/8/10
- Oxygen-Sans, Ubuntu, Cantarell for various Linux distros
- Helvetica Neue, for macOS systems
- Roboto, intentionally put at the very end since we want to use a system native font

2017-07-02 10:08 UTC, sorin-davidoi commented
Could we avoid loading the custom fonts if the option is enabled? That would save 374 KB.

2017-07-02 10:15 UTC, sorin-davidoi commented
What about using [`system-ui`](https://www.chromestatus.com/feature/5640395337760768) (shipped in Chrome and Safari)?

2017-07-02 11:01 UTC, sorin-davidoi commented
I've been wanting to look into this for a while, glad someone beat me to it :+1: 

A couple of questions:
- Could we avoid loading the custom fonts if the option is enabled? That would save 374 KB. If I tick the checkbox, I don't expect Roboto to be used - which might very well mean that it will fallback to `sans-serif` or whatever if all the other fonts are not found.
- What about adding [`system-ui`](https://www.chromestatus.com/feature/5640395337760768) (shipped in Chrome and Safari) as the first font?

2017-07-02 15:50 UTC, eramdam commented
@sorin-davidoi 

1. I'd have to check where we try to load Roboto but that sounds doable
2. I legit didn't know `system-ui` shipped already!

2017-07-02 15:59 UTC, nightpool commented
I'm confused about this implementation. This doesn't work at all if I've changed my system's default font, which seems to kinda defeat the point.

Why not just use font-family: sans-serif; and be done with it? or font-family: none?

2017-07-02 16:01 UTC, nightpool commented on app/javascript/mastodon/features/ui/index.js
> +      className += ' has-system-font';
this would be more cleanly implemented as an array, using classes.join(" ") at the calling site.

2017-07-02 16:01 UTC, sorin-davidoi commented
@nightpool I think Chrome's fonts can be changed in its settings (don't know if it reads them from the OS everytime you launch it or just when you start it the first time).

2017-07-02 16:02 UTC, eramdam commented
@nightpool You'll notice that we're talking about the system's **default** font. Quoting the [specification for `system-ui`](https://drafts.csswg.org/css-fonts-4/#system-ui-def)

> This generic font family is intended to let text render with the **default user interface** font on the platform on which the UA is running.

So if your browser implements `system-ui` or a similar property, I feel like it should still use the default font. I don't have an OS where I can change my default font so I can't test this unfortunately.

2017-07-02 16:11 UTC, nightpool commented
@sorin-davidoi right. But using "Segoe UI" means that, if I was on Windows 10 (or another OS where I happened to have installed Segoe UI for unrelated reasons....), that would override my chrome font choice.

If we want to just use system-ui, then fine. But having the other fonts hard coded seems like a bad decision.

2017-07-02 16:15 UTC, sorin-davidoi commented
@nightpool I agree, it is messy. Github seems to use something similar to this (https://css-tricks.com/os-specific-fonts-css/#article-header-id-0). I would personally be happy with `system-ui`, `BlinkMacSystemFont` and `-apple-system`, but not sure how this will look in browsers / OSs that don't support them.

2017-07-02 16:16 UTC, eramdam commented
The other fonts are merely fallbacks for all the other browsers that don't support `system-ui` just yet. The purpose of the setting is to use a font that "feels native to the OS", as per [specification](https://drafts.csswg.org/css-fonts-4/#system-ui-def). It's messy but we don't have other choices unfortunately (I took inspiration from GitHub's font stack)

>  The purpose of system-ui is to allow web content to integrate with the **look and feel of a native app**. On platforms which have a collection of system user interface fonts (e.g. for different languages), user agents may treat system-ui as a virtual font which encompasses all the platform user interface fonts. However, if this is done, the details of the virtual font must not be visible or detectable.

Keep in mind that whatever font that you choose in the setting of your browser is the fallback used for `sans-serif`, `serif` and `monospace`. Which differs in the way that they could probably not be fonts used in your OS. 

Also, the setting is **disabled by default**, and usually people who would want to enable it know what they're getting into.

2017-07-02 16:37 UTC, sorin-davidoi commented on app/javascript/styles/basics.scss
> +.has-system-font {
Minor nitpick, maybe something like `.system-font` would be better? `has` for me implies that we do some feature detection (e.g. `has-flex`, `has-grid`).

2017-07-02 16:40 UTC, eramdam commented
@sorin-davidoi I tested and Roboto is not loaded (except for the regular family because of the style on [`body`](https://github.com/tootsuite/mastodon/blob/57e7da9a1983fd52e2e6bbb834e099897e94e295/app/javascript/styles/basics.scss#L2)) if it's at the "end" of the stack. Also I can't remove it entirely since Roboto is the default font on newer Android systems.

2017-07-02 16:45 UTC, nightpool commented on app/javascript/styles/basics.scss
> +.has-system-font {
I would name it '.use-system-font'

2017-07-02 16:55 UTC, sorin-davidoi approved these changes
Off by default, saves ~300 KB if enabled :+1:

2017-07-03 11:53 UTC, unarist commented on app/javascript/mastodon/features/ui/index.js
> +      <div className={classNames.join(' ')} ref={this.setRef}>
How about using [`classnames`](https://www.npmjs.com/package/classnames#usage)?

2017-07-03 19:30 UTC, eramdam commented on app/javascript/mastodon/features/ui/index.js
> +      <div className={classNames.join(' ')} ref={this.setRef}>
@unarist I didn't know about that! I'll update the code to use it for consistency.

2017-07-04 06:50 UTC, eramdam commented on app/javascript/mastodon/features/ui/index.js
> +      <div className={classNames.join(' ')} ref={this.setRef}>
@unarist I just pushed a commit to use `classnames`! 👍

2017-07-06 19:28 UTC, Gargron requested changes

2017-07-06 19:28 UTC, Gargron commented on app/javascript/styles/basics.scss
> +  font-family: system-ui, -apple-system,BlinkMacSystemFont, "Segoe UI","Oxygen", "Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue","Roboto", sans-serif;
hey, the webfont for Roboto is actually called "mastodon-font-sans-serif" in our CSS

2017-07-06 20:30 UTC, eramdam commented on app/javascript/styles/basics.scss
> +  font-family: system-ui, -apple-system,BlinkMacSystemFont, "Segoe UI","Oxygen", "Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue","Roboto", sans-serif;
@Gargron I just fixed this. Sorry for the overlooking 😅

2017-07-06 20:36 UTC, Gargron approved these changes

2017-07-06 20:39 UTC, merged