Fixes and improvements for pt-BR translations
mastodon/mastodon pull request #4174
Opened 2017-07-12 17:10 UTC by gerep

2017-07-12 22:03 UTC, ykzts submitted a review, later dismissed

2017-07-13 13:08 UTC, Gargron commented on config/locales/pt-BR.yml
> +    about_mastodon: Mastodon é um servidor de rede social <em>grátis e open-source</em>. Uma alternativa <em>descentralizada</em> às plataformas comerciais, que evita o risco de uma única empresa mon
Could you check the new landing page and adjust this translation accordingly?

2017-07-13 17:11 UTC, gerep commented on config/locales/pt-BR.yml
> +    about_mastodon: Mastodon é um servidor de rede social <em>grátis e open-source</em>. Uma alternativa <em>descentralizada</em> às plataformas comerciais, que evita o risco de uma única empresa mon
Sure! I just noticed that they are really different. I will make the updates ;)

2017-07-13 19:04 UTC, sorin-davidoi commented
I guess #4185 can be included here?

2017-08-01 14:26 UTC, nightpool requested changes
needs review from another Brazilian translator/user.

2017-12-03 09:35 UTC, ykzts commented
The original repository has been lost.

@gerep I close this Pull Request. Please reopen this pull request again when you resume.

2017-12-03 09:35 UTC, closed without merging