Update French locales (landing page & co)
mastodon/mastodon pull request #4261
Opened 2017-07-19 05:43 UTC by eramdam

🥐 🥖 🇫🇷  French speaking contributors rejoice 🇫🇷 🥖 🥐

This PR adds French locales to the landing page that was added recently and everything that came after that.

If you're speaking French, feel free to comment **especially** on the `terms.body_html` string, I'm not 100% sure about the legal phrasing and speech figures to use, so if you're more knowledgeable than me on this field, I'm all ears!

2017-07-19 05:53 UTC, goofy-bz commented on config/locales/fr.yml
> +          desc_html: Permettre à n'importe qui de supprimer leur compte
"n'importe qui" et "leur" ne coincident pas au plan grammatical. Je suggère "Permettre à chacun⋅e de supprimer son compte" par exemple

2017-07-19 05:55 UTC, goofy-bz commented on config/locales/fr.yml
> +        title: Termes et conditions d'utilisations personalisés
typo s/personalisés/personnalisées

2017-07-19 05:58 UTC, goofy-bz commented on config/locales/fr.yml
> +    follow_request: 'Vous avez demandé⋅e à suivre:'
le ⋅e genré est inutile ici car le participe ne peut pas être accordé au sujet dans cette phrase

2017-07-19 05:58 UTC, goofy-bz commented on config/locales/fr.yml
> +    following: 'Youpi! Vous suivez:'
ajouter une espace insécable avant le deux-points

2017-07-19 05:59 UTC, goofy-bz commented on config/locales/fr.yml
> +      title: "%{name} à mis⋅e votre status en favori"
typo s/status/statut

2017-07-19 05:59 UTC, goofy-bz commented on config/locales/fr.yml
> +      title: "%{name} a partagé⋅e votre status"
⋅e genré inutile grammaticalement comme plus haut. aussi : *statut*

2017-07-19 06:02 UTC, goofy-bz commented on config/locales/fr.yml
> +      failed_to_execute: Error d'exécution
trad oubliée Error > Erreur

2017-07-19 06:03 UTC, goofy-bz commented on config/locales/fr.yml
> +      title: Status du compte
en français c'est "statut", ou même "état"

2017-07-19 06:05 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Lors de l'enregistrement sur notre site, il peut vous être demandé de renseigner votre nom et adresse e-mail. Vous pouvez, cependant, visiter notre site sans inscription. Votre adresse e-mail
typo s/vérifié/vérifiée

2017-07-19 06:05 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Lors de l'inscription et de la publication de status, nous enregistrons l'adresse IP de laquelle le(s) status viennent. Nous pouvons également conserver des historiques serveurs qui contiendro
statut

2017-07-19 06:06 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Toute information que nous collectons pourra être utilisée d'une des manières suivantes:</p>
une espace insécable avant deux-points

2017-07-19 06:06 UTC, goofy-bz commented on config/locales/fr.yml
> +      <li>Pour personnaliser votre expérience &mdash; vos données nous aide à mieux répondre à vos besoins individuels.</li>
vos données nous aide > nous aident

2017-07-19 06:07 UTC, goofy-bz commented on config/locales/fr.yml
> +      <li>Afin d'améliorer le support client &mdash; vos données nous aide à mieux répondre à vos requêtes et demandes de support.</li>
aide > aident

2017-07-19 06:09 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Nous appliquons une multitude de mesures de sécurités afin de maintenir la sécurité de vos données personnelles lorsque vous entrez, soumettez, ou accédez à vos données personnelles.</p>
des mesures une seule sécurité donc : "de mesures de sécurité", mais il vaudarit mieux écrire pour éviter l'inutile répétition : "Nous appliquons une multitude de mesures afin de maintenir la sécurité de vos données personnelles"

2017-07-19 06:10 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Oui. Les cookies sont de petits fichiers qu'un site ou prestataires de services transfèrent sur le disque dur de votr ordinateur par le bais de votre navigateur Web (si ce dernier le permet).
typo s/ votr/votre

2017-07-19 06:10 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Oui. Les cookies sont de petits fichiers qu'un site ou prestataires de services transfèrent sur le disque dur de votr ordinateur par le bais de votre navigateur Web (si ce dernier le permet).
typo s/bais/biais

2017-07-19 06:12 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Nous utilisons les cookies pour enregistrer vos préférences pour de futures visites, compiler des données agrégées à propos du traffic et des interactions effectuées sur le site afin de propos
typo traffic > trafic
sur la fin de phrase, erreur de syntaxe
Ces acteurs n'ont > Ces acteurs ont (car "seulement" derrière suffit)

2017-07-19 06:13 UTC, goofy-bz commented on config/locales/fr.yml
> +    <h3 id="disclose">Divulguons-nous des données à des acteurs tiers?</h3>
une espace insécable avant le point d'interrogation, obligatoire en français

2017-07-19 06:15 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Nous n'échangeons pas, ne vendons pas ni effectuons quelconque transferts avec des acteurs tiers d'informations permettant de vous identifier personellement. Cela n'inclut pas les acteurs de c
ajouter "de" avant "quelconque" et ajouter un S final à "quelconque"
personellement > personnellement
"aucune information permettant l'identification de nos visiteurs ne sera divulguées" > divulguée

2017-07-19 06:18 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Nous pouvons être amenés à inclure ou offrir les services ou produits d'acteurs tiers sur notre site. Ces acteurs tiers possèdent leur propre politiques de confidentialité. Nous ne sommes donc
leur propre politiques > politique
responsable > responsables
concernants > concernant

2017-07-19 06:19 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Notre site, nos produits et services sont tous dirigés à l'usage de personnes étant âgés de 13 ans ou plus. Si ce serveur est hébergés aux États-Unis et que vous êtes âgés de moins de 13 ans,
hébergés > hébergé
âgés > âgé⋅e

2017-07-19 06:21 UTC, goofy-bz commented on config/locales/fr.yml
> +    <p>Ce document est distributé sous licence CC-BY-SA. Il a été mis à jour pour la dernière fois le 31 Mai 2013.</p>
typo s/distributé/distribué
la date de 2013 ne devrait-elle pas être modifiée ?

2017-07-19 08:52 UTC, Gargron requested changes

2017-07-19 08:52 UTC, Gargron commented on config/locales/fr.yml
> +    <h2>Politique de confidentialité</h2>
I think the syntax is

```yaml
key: |
  indented as if it's a child
  etc
```

CI seems to choke on this line. (could not find expected ':' while scanning a simple key at line 437 column 5)

2017-07-19 10:14 UTC, ykzts submitted a review, later dismissed

2017-07-19 10:14 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -      {
why delete?

2017-07-19 10:14 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -      {
why delete?

2017-07-19 10:14 UTC, ykzts commented on app/javascript/mastodon/locales/defaultMessages.json
> -      {
why delete?

2017-07-19 10:14 UTC, ykzts commented on app/javascript/mastodon/locales/fr.json
> -  "confirmations.unfollow.message": "Are you sure you want to unfollow {name}?",
why delete?

2017-07-19 10:14 UTC, ykzts commented on app/javascript/mastodon/locales/fr.json
> +  "notifications.column_settings.push": "Notifications",
Why does "push" remove? Here "push" is important.

2017-07-19 15:30 UTC, eramdam commented on app/javascript/mastodon/locales/fr.json
> -  "confirmations.unfollow.message": "Are you sure you want to unfollow {name}?",
@ykzts the `yarn manage:translations` removed those strings automatically so I figured out that they must have been removed from the default locale. I can bring them back if it's an issue.

2017-07-19 15:44 UTC, ykzts commented on app/javascript/mastodon/locales/fr.json
> -  "confirmations.unfollow.message": "Are you sure you want to unfollow {name}?",
```console
$ rm -rf build
$ yarn build:development
$ yarn manage:translations
```

2017-07-19 16:40 UTC, eramdam commented on app/javascript/mastodon/locales/fr.json
> -  "confirmations.unfollow.message": "Are you sure you want to unfollow {name}?",
I'll do that, thanks!

2017-07-22 17:39 UTC, eramdam commented
@Gargron I've fixed the indenting so CI should be fixed now.


@ykzts I've put back the missing messages and re-added `push` on push notifications-related strings

@goofy-bz I've fixed most of the typos you noticed.

While updating my branch with master I've noticed @Sylvhem's PR related to the landing page was merged already. So my PR is mostly about adding missing locales. Will update the title. But @Sylvhem feel free to weigh in if you have any concerns regarding the locales I'm translating 😬

2017-07-22 18:28 UTC, Gargron approved these changes

2017-07-22 18:28 UTC, merged