Allow domain blocks that only reject media without silencing or suspending
mastodon/mastodon pull request #4325
Opened 2017-07-23 21:11 UTC by sdukhovni

Fixes #3489, also #2480

2017-07-23 21:43 UTC, nightpool commented on app/validators/domain_block_validator.rb
> +class DomainBlockValidator < ActiveModel::Validator
seems like this could be much more easily handled by adding a reject_media? method that is defined as (media_only? || @reject_media?)

2017-07-23 21:46 UTC, Gargron requested changes

2017-07-23 21:46 UTC, Gargron commented on app/models/domain_block.rb
> +  enum severity: [:silence, :suspend, :media_only]
I suggest naming it "transparent" or "noop" and having it do absolutely nothing, thus not having to worry about functionality overload with the reject_media boolean.

2017-07-23 21:54 UTC, sdukhovni commented on app/models/domain_block.rb
> +  enum severity: [:silence, :suspend, :media_only]
That's reasonable. Should the menu option still be called "Reject media only" in the frontend?

2017-07-23 22:00 UTC, Gargron commented on app/models/domain_block.rb
> +  enum severity: [:silence, :suspend, :media_only]
No, I think it should be called accordingly (Transparent or No-op). Solves you a lot of trouble, no more need for the validation, even hiding the boolean with JS could be omitted

2017-07-23 22:09 UTC, sdukhovni commented on app/models/domain_block.rb
> +  enum severity: [:silence, :suspend, :media_only]
So we're ok with admins creating domain blocks that are complete no-ops? I guess it doesn't hurt anything, but it seems a little silly...

2017-07-24 12:06 UTC, sdukhovni commented on app/models/domain_block.rb
> +  enum severity: [:silence, :suspend, :media_only]
Completed the renaming, and removed the validation.

2017-07-24 12:26 UTC, Gargron approved these changes

2017-07-24 12:26 UTC, merged