fix(tabs_bar): Allow animation to end before navigating
mastodon/mastodon pull request #4429
Opened 2017-07-28 17:27 UTC by sorin-davidoi

Another hacky solution, similar to #4320.

cc: @unarist @nolanlawson

2017-07-28 17:46 UTC, nolanlawson commented
This solution looks great to me! Is there really not a "React-ish" solution though, like what Twitter describes [here](https://medium.com/@paularmstrong/twitter-lite-and-high-performance-react-progressive-web-apps-at-scale-d28a00e780a3) under "Defer Rendering When Mounting & Unmounting Many Components"? I kinda figured we could just use their same approach of deferring the component.

2017-07-28 17:46 UTC, nolanlawson approved these changes

2017-07-28 17:47 UTC, nolanlawson commented on app/javascript/mastodon/features/ui/components/tabs_bar.js
> +      }, 50);
What's with the debounce? `transitionend` should only be called once, exactly when the transition has ended.

2017-07-28 17:47 UTC, unarist requested changes

2017-07-28 17:47 UTC, unarist commented on app/javascript/mastodon/features/ui/components/tabs_bar.js
> +      const nextTab = e.nativeEvent.path.find(node => node.classList.contains('tabs-bar__link'));
`path` property is not exist in Firefox and Safari.

2017-07-28 17:48 UTC, sorin-davidoi commented on app/javascript/mastodon/features/ui/components/tabs_bar.js
> +      }, 50);
It has `transition: all`, and that class changes like 4 properties, all firing events.

2017-07-28 18:26 UTC, sorin-davidoi commented on app/javascript/mastodon/features/ui/components/tabs_bar.js
> +      const nextTab = e.nativeEvent.path.find(node => node.classList.contains('tabs-bar__link'));
Today I learned :+1:

2017-07-28 18:28 UTC, unarist approved these changes

2017-07-28 19:10 UTC, sorin-davidoi commented
@nolan Will give it a shot but last time I checked the biggest bottleneck was not the rendering but the unmounting of the all the component on the page.

2017-07-28 20:55 UTC, merged

2017-07-29 08:25 UTC, unarist commented
> Another problem is the animation. We would have to delay the mounting of the component not by animation frame, but by the duration of the transition (200ms).

I've missed this point, and yes, this change looks more laggy on the PC...

2017-07-29 10:35 UTC, sorin-davidoi commented
We could wrap it inside isUserTouching, like the actions modal.

2017-07-29 10:44 UTC, unarist commented
Although I don't think that feeling is not depending on whether it's PC or mobile device, but device performance or something.

2017-07-29 11:12 UTC, sorin-davidoi commented
Yes, but I would say that whether the device is touch or not is strongly correlated to the performance of the device. Don't know what to say, let's leave it as it is for now and hear more feedback?

2017-07-29 16:48 UTC, unarist commented
I found a odd behavior.

1. Open home column
2. Touch home tab, and just after, touch notification tab
3. It will show notification column in a moment, then back to home column

<details>
<summary>demo gif (w/ event timing log)</summary>

![test](https://user-images.githubusercontent.com/705555/28746494-60d3a438-74c8-11e7-8968-e615a7138f7e.gif)
</details>