i18n: Update Polish translation
mastodon/mastodon pull request #4479
Opened 2017-08-01 11:46 UTC by m4sk1n

2017-08-01 12:59 UTC, Gargron requested changes

2017-08-01 12:59 UTC, Gargron commented on config/locales/pl.yml
> +  application_mailer
Missing `:`

2017-08-01 14:24 UTC, nightpool commented
Needs review from another polish translator/user.

2017-08-01 15:27 UTC, ykzts commented
https://github.com/tootsuite/mastodon/commits/master/config/locales/pl.yml

@m4sk1n and @rysiekpl ?

2017-08-01 15:29 UTC, m4sk1n commented
Thanks for assigning me to review my translation ;)

2017-08-01 15:33 UTC, ykzts commented on config/locales/pl.yml
> +      subject: "%{name} wspomniał o Tobie"
What is the change in this line?

2017-08-02 21:14 UTC, m4sk1n commented on config/locales/pl.yml
> +      subject: "%{name} wspomniał o Tobie"
Because it looks more natural for me

2017-08-03 15:49 UTC, Gargron approved these changes

2017-08-03 15:49 UTC, merged