It makes no sense to try using invalid or expired link again
mastodon/mastodon pull request #4521
Opened 2017-08-04 15:30 UTC by m4sk1n

2017-08-04 15:55 UTC, ykzts commented
ref https://github.com/tootsuite/mastodon/pull/4509#discussion_r131385758

2017-08-05 03:26 UTC, nullkal requested changes

2017-08-05 03:26 UTC, nullkal commented on config/locales/en.yml
> +    invalid_reset_password_token: Password reset link is invalid or expired. Have you already used it?
As per https://github.com/tootsuite/mastodon/blob/8d6c3cd48ae4f96752ff6b698bc7244d97aa9a27/config/initializers/devise.rb#L230, password reset token expires in 6 hours without consume it. I think "Please request a new one." is better.

2017-08-07 10:42 UTC, ykzts commented
resolve conflicts.

2017-08-07 15:18 UTC, m4sk1n commented
@ykzts done

2017-08-07 15:19 UTC, ykzts approved these changes

2017-08-07 15:20 UTC, merged