Add link to 'noscript' message
mastodon/mastodon pull request #4561
Opened 2017-08-08 20:25 UTC by m4sk1n

2017-08-08 22:54 UTC, ykzts approved these changes

2017-08-09 23:51 UTC, Gargron requested changes

2017-08-09 23:51 UTC, Gargron commented on config/locales/fa.yml
> -    noscript: برای استفاده از نسخهٔ تحت وب ماستدون، لطفاً جاوااسکریپت را فعال کنید. یا به جایش می‌توانید یک اپ ماستدون را به‌کار ببرید.
You have removed many translations which could be kept.

2017-08-10 06:26 UTC, m4sk1n commented on config/locales/fa.yml
> -    noscript: برای استفاده از نسخهٔ تحت وب ماستدون، لطفاً جاوااسکریپت را فعال کنید. یا به جایش می‌توانید یک اپ ماستدون را به‌کار ببرید.
but I renamed noscript to noscript_html

2017-08-10 11:40 UTC, Gargron commented on config/locales/fa.yml
> -    noscript: برای استفاده از نسخهٔ تحت وب ماستدون، لطفاً جاوااسکریپت را فعال کنید. یا به جایش می‌توانید یک اپ ماستدون را به‌کار ببرید.
These could be renamed to noscript_html

2017-08-11 19:19 UTC, m4sk1n commented on config/locales/fa.yml
> -    noscript: برای استفاده از نسخهٔ تحت وب ماستدون، لطفاً جاوااسکریپت را فعال کنید. یا به جایش می‌توانید یک اپ ماستدون را به‌کار ببرید.
@Gargron, now should be fine

2017-08-13 00:09 UTC, ykzts commented on config/locales/ru.yml
> -    noscript: Для работы с Mastodon, пожалуйста, включите JavaScript.
`noscript_html`

2017-08-13 00:13 UTC, ykzts requested changes

2017-08-13 00:13 UTC, ykzts commented on config/locales/ko.yml
> -    noscript: Mastodon을 사용하기 위해서는 JavaScript를 켜 주십시오.
`noscript_html`

2017-08-13 00:13 UTC, ykzts commented on config/locales/ja.yml
> +    noscript_html: Mastodonのウェブアプリケーションを利用する場合はJavaScriptを有効にしてください。またはあなたのプラットフォーム向<a href="https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md">けのMastodonネイティブアプリ</a>を探すこと
broken Japanese translate.

Do not add the A tag except for the locale you know (the translator for each language should do it).

2017-08-13 00:13 UTC, ykzts commented on config/locales/ca.yml
> -    noscript: Per utilitzar Mastodon si us plau activa JavaScript.
`noscript_html`

2017-08-13 18:37 UTC, m4sk1n commented on config/locales/ja.yml
> +    noscript_html: Mastodonのウェブアプリケーションを利用する場合はJavaScriptを有効にしてください。またはあなたのプラットフォーム向<a href="https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md">けのMastodonネイティブアプリ</a>を探すこと
Ok

2017-08-13 20:00 UTC, m4sk1n commented on config/locales/ca.yml
> -    noscript: Per utilitzar Mastodon si us plau activa JavaScript.
@ykzts now?

2017-08-25 04:25 UTC, akihikodaki approved these changes

2017-08-25 14:08 UTC, ykzts commented on config/locales/ja.yml
> +    exports:
indent?

2017-08-27 23:18 UTC, ykzts approved these changes
has been fixed

2017-08-31 23:27 UTC, ykzts commented
@Gargron I think that this was corrected enough. What about you think.

2017-09-01 23:48 UTC, Gargron approved these changes

2017-09-01 23:52 UTC, merged