Don't wipe compose box content on mention or reply
mastodon/mastodon pull request #4579
Opened 2017-08-11 12:46 UTC by MightyPork

This is an effort to preserve text and settings of the compose box when the reply or mention button is pressed. Handles are prepended if missing.

Currently, the content is wiped, possibly destroying what text user might have had there before, perhaps preparing to reply. 

One situation to illustrate the problem - Alice makes a typo and deletes her post, then re-sends it with corrections. Meanwhile, Bob was typing a reply, but the old post vanished, and the new one appeared. Bob clicks reply on the corrected post, but his compose box is wiped in the process, deleting his reply.

If there are still issues to be addressed, let me know.
If this has no chance of being merged, also please tell me. I'll re-submit it to the glitch-soc fork.

2017-08-14 22:20 UTC, nightpool commented on app/javascript/mastodon/reducers/compose.js
> +function addMentions(state, mentionsStr) {
There's no reason to take all of "state" here if you're only using `'text'`

2017-08-18 10:15 UTC, MightyPork commented
I don't mean to sound impatient, but is there still something wrong?

2017-08-22 12:36 UTC, akihikodaki requested changes
Sorry for keeping you waiting. I have found a point which can be improved. I hope your change would land soon.

2017-08-22 12:36 UTC, akihikodaki commented on app/javascript/mastodon/reducers/compose.js
> +  for (const m of mentionsStr.split(' ')) {
Use `Array.prototype.filter`.

2018-10-20 00:38 UTC, Gargron commented
Resolved by #8893

2018-10-20 00:38 UTC, closed without merging