Add GitHub Url library
mastodon/mastodon pull request #4657
Opened 2017-08-21 22:17 UTC by lnanase

Mastodon Github repository URL replace to dynamic library file.
All Other instance need to do is change library file.

(Similar pull request #4643. Sorry, @zunda .)

Thank you.

2017-08-21 22:32 UTC, zunda commented
This looks better and more consistent than #4643 for me! I wonder if it is possible to insert a shim to represent tag/branch/commit hash in `Mastodon::Github` so that instances following the master branch can specify tag/branch/commit hash when appropriate.

2017-08-21 22:37 UTC, nightpool commented
-1 to tying this to github, tentative -1 to changing the onboarding modal since it's talking about mastodon the project and not just the source code/any instance customizations, +1 for everything else.

2017-08-21 23:18 UTC, zunda commented
Ah gothca. It is too consistent to change URL on onboarding modal.

2017-08-22 12:21 UTC, akihikodaki requested changes
It is a good idea to extract brand-related information from the code base, but this pull request actually spreads the information that Mastodon is hosted on GitHub over the code base. Please be aware that others, and the upstream in future may use other hosting services.

2017-08-22 12:21 UTC, akihikodaki commented on lib/mastodon/github.rb
> +    def to_s
Should be named `link_url` or something like that. There is no actual reason that the link title is not `to_s` and the URL is not `link_url`. Name them in a consistent rule then.

2017-08-23 12:14 UTC, Gargron commented
I chose #4643 because it's less brand attached and more general (sorry)

2017-08-23 12:14 UTC, closed without merging

2017-08-23 12:54 UTC, akihikodaki commented
#4643 does not include JavaScript side while this pull request does. The addition of JavaScript side would be appreciated.
If you are willing to implement that, I suggests to have a YAML shared by Rails and webpack.
See `config/webpacker.yml` to load a YAML in webpack. [webpack's DefinePlugin](https://webpack.js.org/plugins/define-plugin/) would allow to expose it to the bundled scripts.
For Rails, you may let `Mastodon::Version` extend with `RailsSettings::Default` class.