Allow columns to be wider on large screen.
mastodon/mastodon pull request #4663
Opened 2017-08-22 18:36 UTC by Aldarone

This line make the columns take full width on large screen but still allow horizontal scrollbar on small screens or when there is to much of them.

2017-08-22 18:39 UTC, Aldarone commented
(Screenshots incoming)

2017-08-22 18:55 UTC, wxcafe commented
imo this feature needs a toggle in the settings -- I personally definitely don't like the wide columns.

2017-08-22 18:56 UTC, ElkoHRH approved these changes

2017-08-22 19:11 UTC, nightpool commented
1. this doesn't affect the left-hand drawer, should it?
2. On cybre.space we allow the columns to resize between 400 and 330 px. This is a pretty good compromise between usability (long text lines are hard to read) and flexibility. Would be interested to hear @Gargron's thoughts on this.

2017-08-22 23:25 UTC, nightpool requested changes
probably needs at least *some* max-width, although we can bikeshed the specific px value

2017-08-23 04:36 UTC, clarcharr commented
> On cybre.space we allow the columns to resize between 400 and 330 px. This is a pretty good compromise between usability (long text lines are hard to read) and flexibility. Would be interested to hear @Gargron's thoughts on this.

TBQH I would very much like to see these changes made to cybre.space backported to upstream, gated by features as necessary.

2017-08-24 00:02 UTC, badosu commented
Even if the wider columns are not accepted please just center the application so it's easier to read on large displays.

2017-10-14 13:23 UTC, lostinlight commented
Small change that makes a big difference :)

On a 1440 wide screen now:
![screen preview without change](https://framapic.org/mQcb0aJkjbLV/BIKYt5ApwzvY.png)

I am manually setting flex of .drawer & .columns to '0 1 25%' instead of fixed px width. Would be great to see Aldarone's PR merged. 
![screen preview with change](https://framapic.org/CkQa1il9WB5D/KnFy9MEb5xMI.png)
 
Centering the wrapper in case wider columns aren't accepted, would *really* be helpful! 
`.ui {align-items: center}`

2018-03-19 01:34 UTC, Gargron commented
>imo this feature needs a toggle in the settings -- I personally definitely don't like the wide columns.

Agree with this. Will accept a variant of this behind a preference.

2018-03-19 01:34 UTC, closed without merging

2018-03-22 15:52 UTC, wxcafe commented
There's one in glitchsoc, maybe we could just merge the code

2018-03-22 18:45 UTC, trwnh commented
For legibility, it's pretty widely accepted that lines of text should be 45-75ch wide. I understand cases where perhaps a user will want to override this, but at that point they may as well start setting their own custom CSS. I personally use 75ch as a width, on a 2560px wide monitor.

Alternatively, zooming in works wonders for making the columns wider, if you also don't mind having larger text.