Adjust toot button style
mastodon/mastodon pull request #4736
Opened 2017-08-29 19:46 UTC by lynlynlynx

I think this way is better than #4723 "fix toot button text be hidden when img pasted"

##  Pros

- **Solve ellipsis of toot buttons in some languages whose translation is long**

- Enlarge Formosan toot buttons

##### Before and after images below.
![ba4](https://user-images.githubusercontent.com/27640522/29838157-55d881ea-8d35-11e7-8e89-954550b1750e.png)

## Cons

- **Padding becomes smaller in some languages**
I wonder if we prioritize usual(image is not attached) appearance or not :thinking:
Anyone has good way to solve this cons? Variable padding?
- **Can't solve ellipsis of all languages**
Bulgarian and Ukrainian image is attached.
Spanish and Portuguese image is attached in private or direct toots.
I think there is no way to solve this except increasing column width. :man_shrugging: 

##### Before and after images below.

Padding becomes smaller in some languages
![ba5](https://user-images.githubusercontent.com/27640522/29838166-5d7b5a58-8d35-11e7-8574-5c0e7c94ad91.png) 
To put it the other way around.
![ba8](https://user-images.githubusercontent.com/27640522/29839236-79252b1e-8d38-11e7-98ec-4f3d0a8b45d0.png)

Can't solve
![ws000053](https://user-images.githubusercontent.com/27640522/29840389-d32ae7d0-8d3c-11e7-988c-f98eb7a58489.png) ![ws000054](https://user-images.githubusercontent.com/27640522/29840387-d32109c2-8d3c-11e7-8cdf-30b589743353.png) ![ws000055](https://user-images.githubusercontent.com/27640522/29840388-d322d914-8d3c-11e7-8ace-8f57b2ec5a84.png)

----

The appearance is almost same for languages use "TOOT" as "compose_form.publish".
![ba7](https://user-images.githubusercontent.com/27640522/29838720-f0f9d510-8d36-11e7-8325-6a9ce7eeadbd.png)

2017-09-09 03:52 UTC, matyapiro31 approved these changes

2017-09-18 05:17 UTC, akihikodaki approved these changes

2017-09-18 11:44 UTC, nightpool requested changes
Why not just use flexbox to change the padding based on how much space is available? 

At a minimum, we should never use !important styles unless something is very wrong with our selectors

2017-10-01 10:35 UTC, matyapiro31 commented
flexbox is not stable technology now, there are some difference among browsers remained, and also there is no reason why using padding isn't better than flexbox.
I agree with removing  `!import`.

2017-10-03 16:10 UTC, nolanlawson commented
@matyapiro31 We don't support IE at all, and IE is the browser with the v1 version of flexbox. I think given we're essentially supporting latest Chrome/Edge/Firefox/Safari, [it's safe to use flexbox](http://caniuse.com/#feat=flexbox). Furthermore, we already use flexbox in several places in the codebase. :smiley:

2017-11-27 15:18 UTC, mattcoxonline commented
<img width="1584" alt="screen shot 2017-11-27 at 16 13 48" src="https://user-images.githubusercontent.com/673542/33273605-145f72c4-d38e-11e7-98fa-7a2deca50046.png">

I started to tweak the padding and text size around the tootbox to see how things fit. And a small reduction in font size / icon sizes and maintaining an equal padding either side of the button seems to work quite well.

There's also the option for longer toot buttons to force the icon set to the left to collapse behind an elipses. This also forces you to take the decision on what is the primary action you want people to do; CW vs upload media vs other stuff.

However, we have a lot of space in the left column and I'm not sure why the grey strip of buttons does't run the full width of the input box? Maybe too crazy a suggestion.

2017-11-27 22:55 UTC, lynlynlynx commented
Full-width textbox seems really nice to me.
I got stuck with this pull request, so I'll close it.
Would you create new request? @mattcoxonline

2017-12-07 19:09 UTC, closed without merging