Redesign video player
mastodon/mastodon pull request #4911
Opened 2017-09-12 20:06 UTC by Gargron

2017-09-13 13:25 UTC, unarist commented
- thumbnail -> expand -> fullscreen: works
- thumbnail -> fullscreen: empty fullscreen...?

2017-09-13 13:27 UTC, Gargron commented
@unarist Cannot confirm, works fine both ways (Firefox 55, Linux)

2017-09-13 13:36 UTC, unarist commented
Hmm, I've confirmed working on Edge and Firefox, but the issue occurs on Chrome 61 on Windows.

Also the player always fill the screen on Edge and Firefox, but it will be in original video size at a maximum on Chrome.

2017-09-13 13:55 UTC, Gargron commented
@unarist Okay, should be fixed now

2017-09-13 14:19 UTC, Gargron commented
I have also added Aria labels to the buttons on the player

2017-09-13 14:23 UTC, unarist commented
Sizing seems still prevent by max-width/height on `.media-modal video`:

https://github.com/tootsuite/mastodon/blob/283a5ec1a4b4c771e36e5ad50f6e7c425fcfc4f7/app/javascript/styles/components.scss#L3063-L3073

and empty fullscreen issue is still exists on Chrome. I also investigating this, but no hints yet...

2017-09-13 23:32 UTC, Gargron commented
@unarist Can I merge this? 😅

2017-09-13 23:58 UTC, unarist requested changes

2017-09-13 23:58 UTC, unarist commented on app/javascript/styles/components.scss
> +    height: 100%;
`!important` is needed to override inline styles. Firefox has those styles in UA stylesheet.

also this can be merged into `&.fullscreen`?

2017-09-14 00:27 UTC, unarist commented on app/javascript/styles/components.scss
> +    height: 100%;
and add `margin: 0` to override `margin-top` on `.status .video-player`.

2017-09-14 01:13 UTC, Gargron commented
@unarist Done!

2017-09-14 01:26 UTC, unarist approved these changes

2017-09-14 01:26 UTC, unarist commented
BTW, currently I can't hide controls on fullscreen? Hiding it a little while after user stops mouse movement would helps I think.

Although, it's not a blocking issue, so fixing in subsequent PRs.

2017-09-14 01:39 UTC, merged