Add support for multiple themes
mastodon/mastodon pull request #4959
Opened 2017-09-15 08:26 UTC by Chronister

Many non-flagship instances wish to differentiate themselves by providing customized themes for mastodon. However, not all users may necessarily appreciate the changes these themes make (and simply not using that instance may not be an option if they are deeply connected in the community). Furthermore, flagship may wish to someday provide alternate themes (such as a light theme) for accessiblity or preference reasons. This PR provides baseline support for this capability:

 - Add `config/themes.yml` where instance administrators can list out a series of theme names and paths
 - Refactor the webpack pipeline to package each listed theme separately
 - Change the application layout to use the package corresponding to the user's selected theme
 - Provide a ruby interface to the theme list in `app/lib/themes.rb`
 - Add a <select> field on the user preferences page, populated with the themes the instance provides

2017-09-15 08:52 UTC, Chronister commented
Closing until I fix the Nil default preference issue that's causing the travis build to fail

2017-09-15 15:01 UTC, nightpool commented on app/javascript/packs/common.js
>  // import default stylesheet with variables
this comment is now out of date.

2017-09-16 09:22 UTC, lynlynlynx commented
LGTM 👍 
I tested this pull request, and this works really nice.
At long last, we can now add high contrast theme as secondary default theme!

This pull request is related to #2028 and #2280 .

2017-09-16 09:30 UTC, unarist requested changes
* Since themes may be deleted in the future, then we should fallback to default theme. Currently it causes an error page.
* I think each theme should have "display name". It allows admins to change display name without breaking their current preference.

2017-09-16 09:30 UTC, unarist commented
and personally, I'd like to place that dropdown to next to language selection, like Kirakiratter does:

![image](https://user-images.githubusercontent.com/705555/30511082-9322bb9e-9b0c-11e7-97f4-51bcc9fcf30b.png)

2017-09-16 23:45 UTC, nightpool commented
Currently on cybre.space having win95 enabled breaks the admin page:

![image](https://user-images.githubusercontent.com/233815/30516816-767c0e04-9b17-11e7-8fa5-8f6e048ea300.png)

not sure whether this should be considered a bug in this PR or not.

2017-09-16 23:46 UTC, nightpool commented on app/views/layouts/application.html.haml
> +    = stylesheet_pack_tag (current_account&.user&.setting_theme || Setting.default_settings['theme']), media: 'all'
law of demeter violation. this should probably be a method in ApplicationController instead

2017-09-16 23:51 UTC, nightpool requested changes

2017-09-16 23:51 UTC, nightpool commented on app/lib/themes.rb
> +    @conf = YAML.load_file(Rails.root.join('config', 'themes.yml'))
can't remember if this needs to be frozen or not in modern rails

2017-09-16 23:51 UTC, nightpool commented on app/models/user.rb
> +    settings.theme
alternatively could do fallback here but that seems less good.

2017-09-16 23:51 UTC, nightpool commented on app/views/layouts/application.html.haml
> +    = stylesheet_pack_tag (current_account&.user&.setting_theme || Setting.default_settings['theme']), media: 'all'
law of demeter violation. also, this is just a little bit too complex of code. this should probably be a method in ApplicationController or something instead. you could handle fallback there too.

2017-09-16 23:51 UTC, nightpool commented on config/locales/simple_form.en.yml
> +        setting_theme: Theme
Might need to be a bit more verbose.

2017-09-17 16:17 UTC, lynlynlynx requested changes

2017-09-17 16:17 UTC, lynlynlynx commented on app/views/layouts/application.html.haml
> +    = stylesheet_pack_tag (current_account&.user&.setting_theme || Setting.default_settings['theme']), media: 'all'
Please be sure to add theme dependent `stylesheet_pack_tag` to embedded.html.haml as well.

2017-09-18 02:59 UTC, Chronister commented
As of 8780db68f7f93ca576984554066bdfe01c2ae778, we now:
 - check current user's theme in ApplicationController
 - check there if the current user's theme is a known theme and return the configured default if not
 - look up theme names in the internationalization strings (falling back to the raw theme name if unavailable), so these can both be different from what's in themes.yml and localized to other languages
 - show a hint explaining the scope and effect of the theme setting
 - show the theme setting at the top of the preferences, above language (negotiable -- it may make more sense to visually group it with accessibility or display settings, or move these out into their own tab entirely)
 - use current_theme in embedded.html.haml

2017-09-18 04:34 UTC, akihikodaki commented on app/controllers/application_controller.rb
> +      return current_account&.user&.setting_theme
I do not think it needs `&.` operator here. If they gets `nil`, it is a programming error and should fail rather than returning `nil`.

2017-09-18 07:58 UTC, lynlynlynx submitted a review, later dismissed

2017-09-18 09:30 UTC, Chronister commented
oops, i should look into why codeclimate says things before making changes. looks like 'and' and '&&' have different precedence.

2017-09-18 10:10 UTC, unarist requested changes

2017-09-18 10:10 UTC, unarist commented on app/views/layouts/embedded.html.haml
> +    = stylesheet_pack_tag current_theme, media: 'all'
In most cases, embeds will be seen by non-logged in users. So I think it should be fixed to default theme, and it shouldn't be changed by user preferences.

2017-09-18 11:23 UTC, nightpool commented on app/controllers/application_controller.rb
> +      return current_account&.user&.setting_theme
should just be current_user, right?

2017-09-18 11:25 UTC, nightpool commented on app/controllers/application_controller.rb
> +      return current_account&.user&.setting_theme
I *think* this should cover most cases and make more sense?

```ruby
return Setting.default_settings['theme'] unless Themes.instance.names.include? current_user&.setting_theme
return current_user.setting_theme
```

2017-09-18 11:27 UTC, nightpool submitted a review, later dismissed
LGTM modulo changing embedded.html.haml to use only the default theme and fixing the current_user issue

2017-09-19 12:49 UTC, unarist approved these changes

2017-09-19 13:58 UTC, akihikodaki approved these changes
Approving but have a non-blocking comment.

2017-09-19 13:58 UTC, akihikodaki commented on app/controllers/application_controller.rb
> +    return Setting.default_settings['theme'] unless Themes.instance.names.include? current_user&.setting_theme
I think `return current_user.setting_theme if Themes.instance.names.include? current_user&.setting_theme` is easier to understand.

2017-09-19 14:36 UTC, merged