Configure webpack to poll for changes in development
mastodon/mastodon pull request #5040
Opened 2017-09-22 12:56 UTC by aschmitz

Vagrant on Linux/macOS hosts shared files via NFS, which doesn't support inotify-based watching of files. This tweak makes webpack check for changes every second, and rebuild if necessary. This removes the need to restart Foreman every time a frontend file changes. Note that rebuilding is still a relatively lengthy process.

The polling frequency can be changed to taste.

2017-09-22 12:58 UTC, aschmitz commented
See also #4961 as the related issue.

2017-09-22 13:11 UTC, nightpool commented
Is there a way to configure this so that it only happens on NFS based systems? Or, at least, does this override or complement the inotify behavior?

2017-09-22 13:51 UTC, aschmitz commented
I hadn't actually investigated that, but it makes sense that some
developers would run this outside of Vagrant. Digging in a bit, webpack
delegates this to watchpack, which passes it off to chokidar.

It looks like setting `poll` does indeed force polling in at least one case
(macOS), so it's probably polite to avoid that where not necessary.

The config file for webpack is fully JavaScript, so we could attempt some
sort of detection there before setting the `poll` property, although I'm
not sure how to detect NFS off the top of my head. Alternatively, it looks
like setting the `CHOKIDAR_USEPOLLING` and `CHOKIDAR_INTERVAL` environment
variables would trigger the same behavior, and there may be a way of having
that happen only in Vagrant.

I'll think about how to best detect that and update this. Suggestions are
obviously welcome too.

2017-09-30 13:59 UTC, Gargron requested changes
Make this controlled by an env variable, and set this env variable from the Vagrant box/definition

2017-09-30 14:12 UTC, aschmitz commented
Would it be sufficient to reuse the `VAGRANT` environment variable that's set in `.env.vagrant` , or should we add another variable to make it clearer for non-Vagrant users who want the same functionality?

2017-09-30 15:16 UTC, Gargron commented
Sure, use `VAGRANT`. Wasn't aware it exists 😅

2017-10-04 07:52 UTC, Gargron approved these changes

2017-10-04 07:52 UTC, merged