Use nullDB during asset compilation
mastodon/mastodon pull request #5127
Opened 2017-09-28 03:55 UTC by danhunsaker

This change allows Nanobox users to continue deploying Mastodon instances, and also speeds up the asset compilation phase for other users who might want it. It adds the ActiveRecord nullDB driver, and lets users switch to it by setting an environment variable (`DB_ADAPTER=nulldriver`), which can be done as part of the `rake assets:precompile` command. For Nanobox users, it relieves the need for an actual database connection during the `compile` step (part of the deploy process which prepares the code for upload to the server). For all users, it speeds up asset compilation by converting all DB calls to no-ops, which is considerably faster than talking to an actual Postgres DB during a phase which doesn't actually need DB access to begin with (even though Rails loads itself entirely for the process anyway).

2017-09-28 05:50 UTC, nullkal commented
After #5067, `assets:precompile` requires the true database connection.

2017-09-28 05:52 UTC, nullkal requested changes
After #5067, `assets:precompile` requires the *true* database connection.

This is because the generation of 500 error page use the instance name in the database after that.

2017-09-28 06:38 UTC, danhunsaker commented
OK, fair enough. I'll adjust the PR to also re-run the `bundle exec rake assets:generate_static_pages` task after the DB is accessible. That's the only portion that needs DB access, yes?

2017-09-28 07:04 UTC, nullkal approved these changes

2017-09-28 11:39 UTC, nightpool commented
Wait, which part of 5067 requires the database? I compile my assets locally
and upload them—am I going to run into issues?

On Thu, Sep 28, 2017 at 3:04 AM nullkal <notifications@github.com> wrote:

> *@nullkal* approved this pull request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tootsuite/mastodon/pull/5127#pullrequestreview-65767547>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAORV6lnlmth7lfqHj6nev2zFmQ_urXzks5sm0TtgaJpZM4Pmsdq>
> .
>

2017-09-28 12:07 UTC, Gargron commented
@nightpool #5099 adds `Setting.site_title` call to the `<title>` of the error page layout.

I thought people would like that. I believe that maybe it should be removed now though.

2017-09-28 14:39 UTC, danhunsaker commented
Not sure why Travis builds are failing, here... Thoughts?

2017-09-29 01:04 UTC, Gargron commented
Okay i removed the need for db in master

2017-09-30 03:36 UTC, nightpool commented on boxfile.yml
> +    - bundle exec rake assets:generate_static_pages
this can be removed.

2017-09-30 04:46 UTC, danhunsaker commented on boxfile.yml
> +    - bundle exec rake assets:generate_static_pages
Commit removed.

2017-09-30 05:55 UTC, nightpool commented
Looks like Travis is still failing, although I'm not 100% sure why. Do those commands work locally on your computer?

My current working theories are either 1) the DB_ADAPTER environment variable isn't falling back to postgres correctly or b) the nulldb adapter itself is interfering with the schema load process.

2017-09-30 06:15 UTC, danhunsaker commented
I'll double check that in a bit. Away from the keyboard for the moment.

2017-10-03 02:49 UTC, akihikodaki commented
For anyone interested in the test failure: you can reproduce it with the following command:
```shell
RAILS_ENV=test ./bin/rails db:abort_if_pending_migrations
```

2017-10-03 06:16 UTC, akihikodaki requested changes
I figured out what is wrong with CI and how to fix.
You should prevent from requiring the adapter in `config/application.rb` if `DB_ADAPTER` is not nulldb. Otherwise it hooks `ActiveRecord::Schema` and disrupts db tasks.

2017-10-03 16:08 UTC, akihikodaki commented
I had an experiment to remove `activercord/railties` (and optionally Redis) dependency from `assets:precompile`. Now I prefer the approach in the experiment because:
* It showed it still calls `Setting.site_title` via `title` method. Hopefully the approach eliminates such bugs.
* It was not so difficult.
* No additional dependency (it actually reduces dependencies required to build assets.)

2017-10-03 18:11 UTC, danhunsaker commented
Removing the DB dependency during asset precompile is what I originally set out to do, but I'm not as familiar with Rails as I'd like. How does one go about removing dependencies from a Rake task?

2017-10-13 14:46 UTC, danhunsaker commented
@akihikodaki I think your approach of removing railties is superior to this one.

Between that, and since builds are working again (if a bit on the slow side, still) now that the DB calls have been removed from the asset compilation phase, I'm going to close this one.

2017-10-13 14:46 UTC, closed without merging