Append confirmation link as plain text
mastodon/mastodon pull request #5146
Opened 2017-09-29 11:08 UTC by Kjwon15

Some mail application is malfunctioning with links.
link as plaintext is useful when this situation:
![screenshot from 2017-09-29 20-05-41](https://user-images.githubusercontent.com/5047683/31013607-bf674054-a551-11e7-83d3-8d9639bc14ac.png)
(I was not able to click that link, So I used "view original" feature to confirmation email)

2017-09-30 02:31 UTC, Gargron commented
There should be a plaintext version of the e-mail for this, the template ends with text.erb instead of html.haml. I don't think we should put plaintext links into html templates.

2017-09-30 03:23 UTC, nightpool commented
@Gargron It's very common to put plain-text confirmation links into emails in case they get blocked by the client. Since getting a squeaky-clean email setup is very, very hard, this seems useful.

2017-09-30 14:01 UTC, Gargron requested changes

2017-09-30 14:01 UTC, Gargron commented on app/views/user_mailer/confirmation_instructions.en.html.erb
> +<p>If above link not worked, Copy and paste this URL</p>
> If the above link did not work, copy and paste this URL into your address bar:

2017-10-02 05:21 UTC, Gargron approved these changes

2017-10-02 05:21 UTC, merged

2017-10-02 20:07 UTC, Kjwon15 commented
OMG I changed incorrectly and it merged...
I'm very sorry for this. :cry:

It should be
```html
<p>To confirm your inscription, please click on the following link : <br>
<%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>

<p>If the above link did not work, copy and paste this URL into your address bar: <br>
<span><%= confirmation_url(@resource, confirmation_token: @token) %></span>
```
not
```html
<p>If the above link did not work, copy and paste this URL into your address bar: <br>
<%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>

<p>If above link not worked, Copy and paste this URL</p>
<span><%= confirmation_url(@resource, confirmation_token: @token) %></span>
```

2017-10-02 20:22 UTC, Gargron commented
@Kjwon15 Oh, I don't know how I missed it... Tired eyes. Please submit a fix asap...