Consistant blocking behavior
mastodon/mastodon pull request #5383
Opened 2017-10-13 19:49 UTC by ThibG

There are a few inconsistencies in blocking behavior: indeed, if user Blocker blocks user Blockee, the expected behavior is that Blockee won't see messages from Blocker, and vice-versa. However, there are places where Blockee can see messages from Blocker:
1. By putting the URL of one of Blocker's public/unlisted toots in the search box
  This is a very minor issue, as Blockee could just use the URL to access the toot outside of the Web UI, but it's still inconsistent.
2. Being mentioned in one of Blocker's toots:
  In this case, the toot will pop up in the notifications, and *disappear* from the Web UI (until it is reloaded) as soon as Blockee clicks on it, which is highly confusing.
  I decided to changes the rules to keep the notifications (so talking about them behind their back would not be possible), but also make toots mentioning Blookee accessible to them.

First commit addresses the first point, and the second the second issue.

2017-10-13 20:02 UTC, ThibG commented
One test fails, I will change it if we agree toots mentionning you should be displayed even if the author blocks you.

2017-10-14 12:44 UTC, Gargron commented
I'm not sure on this. We've had similiar issues opened in the past like "remote server still gets sent Salmon slaps even if blocked" which indicates that the behaviour would be unintuitive, so even though the "talking behind back" point is valid, I think the block operation should supersede that. So how about we prevent those notifications from being created instead?

2017-10-14 13:17 UTC, ThibG commented
I have no strong opinion either way, but the messages are currently delivered to blocked users, through federation or not.
I'm also thinking about clearly indicating when someone is blocked, but that's a separate issue.

2017-10-14 14:23 UTC, nightpool commented
We should NOT be delivering mentions to blocked users. I mean, you're never
going to see the reply, so how is it worth it?
On Sat, Oct 14, 2017 at 9:17 AM ThibG <notifications@github.com> wrote:

> I have no strong opinion either way, but the messages are currently
> delivered to blocked users, through federation or not.
> I'm also thinking about clearly indicating when someone is blocked, but
> that's a separate issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tootsuite/mastodon/pull/5383#issuecomment-336634422>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAORVx-VBA-2QyKFuczDPkQKTuPCDftjks5ssLRxgaJpZM4P4-Rd>
> .
>

2017-10-14 20:03 UTC, ThibG commented
@nightpool you may still want to know what they say “behind your back” especially since their toot may be public and seen by other people. The (very few) people that gave me feedback on this were rather for showing the mentions. So I don't know :/

2017-11-13 17:49 UTC, ThibG commented
Rebased and dropped the controversial commit. I still think blocking behavior should be tweaked, though, but I don't really prioritize it for now.

2017-11-14 20:18 UTC, Gargron requested changes

2017-11-14 23:10 UTC, ThibG commented on app/controllers/api/v1/search_controller.rb
> +    search[:statuses].keep_if { |status| authorize status, :show? rescue false }
Integrated your changes

2017-11-15 00:53 UTC, Gargron approved these changes

2017-11-15 00:53 UTC, merged