Add up-to-date korean translation on client
mastodon/mastodon pull request #5402
Opened 2017-10-15 10:01 UTC by voidsatisfaction

# Why?

Toot -> 툿
and some not translated things

2017-10-15 12:18 UTC, Gargron commented
@Kjwon15 is this ok?

2017-10-15 17:51 UTC, tribela requested changes
"Toot" → "툿" : :+1: 
But some translations are could be changed.

2017-10-15 17:51 UTC, Kjwon15 commented on app/javascript/mastodon/locales/ko.json
> +  "privacy.unlisted.short": "타임라인 미표시",
"타임라인에 미표시" could be better.

2017-10-15 17:51 UTC, Kjwon15 commented on app/javascript/mastodon/locales/ko.json
> +  "status.embed": "퍼가기",
"퍼가기" is slang…
How about "공유하기" or "임베드"

2017-10-15 17:56 UTC, Kjwon15 commented on app/javascript/mastodon/locales/ko.json
> +  "privacy.unlisted.short": "타임라인 미표시",
Or just "미공개"

2017-10-16 10:35 UTC, voidsatisfaction commented on app/javascript/mastodon/locales/ko.json
> +  "privacy.unlisted.short": "타임라인 미표시",
@Kjwon15 Thank you for replying. Because there is `"privacy.private.short": "비공개",` already, I think "타임라인에 미표시" suggestion is better solution.

2017-10-16 10:35 UTC, voidsatisfaction commented on app/javascript/mastodon/locales/ko.json
> +  "status.embed": "퍼가기",
You are right. I will change it to "공유하기"

2017-10-16 12:39 UTC, Gargron approved these changes

2017-10-16 12:39 UTC, merged

2017-10-18 02:35 UTC, Kjwon15 commented on app/javascript/mastodon/locales/ko.json
> +  "embed.instructions": "아래의 코드를 복사하여 대화를 원하는 곳으로 퍼가세요.",
This wasn't changed.
퍼가기 → 공유하기

2017-10-18 02:41 UTC, voidsatisfaction commented on app/javascript/mastodon/locales/ko.json
> +  "embed.instructions": "아래의 코드를 복사하여 대화를 원하는 곳으로 퍼가세요.",
@Kjwon15 Thank you. I want to change the expression but should I make another branch or just push here?

2017-10-18 02:45 UTC, Kjwon15 commented on app/javascript/mastodon/locales/ko.json
> +  "embed.instructions": "아래의 코드를 복사하여 대화를 원하는 곳으로 퍼가세요.",
@Gargron is using "squash and rebase" strategy to merge PRs.
I think you should rebase into merged master branch (to get rid of old merged commits) and create another PR