Allow to dereference Follow object for ActivityPub
mastodon/mastodon pull request #5772
Opened 2017-11-21 09:51 UTC by akihikodaki

Resolves #5770.

2017-11-21 10:41 UTC, akihikodaki commented
7a7604908ffa9cf9377a33a22b5bc7ff2002b813 is a change suggested at https://github.com/tootsuite/mastodon/pull/5649#pullrequestreview-77766123. 7a7604908ffa9cf9377a33a22b5bc7ff2002b813 must be merged before #5649.

2018-01-02 13:33 UTC, Gargron approved these changes

2018-01-02 13:35 UTC, Gargron requested changes

2018-01-02 13:35 UTC, Gargron commented on app/serializers/activitypub/follow_serializer.rb
> +  attribute :id, if: -> { object.respond_to(:object_type) }
`respond_to?` (missing question mark)

I would also prefer using `if: :symbol` with a method definition as it's easier to read. E.g. `if: :supports_dereferencing?`

2018-01-03 00:49 UTC, akihikodaki commented
55ecc966a07fa1b523843539c5f565d9454e7e5a resolves https://github.com/tootsuite/mastodon/pull/5772#pullrequestreview-86140318.

2018-01-03 03:40 UTC, Gargron requested changes

2018-01-03 03:40 UTC, Gargron commented on app/serializers/activitypub/follow_serializer.rb
> +  private
Unfortunately it can't be private in a serializer (see build failure)

2018-01-03 03:50 UTC, akihikodaki commented
9818b2f0cc3d6281c944084cfa08158df91560bd resolves https://github.com/tootsuite/mastodon/pull/5772#pullrequestreview-86292893.

2018-01-03 17:08 UTC, Gargron approved these changes

2018-01-03 17:08 UTC, merged