Reduce motion for boost animation
mastodon/mastodon pull request #5871
Opened 2017-12-02 19:11 UTC by nolanlawson

Fixes #5833. Video demonstrations: [before](https://gfycat.com/ShyIdealisticBelugawhale) and [after](https://gfycat.com/SimplisticTidyBinturong).

When motion is reduced, it does a little `transition: color` animation rather than the standard rotation animation. Note that it doesn't look exactly like the non-reduced-motion version because I'm adding a color to the SVG rather than using an entirely different SVG with a frame for each frame of the animation.

I added a CSS class for `reduce-motion` because it was simpler to do this all in CSS. I also added `no-reduce-motion` because `:not()` queries tend to be bad for performance compared to a simple class lookup.

2017-12-02 19:11 UTC, nolanlawson commented on app/javascript/styles/mastodon/components.scss
> +  transition: color 100ms ease-in;
this is the same animation as the favourite star AFAICT

2017-12-02 20:24 UTC, Gargron requested changes

2017-12-02 20:24 UTC, Gargron commented on app/views/layouts/application.html.haml
> +  - body_classes += (' reduce-motion' if current_account&.user&.setting_reduce_motion) || ' no-reduce-motion'
```ruby
body_classes += current_account&.user&.setting_reduce_motion ? ' reduce-motion' : ' no-reduce-motion'
```

2017-12-15 02:05 UTC, nolanlawson commented on app/views/layouts/application.html.haml
> +  - body_classes += (' reduce-motion' if current_account&.user&.setting_reduce_motion) || ' no-reduce-motion'
My ruby foo is not great. 😅 Will fix.

2017-12-15 02:11 UTC, Gargron approved these changes

2017-12-24 03:48 UTC, merged