OC language update
mastodon/mastodon pull request #5905
Opened 2017-12-06 19:00 UTC by Quenty31

First step to complete translation.
There are things remaining, will translate them later

2017-12-06 19:28 UTC, Quenty31 commented
Erm...where did I go wrong?

2017-12-06 21:32 UTC, ykzts commented
unnecessary trailing whitespace 😉 e23ee3b7dd4e94770ea9bd66f469924a3485cb31

2017-12-06 21:32 UTC, ykzts approved these changes

2017-12-06 21:37 UTC, ykzts requested changes

2017-12-06 21:37 UTC, ykzts commented on config/locales/oc.yml
> +      demote: Retrogradar
Move this line under https://github.com/tootsuite/mastodon/pull/5905/files#diff-7cde7553e8a510f83c4856fb298d9809L64.

2017-12-07 06:28 UTC, ykzts approved these changes

2017-12-07 06:28 UTC, merged