make it possible to stream public timelines without authorization
mastodon/mastodon pull request #5977
Opened 2017-12-11 13:53 UTC by nullkal

Public timelines can be fetched via `/api/v1/timelines/public` without authorization, but streaming them needs authorization token now. This PR make it consistent between normal fetching APIs and streaming APIs.

2017-12-11 14:12 UTC, abcang commented on streaming/index.js
> +    const PUBLIC_STREAMS = [
I think that it is better to define PUBLIC_STREAMS and PUBLIC_ENDPOINTS outside the function.

2017-12-11 14:47 UTC, abcang commented
If authentication is skipped, since `req.accountId` does not have a value, I think you need to change some methods such as streamFrom. Especially streamFrom will filter on accounts if `needsFiltering` is true, so we need to fix.

2017-12-11 15:17 UTC, abcang requested changes

2017-12-11 15:17 UTC, abcang commented on streaming/index.js
> +    const auth_required = PUBLIC_ENDPOINTS.some(endpoint => endpoint === req.path);
Maybe `!PUBLIC_ENDPOINTS.some(endpoint => endpoint === req.path)`. Also, it is better to change the variable name to camel case.

2017-12-11 15:17 UTC, abcang commented on streaming/index.js
> +          if (req.accountId != null) {
I think that simply does not have any problem. `accountId` can never be 0.

```
if (!req.accountId) {
```

And you should not need to change `.eslintrc.yml`.

2017-12-11 15:28 UTC, abcang approved these changes

2017-12-12 00:32 UTC, Gargron commented on streaming/index.js
> +    const accountId = req.accountId || '(anonymous user)';
Can we use IP instead?

2017-12-12 00:35 UTC, Gargron commented on streaming/index.js
> +    const accountId = req.accountId || '(anonymous user)';
Can we use IP instead?

2017-12-12 00:37 UTC, Gargron commented
I think conceptually I am okay with this. Originally I was against it because keeping open connections is a burden and allowing anonymous connections means you would have to block by IP instead of simply revoking access tokens.

However if this becomes a thing than the /about page could get real-time updates instead of poll intervals.

2017-12-12 14:13 UTC, Gargron approved these changes

2017-12-12 14:13 UTC, merged