Handle sessions that can't be translated
mastodon/mastodon pull request #6245
Opened 2018-01-11 23:18 UTC by Kjwon15

This commit fixes #6165.

2018-01-11 23:58 UTC, ykzts requested changes

2018-01-11 23:58 UTC, ykzts commented on app/views/auth/registrations/_sessions.html.haml
> +              = t 'sessions.description', browser: t("sessions.browsers.#{session.browser}", default: "#{session.browser}"), platform: t("sessions.platforms.#{session.platform}", default="#{session.p
`default="#{session.platform}"` -> `default: "#{session.platform}"`?

2018-01-12 00:22 UTC, Kjwon15 commented on app/views/auth/registrations/_sessions.html.haml
> +              = t 'sessions.description', browser: t("sessions.browsers.#{session.browser}", default: "#{session.browser}"), platform: t("sessions.platforms.#{session.platform}", default="#{session.p
Oh!

2018-01-12 01:01 UTC, ykzts approved these changes

2018-01-12 01:44 UTC, merged