Specify AGPLv3+
mastodon/mastodon pull request #6546
Opened 2018-02-23 17:18 UTC by TrashMacNugget

Since the documentation doesn't specify you can use Mastodon as AGPLv3 or any later version.

2018-02-24 11:00 UTC, ykzts requested changes

2018-02-24 11:00 UTC, ykzts commented on package.json
> +  "license": "AGPL-3.0+",
`AGPL-3.0-or-later` ([SPDX License List | Software Package Data Exchange (SPDX)](https://spdx.org/licenses/)

2018-02-24 18:13 UTC, Gargron commented
But why is this needed?

2018-02-24 23:54 UTC, TrashMacNugget commented
@Gargron
Better license compatibility. If in the future there is some library using (A)GPLv4 that Mastodon wants to use, or some (A)GPLv4 project wants to use some Mastodon code, there would be no incompatibilities. Since it is not specified, that is currently the way it is now, but it is better to specify so there is no legal uncertainty.

2018-02-25 07:02 UTC, akihikodaki commented
An alternative option is to have a license notice to specify only version 3. (The license itself recommends to have one on all files, but I don't think it is mandatory. Writing the intension to `LICENSE` or `README.md` may also be enough.)
Such a notice should be helpful for future authors of softwares licensed with some later version.

2018-02-25 16:09 UTC, TrashMacNugget commented
@akihikodaki I think it would be much better to just leave it as-is, since the project already is licensed as AGPLv3 or (at your option) any later version.

2018-02-26 22:42 UTC, ykzts approved these changes

2018-02-27 00:52 UTC, merged