Update Polish string
mastodon/mastodon pull request #6918
Opened 2018-03-26 10:01 UTC by M4v3R

The title 'Polszczyzna' for Polish locale was incorrect, it should read 'Polski'. This pull request fixes that.

2018-03-26 10:09 UTC, ykzts commented
cc @KrzysiekJ @m4sk1n @rysiekpl

2018-03-26 10:13 UTC, m4sk1n commented
#5488
https://capitalism.party/users/KrzysiekJ/updates/231

2018-03-26 10:15 UTC, M4v3R commented
@m4sk1n oops, missed that. Still, I think 'Polszczyzna' sounds... artificial. No software I know use that term, nor do people use it casually. I would suggest to reconsider that choice :).

2018-03-26 10:20 UTC, M4v3R commented
@m4sk1n One more thing I'd like to add about why I'm not a fan of 'Polszczyzna' - when I saw that I got an impression that it was a product of machine translation which often produces this kind of artificial sounding translations. And that put me off a bit, thinking that no big effort was put in to Polish translation. I see now that I was wrong, but that was the first impression I had so wanted to share that.

2018-03-26 10:35 UTC, m4sk1n commented
No software I know (besides Mastodon) uses “toot” term for posting… ;)

2018-03-26 10:39 UTC, M4v3R commented
True, and the same applies to Twitter which invented the term "tweet", and yet uses standard wording for everything else :)

<img width="379" alt="zrzut ekranu 2018-03-26 o 12 38 00" src="https://user-images.githubusercontent.com/1614514/37901764-a10dccae-30f2-11e8-99f3-058606c5b71d.png">

2018-03-26 10:53 UTC, rysiekpl requested changes
`Polszczyzna` is nicer IMVHO. Not many other services use it, but it's perfectly valid, and is a nice traditional way of referring to the Polish language.

2018-03-26 16:02 UTC, closed without merging

2018-03-26 17:05 UTC, nightpool commented
If no other services use it—and i could not find a single one that does, among the many i use—is it going to put off new users from joining mastodon, if they get the same impression @M4v3R did?

> when I saw that I got an impression that it was a product of machine translation which often produces this kind of artificial sounding translations

This is very concerning to me.

2018-04-23 11:51 UTC, KrzysiekJ commented
Language names are listed, which are arguably nouns, and [„polszczyzna” is adequate for that purpose](http://sjp.pwn.pl/doroszewski/polszczyzna.html), according to the dictionary of Polish edited by Doroszewski. On the other hand, [the same dictionary doesn’t mention usage of „polski” standalone as a noun describing language](https://sjp.pwn.pl/doroszewski/polski;5476592.html) (there is obsolete „polskie” however).