Add and revise Traditional Chinese (zh-TW) translation for serveral strings
mastodon/mastodon pull request #7002
Opened 2018-04-02 08:48 UTC by ymhuang0808

The PR may be reviewed by a native Traditional Chinese speaker.

2018-04-02 09:15 UTC, ykzts commented
cc @Artoria2e5 @caasi @shouko @vidarlee

2018-04-03 01:58 UTC, Artoria2e5 requested changes
👍🏽✏️🔜🆗

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.blocked": "封鎖的",
add 已/被, or both

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
忘記 YML 裡面是怎麼翻譯的了……一樣的話就好

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "compose_form.sensitive.unmarked": "此媒體已被取消標註為敏感的",
未被標註

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "emoji_button.not_found": "沒有表情符號！！ (╯°□°）╯︵ ┻━┻",
要不要像「emoji &rarr; emojo」那樣寫成「表情符吼」之類的？

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "emoji_button.recent": "經常使用的",
大陸這邊會用「常用」，不知道你們島上會不會那樣縮短……

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "keyboard_shortcuts.favourite": "到最愛",
這邊 favorite 是動詞啦，按鍵加入最愛的那種意思

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "regeneration_indicator.label": "載入中...",
「…」

2018-04-03 01:58 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "search_results.accounts": "人們",
應該是不要加「們」的……

2018-04-03 02:00 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
>    "emoji_button.food": "食物與飲料",
好像這個也可以改成「飲食」的感覺

2018-04-05 07:42 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
沒找到相同的詞

2018-04-05 07:43 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "emoji_button.not_found": "沒有表情符號！！ (╯°□°）╯︵ ┻━┻",
抱歉，我不太懂

2018-04-05 07:44 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "emoji_button.recent": "經常使用的",
已經修正，謝謝

2018-04-05 07:44 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "keyboard_shortcuts.favourite": "到最愛",
已經修正，謝謝

2018-04-05 07:44 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "regeneration_indicator.label": "載入中...",
已經修正，謝謝

2018-04-05 07:44 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "search_results.accounts": "人們",
已經修正，謝謝

2018-04-05 07:47 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "compose_form.sensitive.unmarked": "此媒體已被取消標註為敏感的",
Fixed, thanks.

2018-04-11 03:31 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
是不是改成「封鎖」比較好？

2018-04-11 04:50 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
（没有用电脑所以就写简体字了）大概可以？隐藏也好删账户也好都算是封锁…？（总觉得有更好的词但是想不出来…）

2018-04-11 06:46 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
可能還是用隱藏比較符合之前的翻譯

![mastodon_domain_hidden_modal](https://user-images.githubusercontent.com/2720857/38600519-f2f1e6fa-3d53-11e8-9fd3-23db67bafe5c.jpg)

![mastodon_domain_hidden](https://user-images.githubusercontent.com/2720857/38600543-0a524f9c-3d54-11e8-9b7d-04474bc89ce7.jpg)

2018-04-11 09:43 UTC, Gargron commented
Is this done?

2018-04-11 12:06 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
啊我怎么忘了！那就把 yml 的也改回隐藏好了。本来记得是隐藏的，也不知道是谁改掉了…

2018-04-12 02:47 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
是不是可以先不動 yml 檔的部分？主要是因為英文原文來是 "New domain block"，加上 yml 檔案是  Rails 專案內的翻譯。

2018-04-14 01:29 UTC, ymhuang0808 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
原本繁體中文就是「封鎖」：https://github.com/tootsuite/mastodon/commit/120a37a197bad8e9c45d3f72125e074886303a27

我不會改這個部分，先依照原文翻譯

2018-04-14 16:05 UTC, Artoria2e5 commented on app/javascript/mastodon/locales/zh-TW.json
> +  "account.domain_blocked": "域名隱藏",
啊先 merge 算了我來改就是！

2018-04-14 16:06 UTC, Artoria2e5 commented
Good to go.

2018-04-14 17:05 UTC, Gargron approved these changes

2018-04-14 18:06 UTC, Gargron commented
Why is it conflicting with something straight away :weary:

2018-04-15 12:00 UTC, merged

2018-04-15 13:16 UTC, ymhuang0808 commented
Hi @ykzts , thanks for your help. It looks good!

2018-04-16 02:01 UTC, ymhuang0808 commented
Thanks @ykzts ! I will translate on Weblate. 😄