Add label for sensitive pictures
mastodon/mastodon pull request #7012
Opened 2018-04-02 18:29 UTC by ThibG

Add a “sensitive” label besides the eye icon to make sensitive media more obvious, refactor a bit to match glitch-soc's implementation.

2018-04-03 08:54 UTC, ThibG commented
This is what it looks like in the Web UI:
![screenshot-2018-4-3 mastodon instance perso de thibg 1](https://user-images.githubusercontent.com/384364/38239545-52ddba1c-372d-11e8-9f48-7fe69c43256d.png)

And in on public pages:
![screenshot-2018-4-3 t h i b g thib sitedethib com](https://user-images.githubusercontent.com/384364/38239556-5bcdedea-372d-11e8-8172-a307ae355584.png)

2018-04-05 01:00 UTC, ykzts commented on app/views/stream_entries/_content_spoiler.html.haml
> -    %span= t('stream_entries.click_to_show')
NOTE: no longer used.

2018-04-05 01:00 UTC, ykzts approved these changes
👍

2018-04-14 10:43 UTC, Gargron requested changes
I am not quite okay with the visual design of this, though I consider it useful. What if the "sensitive" label was positioned next to / instead of the "GIF" indicator and in the same style as that one?

2018-04-15 19:40 UTC, ThibG commented
I'm not sure about positioning the label next to / instead of the “GIF” indicator, both because it's a different thing entirely and makes more sense around the eye icon, and because it's technically more difficult to do so.
However, there is no reason for it to be styled differently, so I'll fix that.

2019-11-02 05:28 UTC, closed without merging