Add a “bookmark” feature
mastodon/mastodon pull request #7107
Opened 2018-04-11 18:28 UTC by ThibG

Add a bookmark feature, working mostly like favourites, except they are not federated nor visible by other users than the person bookmarking a toot.

2018-04-11 18:31 UTC, m4sk1n commented
I think the “favourite” thing functionality should be reduced now to work like a zucksite like button, without the save feature, but then it would be nice to have an activity log, so there would still be way to find favourited toots

2018-04-11 20:32 UTC, Cassolotl commented
This seems like a good change, I like private save-for-later as separate from public reaction hearts/stars.

Related issues:

* Dream feature: "like" and "save" separately #1178
* arbitrary emojis as reactions #4106 - maybe the heart/star can just be like a positive reaction button and it doesn't need to be saved?

2018-04-13 07:51 UTC, trwnh commented
re: what m4sk1n said -- i don't see a compelling reason to change anything about how faves work currently. fundamentally, they are a public approval / acknowledgement of a message, and can be browsed from someone's profile if they want to see go back and see them.

a bookmark feature would be almost the same thing, but private -- no indicator, not exposed via the profile or the status. adding bookmarks is no reason to remove functionality from the favorites.

2018-04-13 08:08 UTC, Cassolotl commented
I feel like "like/star" doesn't really need to be saved in a list if it's just a reaction emoji ish thing - if folks want to save it for later they'll use the bookmark feature, right?

And I think probably bookmarked toots should show up in search because it's save-for-later and that'll be something you want to be able to look up later.

I think "like/star" toots don't need to show up in a search because it's just public approval and that could clog up the search results unnecessarily - most people are gonna "like/star" *much* more than they'll save-for-later, and they're less likely to need to pull liked toots up in searches later, right?

2018-04-16 18:08 UTC, nightpool commented
disagree with adding this per my comments on #1178.

2018-04-16 18:08 UTC, nightpool commented
Hmm. Not sure what happened to that issue, it seems to be completely deleted, with it's discussion.

2018-04-16 18:35 UTC, ThibG commented
Ok, your main argument seems to be “web browser bookmarks serve this purpose”, yes and no.
If you bookmark the public toot, it's a pain to get back into the WebUI to boost/like/reply to it.
If you bookmark the WebUI, it's a bit better, but you go through the trouble of reloading the whole WebUI, either in an extra tab, or replacing your position in timelines, etc.

2018-04-16 19:59 UTC, ThibG commented
@lanodan favorites are already searchable (along with the rest) if Full-Text-Search is enabled.
The point of the “bookmark” feature as I use it is to bookmark things I haven't the time to read right now but I potentially want to react on later. For instance, if someone posts a long article or a video, and I want to like/boost/comment once I've seen it.

2018-04-17 11:56 UTC, Gargron commented
@ThibG But I use favourites for that use case. And that having a social function makes sense to me, I remember the old Delicious used to display rankings of favourited links and stuff that authors of those links could be proud of. I'm not a big fan of splitting this functionality. In fact, I was not a fan when Twitter changed favourites to likes, and now iirc *they* are adding "bookmarks" and I think that's a hot mess that could've been avoided by just keeping favourites the way they are here right now.

2018-04-17 12:06 UTC, ThibG commented
@Gargron but why should that person be proud of something I haven't read yet? Afaik, people use favorites (or likes, that's what they are protocol-wise) as approval, encouragement, or “I read this” marks. A bookmark is “I want to read this” and is something completely different honestly.

2018-05-12 18:27 UTC, ThibG commented
Worth a shot I guess :man_shrugging:

![pr](https://user-images.githubusercontent.com/384364/39960404-eab20f0a-5622-11e8-8787-1493a331e3c4.gif)

2018-08-10 13:27 UTC, ThibG commented
Updated the PR to:
- Rebase it
- Remove the joke rainbows
- Add OAuth scopes for bookmarks

2019-05-21 18:58 UTC, htgoebel commented
I really like to see this featur merged! I'm bookmarking a lot in Fedilab which I want to read later on the desktop (using the WebUI).

2019-07-30 11:15 UTC, ThibG commented
Twitter has them now :3

2019-10-27 13:46 UTC, regagain commented
I'd still like to have that feature.

2019-11-11 10:33 UTC, umonaca commented
Tried on local dev environment with some existing data, but the database migration failed.
`rails db:migrate --trace` shows:

```
rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
   (0.2ms)  SELECT pg_try_advisory_lock(5881450594042647960)
   (0.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Migrating to CreateBookmarks (20180831171112)
   (0.2ms)  BEGIN
Chewy strategies stack: [2] <- bypass @ /home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37
== 20180831171112 CreateBookmarks: migrating ==================================
-- create_table(:bookmarks, {})
   (60.1ms)  CREATE TABLE "bookmarks" ("id" bigserial primary key, "account_id" bigint NOT NULL, "status_id" bigint NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   (29.1ms)  CREATE  INDEX  "index_bookmarks_on_account_id" ON "bookmarks"  ("account_id")
   (30.0ms)  CREATE  INDEX  "index_bookmarks_on_status_id" ON "bookmarks"  ("status_id")
   -> 0.1280s
Chewy strategies stack: [2] -> bypass, now bypass @ /home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37
   (1.5ms)  ROLLBACK
   (0.6ms)  SELECT pg_advisory_unlock(5881450594042647960)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

=== Dangerous operation detected #strong_migrations ===

New foreign keys are validated by default. This acquires an AccessExclusiveLock,
which is expensive on large tables. Instead, validate it in a separate migration
with a more agreeable RowShareLock.

class StrongMigrations::Checker < ActiveRecord::Migration[5.2]
  def change
    add_foreign_key :bookmarks, :accounts, column: :account_id, on_delete: :cascade, validate: false
  end
end

class ValidateStrongMigrations::Checker < ActiveRecord::Migration[5.2]
  def change
    validate_foreign_key :bookmarks, :accounts
  end
end

/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/strong_migrations-0.4.2/lib/strong_migrations/migration.rb:21:in `stop!'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/strong_migrations-0.4.2/lib/strong_migrations/checker.rb:229:in `raise_error'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/strong_migrations-0.4.2/lib/strong_migrations/checker.rb:148:in `perform'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/strong_migrations-0.4.2/lib/strong_migrations/migration.rb:9:in `method_missing'
/home/mastodon/live/db/migrate/20180831171112_create_bookmarks.rb:10:in `change'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:814:in `exec_migration'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/strong_migrations-0.4.2/lib/strong_migrations/migration.rb:5:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `block in migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `block in migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/strategy.rb:70:in `wrap'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy.rb:201:in `strategy'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/chewy-5.1.0/lib/chewy/railtie.rb:37:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1036:in `up'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/strong_migrations-0.4.2/lib/strong_migrations/database_tasks.rb:4:in `migrate'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb [...]

2019-11-11 12:00 UTC, umonaca commented
Update: it's the strong migration issue.
To anyone who may be interested in this PR: you may wrap the `add_foreign_key` lines with `safety_assured` or follow [the guide here](https://github.com/ankane/strong_migrations) to create a separate migration.

2019-11-12 20:32 UTC, Gargron commented
Okay, I've heard some good arguments for having this feature today. This PR needs to be cleaned up a bit to be merged.

2019-11-12 22:33 UTC, ThibG commented
Rebased and fixed the migration. Would have to go other it to make sure everything has been kept up-to-date.

2019-11-13 02:55 UTC, umonaca requested changes

2019-11-13 02:55 UTC, umonaca commented on app/javascript/mastodon/features/getting_started/index.js
> +  bookmarks: { id: 'navigation_bar.bookmarks', defaultMessage: 'Bookmarks' },
The navigation bar item is missing. You should probably add something like this to `/home/muveexu/donotban/live/app/javascript/mastodon/features/ui/components/navigation_panel.js`
```
<NavLink className='column-link column-link--transparent' to='/bookmarks'><Icon className='column-link__icon' id='bookmark' fixedWidth /><FormattedMessage id='navigation_bar.bookmarks' defaultMessage='Bookmarks' /></NavLink>    
```
And adjust the column height for single-column mode accordingly:
Change [this line](https://github.com/tootsuite/mastodon/blob/c31bc41a02d89eea654f8d7c74c0a1cb544cd919/app/javascript/mastodon/features/getting_started/index.js#L133) to `height += 48*4;`.

2019-11-13 02:57 UTC, umonaca commented
You would probably want [this commit](https://github.com/glitch-soc/mastodon/pull/1166) as well

2019-11-13 03:17 UTC, umonaca commented
Bug report: the un-bookmark is not as responsive as the un-favourite. When a toot is unbookmarked, the icon remains `active` so the user is unsure if the toot has been unbookmarked or not. The user has to refresh the entire page to see the unbookmark has succeeded.

I reported [this issue}(https://github.com/glitch-soc/mastodon/issues/1244) in glitch-soc but was unable to reproduce it on the glitch-soc instance. However, I am able to reliably reproduce this bug in this PR in a local test environment.

2019-11-13 03:41 UTC, umonaca commented on app/javascript/mastodon/actions/interactions.js
> +      dispatch(unbookmarkSuccess(status, response.data));
Update: simply adding `dispatch(importFetchedStatus(response.data));` to this line and the `bookmark(status)` function  fixed the bug I reported.

2019-11-13 03:55 UTC, umonaca requested changes

2019-11-13 03:55 UTC, umonaca commented on app/javascript/mastodon/actions/interactions.js
> +      dispatch(unbookmarkSuccess(status, response.data));
Update: simply adding `dispatch(importFetchedStatus(response.data));` to this line and the `bookmark(status)` function  fixed the bug I reported.

2019-11-13 05:01 UTC, umonaca commented on app/javascript/mastodon/components/status_action_bar.js
> +  handleReblogClick = (e) => {
Is there any reason to have two `handleReblogClick` in this file?

2019-11-13 21:55 UTC, Gargron commented on app/javascript/mastodon/features/status/components/action_bar.js
> +        <div className='detailed-status__button'><IconButton className='bookmark-icon' active={status.get('bookmarked')} title={intl.formatMessage(messages.bookmark)} icon='bookmark' onClick={this.ha
I heard at least one user opinion that favourites and bookmarks not need be side-by-side, bookmarks can be in the dropdown menu. More responses have stated that they would use bookmarks more rarely than favourites, so perhaps this makes sense? Thoughts?

2019-11-13 22:01 UTC, Gargron commented on app/javascript/mastodon/features/status/components/action_bar.js
> +        <div className='detailed-status__button'><IconButton className='bookmark-icon' active={status.get('bookmarked')} title={intl.formatMessage(messages.bookmark)} icon='bookmark' onClick={this.ha
Oh well, we can move it later.

2019-11-13 22:02 UTC, Gargron approved these changes

2019-11-13 22:02 UTC, merged

2019-11-28 11:17 UTC, bannisdale commented
Maybe a stupid question, but ... is this already live? Is this part of the next release? How would I be able to find out? :)

2019-11-29 20:52 UTC, Gargron commented
It's live on mastodon.social, but no stable version has been released since this PR was merged, yet.