Ability to specify Redis passwd on mastodon:setup
mastodon/mastodon pull request #7222
Opened 2018-04-21 22:19 UTC by maxolasersquad

Closes #7221

2018-04-21 22:36 UTC, Gargron requested changes

2018-04-21 22:36 UTC, Gargron commented on lib/tasks/mastodon.rake
> +          q.modify :strip
No `end`? :thinking:

2018-04-21 22:52 UTC, maxolasersquad commented on lib/tasks/mastodon.rake
> +          q.modify :strip
Fixed.

2018-04-22 09:49 UTC, Gargron approved these changes

2018-04-22 09:49 UTC, merged