Multiple Issue templates
mastodon/mastodon pull request #7402
Opened 2018-05-07 16:24 UTC by ykzts

ref https://blog.github.com/2018-05-02-issue-template-improvements/

### Screenshot

![screenshot](https://user-images.githubusercontent.com/12539/39712560-727a109a-525e-11e8-8605-e7ce0d189933.png)

2018-05-07 18:16 UTC, nightpool requested changes
LGTM w/o comments

2018-05-07 18:16 UTC, nightpool commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Issue text goes here. -->
i'm worried about people putting the issue text inside of the comment on accident, leading to very confusing "empty" issues. Can we go back to [Issue text goes here]?

2018-05-07 18:16 UTC, nightpool commented
Maybe we want another template for "I'm having an issue running Mastodon" or similar, for admin support stuff?

2018-05-08 01:56 UTC, ykzts commented
@nightpool 👍

2018-05-08 03:19 UTC, nightpool approved these changes

2018-05-08 03:20 UTC, nightpool commented
I think you misinterpreted what I said, but i'm fine w/o it, I was just thinking a third template for admins might be nice, but i don't know what we'd put there.......

2018-05-08 11:35 UTC, Gargron approved these changes

2018-05-08 11:35 UTC, merged