Ensure single user is a local user (fixes #8154)
mastodon/mastodon pull request #8157
Opened 2018-08-09 20:29 UTC by ThibG

2018-08-09 21:27 UTC, Gargron requested changes

2018-08-09 21:27 UTC, Gargron commented on app/controllers/home_controller.rb
> +      short_account_path(Account.local.first)
Let's make sure it's not suspended (deleted) either...

2018-08-10 06:42 UTC, unarist commented
I'm bit surprised that the account is not `Account.find_local(Setting.site_contact_username)` one, btw.

2018-08-10 09:43 UTC, ThibG commented
@unarist I guess we could do that, but we would have to make sure `Setting.site_contact_username` points to a valid user and is set appropriately when setting up an instance…

2018-08-11 09:53 UTC, Gargron approved these changes

2018-08-11 09:53 UTC, merged