Fetch remote status on behalf of the user pasting URL (fixes #8193)
mastodon/mastodon pull request #8214
Opened 2018-08-15 20:03 UTC by ThibG

Since it can disclose to the remote instance that the local user is trying to fetch a toot, that is opt-out:
![screenshot_2018-08-15 preferences - dev instance](https://user-images.githubusercontent.com/384364/44170197-e463ee80-a0d6-11e8-8bf6-cb3b044af5cc.png)

2018-08-15 20:38 UTC, ThibG commented
I am wondering if it wouldn't be better to try once anonymously, then retry on behalf of the account if the result is not 200 OK.
This would “leak” the information in less circumstances and be slightly less expensive in the most common case, at the cost of one additional HTTP request when the remote resource *is* private.

2018-08-18 19:19 UTC, Gargron requested changes

2018-08-18 19:27 UTC, ThibG commented on config/locales/simple_form.en.yml
> +        setting_fetch_anonymously: Unless this is checked, fetching a remote toot or user from the search box will let the remote server know about your account. If checked, you won't be able to fetc
I'll rewrite it, it's slightly misleading now that the next commit only authenticates you to the remote server when fetching first failed.

2018-08-18 19:38 UTC, ThibG commented on config/settings.yml
> +  fetch_anonymously: false
I'm torn about this one. It's unlikely to happen and is only an issue if pasting an URL of a remote resource stored on a malicious server.
On the contrary, I think this is useful to far more people than it is an issue for.
However, it *is* a change of behavior and privacy expectations, however small it is, so…

2018-08-18 20:04 UTC, ThibG commented
There is an alternative, more involved way to go about how to consent to disclosing the account name to remote instances:
1. Have the setting be on by default, but renamed to something like “always ask”
2. If anonymously getting the remote status failed, and the setting is on, display a message like “The resource you requested might require authentication. Retry by disclosing your account name to the remote instance?”

2018-08-18 20:48 UTC, Gargron commented
@ThibG That sounds way too complicated to be worth it.

2018-08-18 20:54 UTC, ThibG commented
@Gargron to me, that sounds like the best way to do it. But we can implement that later if the feature is opt-out. I will make the setting on by default.

2018-08-19 14:56 UTC, ThibG commented
I have made the changes you requested.

2018-08-19 15:04 UTC, nightpool requested changes
making this an option is a huge anti-pattern. If we think this is a security/privacy risk, we should make sure to foreground it to a user *when they fetch the status*, not in a hidden preferences checkbox that nobody will ever see.

2018-08-19 15:06 UTC, nightpool commented
Alternatively, i think taking out the preferences checkbox and doing the optimistic-anonymous and retrying with authorization covers 90% of the possible security problems.

2018-08-19 19:01 UTC, ThibG commented
Not completely convinced by the color scheme, but here is what I have now:
![screenshot_2018-08-19 dev instance 3](https://user-images.githubusercontent.com/384364/44312091-189b2000-a3f3-11e8-994f-db35b00d4e81.png)

2018-08-19 19:31 UTC, ThibG commented
So… addressed @Gargron's concerns by setting `fetch_anonymously` to `true` by default and changing the wording, and addressed @nightpool's concerns by making the setting discoverable via a warning appearing if the setting is likely to have prevented fetching a private toot.

2018-08-19 19:57 UTC, trwnh commented
"authentify"? i think you mean "authenticate" or "identify"

2018-08-19 20:06 UTC, ThibG commented
@trwnh fixed!

2018-09-20 02:41 UTC, trwnh commented
Revisiting this after I just now had some difficulty sharing an old followers-only status with one of my followers... but I'd like to clarify the flow of what exactly is going on here.

I'm not sure the current setting makes sense as I understand it. Is it opt-out or opt-in? @ThibG's comment says `fetch_anonymously` is set to true by default, and the screenshot shows a "change this setting" link, but the message for commit https://github.com/tootsuite/mastodon/pull/8214/commits/33b401a48417bb009ac3047505691c1a685e3e74 says "allow users opting out". So, is it currently opt-in or opt-out for this PR?

2018-09-20 07:28 UTC, ThibG commented
Sorry this is a bit confusing. This depends on whether you consider the feature to be “stay anonymous” or “fetch private toots”.
The setting is called “always fetch anonymously” and is on by default. This means you won't be able to fetch remote private toots by default.
You can then, by disabling this feature, opt-in to see private toots at the cost of occasionally disclosing to the remote server that *you* are accessing a given resource from them.

Le 20 septembre 2018 04:41:37 GMT+02:00, trwnh <notifications@github.com> a écrit :
>Revisiting this after I just now had some difficulty sharing an old
>followers-only status with one of my followers... but I'd like to
>clarify the flow of what exactly is going on here.
>
>I'm not sure the current setting makes sense as I understand it. Is it
>opt-out or opt-in? @ThibG's comment says `fetch_anonymously` is set to
>true by default, and the screenshot shows a "change this setting" link,
>but the message for commit
>https://github.com/tootsuite/mastodon/pull/8214/commits/33b401a48417bb009ac3047505691c1a685e3e74
>says "allow users opting out". So, is it currently opt-in or opt-out
>for this PR?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tootsuite/mastodon/pull/8214#issuecomment-423021361

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

2018-10-31 16:54 UTC, kit-ty-kate commented
What is the status of this PR? It's really annoying to not being able to give a link to a private toot to someone.

2019-11-02 05:28 UTC, closed without merging

2019-11-06 17:49 UTC, kit-ty-kate commented
Can this be reopened?

2019-11-09 15:55 UTC, ThibG commented
I am not actually completely sure we want something like this, and Pleroma, for instance, isn't going to offer fetching private toots as far as I understand.

However, being able to refer to private toots by URL—at least for those already known to the instance—is still valuable. To this end, I guess we could fetch toots from the database by their `url` attribute. One issue with that is that we can't ensure this URL actually corresponds to the private toot, and have to trust the originating instance. But that assumption is consistent with the other ones that we make regarding the instance being authoritative for every object living on their domain name.

2024-08-06 10:00 UTC, tsmethurst commented
Hiya, are there any plans to reconsider / update this? Just linking to this issue here since it's related: https://github.com/superseriousbusiness/gotosocial/issues/3177