Add quick links to the admin interface in the WebUI
mastodon/mastodon pull request #8545
Opened 2018-08-31 14:25 UTC by ThibG

This adds quick links at the bottom of the status/account dropdown menus if the logged-in user is a moderator.

Also an admin view for select toots only:
![screenshot_2018-08-31 account statuses - thib sitedethib com - dev instance](https://user-images.githubusercontent.com/384364/44918127-8112c700-ad3a-11e8-8b76-40896c30a4f6.png)

2018-08-31 14:55 UTC, ThibG commented
CircleCI is stuck for some reason…

2019-01-04 11:24 UTC, Gargron requested changes

2019-01-04 11:40 UTC, ThibG commented on app/views/admin/statuses/show.html.haml
> += form_for(@form, url: admin_account_statuses_path(@account.id)) do |f|
It's not an *exact* copy as there is no need for filters or pagination, but yeah, some refactoring is probably possible.

2019-01-04 12:10 UTC, Gargron approved these changes

2019-01-04 12:10 UTC, merged