Use process.env to allow configuring of socket permissions
mastodon/mastodon pull request #8852
Opened 2018-10-02 10:38 UTC by Gomasy

Puma can be set with environment variables, but streaming cannot do that...

2018-10-03 02:57 UTC, Gargron commented
>Puma can be set with environment variables, but streaming cannot do that...

I cannot find a Puma setting for `SOCKET_PERMISSION`, could you clarify?

2018-10-03 05:35 UTC, Gomasy commented
![screenshot from 2018-10-03 14-27-33](https://user-images.githubusercontent.com/5166681/46391680-1a0d7700-c719-11e8-8d0d-80aac876ec51.png)
https://github.com/puma/puma/blob/master/README.md

Puma can change permissions of the socket by adding the umask parameter.

2018-10-03 21:45 UTC, Gargron requested changes

2018-10-03 21:45 UTC, Gargron commented on streaming/index.js
> +      fs.chmodSync(server.address(), process.env.SOCKET_PERMISSION || 0o666);
SOCKET_PERMISSION will be a string, but 0o666 is not a string. Perhaps conversion is needed here?

Also maybe call it SOCKET_UMASK?

2018-10-04 01:57 UTC, Gomasy commented
@Gargron It has changed.
It is calculated if exists, but if it does not exist 0o666 is set as usual.

2018-10-07 22:08 UTC, closed without merging