i18n: Update Polish translation
mastodon/mastodon pull request #9070
Opened 2018-10-23 13:56 UTC by m4sk1n

Signed-off-by: Marcin Mikołajczak <me@m4sk.in>

2018-10-24 17:36 UTC, Quenty31 commented
Hello @m4sk1n you've got a problem line 381 with the spaces ;)

2018-10-24 21:51 UTC, ykzts requested changes

2018-10-25 04:39 UTC, m4sk1n commented
I’m sorry, I will need to find better text editor than vim for my phone…

2018-10-25 10:45 UTC, ykzts approved these changes

2018-10-25 10:45 UTC, merged