Restore profile links in /admin/accounts
mastodon/mastodon pull request #9494
Opened 2018-12-11 13:27 UTC by ThibG

Fixes #9431 

Before
--------

![screenshot_2018-12-11 accounts - dev instance](https://user-images.githubusercontent.com/384364/49803700-dc4c5080-fd50-11e8-8573-6577e95d3d05.png)

After
------

![screenshot_2018-12-11 accounts - dev instance 1](https://user-images.githubusercontent.com/384364/49803707-dfdfd780-fd50-11e8-9704-07def4163cd3.png)

2018-12-11 14:00 UTC, ykzts approved these changes

2018-12-12 21:33 UTC, Gargron requested changes

2018-12-12 21:33 UTC, Gargron commented on app/views/admin/accounts/index.html.haml
> +        %th= t('admin.accounts.profile_links')
Would rather avoid adding a string for this

2018-12-14 00:47 UTC, Gargron approved these changes

2018-12-14 00:47 UTC, merged