Ignore low-confidence CharlockHolmes guesses when parsing link cards
mastodon/mastodon pull request #9510
Opened 2018-12-12 13:32 UTC by ThibG

Fixes #9466 by ignoring low-confidence `CharlockHolmes` charset guesses.

High-confidence guesses will still override server or document-specified charset, and low confidence guesses won't be used at all even if there is no server or document-specified charset, so this might not be the best way to proceed.

Note also that the “hint” given to `CharlockHolmes` as very little importance, and feeding it the correct charset may not prevent it from outputing an incorrect, low-confidence guess.

2018-12-12 13:41 UTC, ThibG commented
Weird, the tests pass in my dev environment :thinking:

2018-12-17 17:23 UTC, Gargron requested changes

2018-12-17 17:23 UTC, Gargron commented on app/services/fetch_link_card_service.rb
> +    encoding   = guess&.fetch(:confidence, 0) > 60 ? guess&.fetch(:encoding, nil) : nil
I think `nil > 60` will throw no method error

2018-12-17 18:04 UTC, ThibG commented on app/services/fetch_link_card_service.rb
> +    encoding   = guess&.fetch(:confidence, 0) > 60 ? guess&.fetch(:encoding, nil) : nil
Indeed! Addressed.

2018-12-17 18:19 UTC, Gargron approved these changes

2018-12-17 18:19 UTC, merged

2018-12-17 23:21 UTC, jomo commented
Thank you, @ThibG!