update faq with default language
mastodon/mastodon pull request #954
Opened 2017-04-05 14:32 UTC by JantsoP

Update FAQ on how to change default language of the instance? Can be modified if needed

2017-04-06 17:24 UTC, JantsoP commented
Sorry, i ment @Gargron for the help with Minio install :)

2017-04-06 17:48 UTC, JantsoP commented
Added new translation for import and export :)

2017-04-06 18:27 UTC, JantsoP commented
Add Finnish translation for emails

2017-04-07 10:50 UTC, Gargron requested changes

2017-04-07 10:50 UTC, Gargron commented on docs/Using-Mastodon/FAQ.md
> +#### How i can change the default language of the Instance?
Either remove in favour of #1145 being self-described in the .env file, or refer to it. Modifying `i18n.default_locale` is a bad idea in this application, here `:en` is the most complete localization.

2017-04-07 10:50 UTC, Gargron commented on .env.production.sample
> +# S3_BUCKET=check minio's first launch for details
I suggest moving "check minio's details etc" text into a comment line/block. The commented out variables should still contain valid (or empty) values.

2017-04-07 10:56 UTC, JantsoP commented
All issues fixed?

2017-04-07 10:57 UTC, Gargron approved these changes

2017-04-07 10:58 UTC, merged