Reduce toot size limit for language detection
mastodon/mastodon pull request #9760
Opened 2019-01-08 14:25 UTC by stevenroose

Improves https://github.com/tootsuite/mastodon/issues/9550

2019-01-08 14:31 UTC, ThibG commented
The issue is that automatic detection for such short texts is completely unreliable :/

2019-01-13 17:09 UTC, faho commented
>The issue is that automatic detection for such short texts is completely unreliable :/

Is there any data about that?

Because, anecdotally, 140 is long enough to basically be useless, and google translate at least (no idea if that actually uses cld3 in the background) can detect the language for much shorter texts.

2019-01-13 17:13 UTC, Gargron commented
Google Translate doesn't use CLD3, they use machine learning and it's trained on a very large dataset. Not something you can replicate on a small standalone mastodon server.

2019-01-13 17:19 UTC, faho commented
>Google Translate doesn't use CLD3

Sure, but that shows that it's _possible_ to reliably detect languages with texts shorter than 140 characters.

So I'd like to know if anyone knows why 140 was picked, and if it's maybe possible that CLD3 could handle shorter texts?

Maybe 20 is too short, but 40 or 60 would work?

2019-01-13 19:34 UTC, Gargron commented
140 was picked arbitrarily after some back and forth testing, as documented in the screenshot here: #8010. I'm not claiming it's a scientific number, but the less characters there are, the more wildly inaccurate CLD3 is.

2019-01-13 20:59 UTC, faho commented
>140 was picked arbitrarily after some back and forth testing, as documented in the screenshot here: 

That screenshot shows:

- It's worthless for single words - which is obvious, since e.g. "die" is both english and german ("die bart, die"), and that'll happen frequently.

- It gives you a "probability" score (which I'm guessing is also used for the "reliable?" bool?) that is worthless for single words, but not all that bad for longer sentences? For the two longer tests, it's < 50% (and the longest is a correct guess). These are 51/24 characters, which is a far cry from the 140 that is used currently!

So it doesn't seem all that awful to use a sliding scale? I.e. for things under 40 characters or things marked unreliable, don't trust the detection.

2019-01-13 21:11 UTC, nightpool commented
If i remember correctly, CLD used to contain a disclaimer that it wasn't supposed to be used on texts smaller then N size (i believe around 300-500). We're using it with 140 but I wouldn't want to go any lowers.

2019-01-16 18:54 UTC, stevenroose commented
Are there any alternative language detection systems?

Of course, I still consider #9550 to be the better way to go here.

2019-02-02 18:27 UTC, Gargron requested changes

2019-02-12 14:57 UTC, stevenroose commented on app/lib/language_detector.rb
> +  CHARACTER_THRESHOLD = 20
I don't see why a language detector wouldn't be able to correctly classify toots like `Yes!`, `Good idea.`, `Je ne sais pas.`, `Donde esta la bilbioteca?` etc with a high reliability.

2019-03-15 02:51 UTC, Gargron commented on app/lib/language_detector.rb
> +  CHARACTER_THRESHOLD = 20
Sorry for a late response. But you don't need to believe my word, just play around with the detector and see how reliable it is for those phrases.

![grafik](https://user-images.githubusercontent.com/184731/54405049-a9aa4f00-46d5-11e9-8ff2-d1bd1e5eadec.png)

2019-03-15 04:07 UTC, closed without merging