Add toot export
mastodon/mastodon pull request #978
Opened 2017-04-05 16:45 UTC by SirCmpwn

Import can come separately. Requires some discussion and buy-in from the maintainers on a strategy.

2017-04-05 17:48 UTC, Gargron commented
Commendable effort, but my concern is: how does this behave when someone has, say, 90,000 toots?

The file returned would be huge, but most importantly, the request to generate it would take so long it would time out. Can you think of any ways to mitigate this?

2017-04-05 17:55 UTC, SirCmpwn commented
Perhaps we can set an upper limit on it, like it only exports up to the most recent 5000 toots?

2017-04-06 08:48 UTC, papjul commented
Maybe we can get inspired by how Twitter handles it?
It generates in a background task and when it’s ready you receive an email to download zip file. You should also put a limit of a generation every X hours so the same file is served if requested multiple times during a certain period of time.

2017-04-24 01:16 UTC, mjankowski requested changes
Needs rebase.

2017-04-24 01:16 UTC, mjankowski commented on app/controllers/settings/exports_controller.rb
> +include RoutingHelper
What is this adding?

2017-04-29 10:00 UTC, ashfurrow commented
It sounds like there are some technical details that need to be resolved before we can review this. I'm going to suggest we move this into a issue instead of a pull request, and we can resolve things there?

2017-07-06 22:23 UTC, Gargron commented
Closing this down, toot export is on the backburner, this is incomplete, and has been inactive for a while. But uhh, in case you are reading this, OP, I do thank you for the effort!

2017-07-06 22:23 UTC, closed without merging