Reject existing Follow in addition to sending a Block
mastodon/mastodon pull request #9811
Opened 2019-01-14 19:48 UTC by ThibG

Mastodon expects remote servers to remove follow relationships upon receiving
a Block. However, the spec only evokes Block activities in a C2S context, never
in a S2S context.

This PR, in addition to federating the Block, explicitly sends a Reject for any
affected follow relationship, which makes a bit more sense with regards to the
spec.

Marked Work in Progress as I have to check the generated Activity.

2019-01-17 19:12 UTC, Gargron requested changes

2019-01-17 19:12 UTC, Gargron commented on app/services/unfollow_service.rb
> +    if follow.account.activitypub?
Use `return unless` to avoid indentation

2019-01-18 14:16 UTC, ThibG commented
(Addressed comments)

2019-01-18 14:57 UTC, Gargron approved these changes

2019-01-18 14:57 UTC, merged