Add tombstones for remote statuses
mastodon/mastodon pull request #9830
Opened 2019-01-17 12:14 UTC by ThibG

Record deleted remote statuses so that they can't be re-injected.

2019-01-17 19:10 UTC, Gargron commented on app/lib/activitypub/activity/delete.rb
> +        delete_later!(object_uri)
Maybe use inline block here since it's a single line.

2019-01-17 19:11 UTC, Gargron requested changes

2019-01-17 19:11 UTC, Gargron commented on app/lib/activitypub/activity/delete.rb
> +        delete_later!(object_uri)
Maybe use inline block here since it's a single line.

2019-01-17 19:11 UTC, Gargron commented on app/services/activitypub/process_account_service.rb
>      unless @options[:only_key]
Empty newline before next block please

2019-01-18 14:16 UTC, ThibG commented
(Addressed the comments)

2019-01-18 14:56 UTC, Gargron approved these changes

2019-01-18 14:56 UTC, merged